"""
LIEF ELF functional test suite.

Functionally test a full ELF x64 ls file.

"""

from azul_runner import FV, DataLabel, Event, JobResult, State, test_template

from azul_plugin_lief.lief_elf import LiefELF


class TestExecute(test_template.TestPlugin):
    """Parent class of all Lief ELF tests."""

    PLUGIN_TO_TEST = LiefELF

    def test_lief_elf_ls_64(self):
        """Tests on Ubuntu 18.04 'ls' x64."""
        result = self.do_execution(
            data_in=[
                (
                    DataLabel.CONTENT,
                    self.load_test_file_bytes(
                        "0d06f9724af41b13cdacea133530b9129a48450230feef9632d53d5bbb837c8c",
                        "Benign `ls` binary from debian linux.",
                    ),
                )
            ]
        )

        self.assertJobResult(
            result,
            JobResult(
                state=State(State.Label.COMPLETED),
                events=[
                    Event(
                        entity_type="binary",
                        entity_id="0d06f9724af41b13cdacea133530b9129a48450230feef9632d53d5bbb837c8c",
                        features={
                            "elf_abi_version": [FV(0)],
                            "elf_class": [FV("ELF64")],
                            "elf_data": [FV("2's complement, little endian")],
                            "elf_entrypoint": [FV(22608)],
                            "elf_export": [
                                FV("Version"),
                                FV("_IO_stdin_used"),
                                FV("__progname"),
                                FV("__progname_full"),
                                FV("_fini"),
                                FV("_init"),
                                FV("_obstack_allocated_p"),
                                FV("_obstack_begin"),
                                FV("_obstack_begin_1"),
                                FV("_obstack_free"),
                                FV("_obstack_memory_used"),
                                FV("_obstack_newchunk"),
                                FV("argmatch_die"),
                                FV("exit_failure"),
                                FV("ls_mode"),
                                FV("obstack_alloc_failed_handler"),
                                FV("optarg"),
                                FV("optind"),
                                FV("program_invocation_name"),
                                FV("program_invocation_short_name"),
                                FV("program_name"),
                                FV("quote_quoting_options"),
                                FV("quoting_style_args"),
                                FV("quoting_style_vals"),
                                FV("stderr"),
                                FV("stdout"),
                                FV("version_etc_copyright"),
                            ],
                            "elf_export_binding": [
                                FV("GLOBAL", label="Version"),
                                FV("GLOBAL", label="_IO_stdin_used"),
                                FV("GLOBAL", label="__progname"),
                                FV("GLOBAL", label="__progname_full"),
                                FV("GLOBAL", label="_fini"),
                                FV("GLOBAL", label="_init"),
                                FV("GLOBAL", label="_obstack_allocated_p"),
                                FV("GLOBAL", label="_obstack_begin"),
                                FV("GLOBAL", label="_obstack_begin_1"),
                                FV("GLOBAL", label="_obstack_free"),
                                FV("GLOBAL", label="_obstack_memory_used"),
                                FV("GLOBAL", label="_obstack_newchunk"),
                                FV("GLOBAL", label="argmatch_die"),
                                FV("GLOBAL", label="exit_failure"),
                                FV("GLOBAL", label="ls_mode"),
                                FV("GLOBAL", label="obstack_alloc_failed_handler"),
                                FV("GLOBAL", label="optarg"),
                                FV("GLOBAL", label="optind"),
                                FV("GLOBAL", label="program_name"),
                                FV("GLOBAL", label="quote_quoting_options"),
                                FV("GLOBAL", label="quoting_style_args"),
                                FV("GLOBAL", label="quoting_style_vals"),
                                FV("GLOBAL", label="stderr"),
                                FV("GLOBAL", label="stdout"),
                                FV("GLOBAL", label="version_etc_copyright"),
                                FV("WEAK", label="program_invocation_name"),
                                FV("WEAK", label="program_invocation_short_name"),
                            ],
                            "elf_export_size": [
                                FV(0, label="_fini"),
                                FV(0, label="_init"),
                                FV(4, label="_IO_stdin_used"),
                                FV(4, label="exit_failure"),
                                FV(4, label="ls_mode"),
                                FV(4, label="optind"),
                                FV(8, label="Version"),
                                FV(8, label="__progname"),
                                FV(8, label="__progname_full"),
                                FV(8, label="argmatch_die"),
                                FV(8, label="obstack_alloc_failed_handler"),
                                FV(8, label="optarg"),
                                FV(8, label="program_invocation_name"),
                                FV(8, label="program_invocation_short_name"),
                                FV(8, label="program_name"),
                                FV(8, label="stderr"),
                                FV(8, label="stdout"),
                                FV(17, label="_obstack_begin"),
                                FV(21, label="_obstack_begin_1"),
                                FV(40, label="quoting_style_vals"),
                                FV(42, label="_obstack_memory_used"),
                                FV(47, label="version_etc_copyright"),
                                FV(56, label="_obstack_allocated_p"),
                                FV(56, label="quote_quoting_options"),
                                FV(88, label="quoting_style_args"),
                                FV(106, label="_obstack_free"),
                                FV(235, label="_obstack_newchunk"),
                            ],
                            "elf_export_type": [
                                FV("FUNC", label="_fini"),
                                FV("FUNC", label="_init"),
                                FV("FUNC", label="_obstack_allocated_p"),
                                FV("FUNC", label="_obstack_begin"),
                                FV("FUNC", label="_obstack_begin_1"),
                                FV("FUNC", label="_obstack_free"),
                                FV("FUNC", label="_obstack_memory_used"),
                                FV("FUNC", label="_obstack_newchunk"),
                                FV("OBJECT", label="Version"),
                                FV("OBJECT", label="_IO_stdin_used"),
                                FV("OBJECT", label="__progname"),
                                FV("OBJECT", label="__progname_full"),
                                FV("OBJECT", label="argmatch_die"),
                                FV("OBJECT", label="exit_failure"),
                                FV("OBJECT", label="ls_mode"),
                                FV("OBJECT", label="obstack_alloc_failed_handler"),
                                FV("OBJECT", label="optarg"),
                                FV("OBJECT", label="optind"),
                                FV("OBJECT", label="program_invocation_name"),
                                FV("OBJECT", label="program_invocation_short_name"),
                                FV("OBJECT", label="program_name"),
                                FV("OBJECT", label="quote_quoting_options"),
                                FV("OBJECT", label="quoting_style_args"),
                                FV("OBJECT", label="quoting_style_vals"),
                                FV("OBJECT", label="stderr"),
                                FV("OBJECT", label="stdout"),
                                FV("OBJECT", label="version_etc_copyright"),
                            ],
                            "elf_export_value": [
                                FV(14168, label="_init"),
                                FV(87216, label="_obstack_begin"),
                                FV(87248, label="_obstack_begin_1"),
                                FV(87280, label="_obstack_newchunk"),
                                FV(87520, label="_obstack_allocated_p"),
                                FV(87584, label="_obstack_free"),
                                FV(87696, label="_obstack_memory_used"),
                                FV(90988, label="_fini"),
                                FV(91008, label="_IO_stdin_used"),
                                FV(109408, label="quoting_style_vals"),
                                FV(110272, label="version_etc_copyright"),
                                FV(2226656, label="quoting_style_args"),
                                FV(2228704, label="ls_mode"),
                                FV(2228712, label="Version"),
                                FV(2228720, label="argmatch_die"),
                                FV(2228728, label="exit_failure"),
                                FV(2228736, label="quote_quoting_options"),
                                FV(2228832, label="obstack_alloc_failed_handler"),
                                FV(2228864, label="__progname"),
                                FV(2228864, label="program_invocation_short_name"),
                                FV(2228872, label="stdout"),
                                FV(2228880, label="optind"),
                                FV(2228896, label="optarg"),
                                FV(2228904, label="__progname_full"),
                                FV(2228904, label="program_invocation_name"),
                                FV(2228928, label="stderr"),
                                FV(2233344, label="program_name"),
                            ],
                            "elf_export_version": [
                                FV("* Global *", label="Version"),
                                FV("* Global *", label="_IO_stdin_used"),
                                FV("* Global *", label="_fini"),
                                FV("* Global *", label="_init"),
                                FV("* Global *", label="_obstack_allocated_p"),
                                FV("* Global *", label="_obstack_begin"),
                                FV("* Global *", label="_obstack_begin_1"),
                                FV("* Global *", label="_obstack_free"),
                                FV("* Global *", label="_obstack_memory_used"),
                                FV("* Global *", label="_obstack_newchunk"),
                                FV("* Global *", label="argmatch_die"),
                                FV("* Global *", label="exit_failure"),
                                FV("* Global *", label="ls_mode"),
                                FV("* Global *", label="obstack_alloc_failed_handler"),
                                FV("* Global *", label="program_name"),
                                FV("* Global *", label="quote_quoting_options"),
                                FV("* Global *", label="quoting_style_args"),
                                FV("* Global *", label="quoting_style_vals"),
                                FV("* Global *", label="version_etc_copyright"),
                                FV("GLIBC_2.2.5(3)", label="__progname"),
                                FV("GLIBC_2.2.5(3)", label="__progname_full"),
                                FV("GLIBC_2.2.5(3)", label="optarg"),
                                FV("GLIBC_2.2.5(3)", label="optind"),
                                FV("GLIBC_2.2.5(3)", label="program_invocation_name"),
                                FV("GLIBC_2.2.5(3)", label="program_invocation_short_name"),
                                FV("GLIBC_2.2.5(3)", label="stderr"),
                                FV("GLIBC_2.2.5(3)", label="stdout"),
                            ],
                            "elf_export_visibility": [
                                FV("DEFAULT", label="Version"),
                                FV("DEFAULT", label="_IO_stdin_used"),
                                FV("DEFAULT", label="__progname"),
                                FV("DEFAULT", label="__progname_full"),
                                FV("DEFAULT", label="_fini"),
                                FV("DEFAULT", label="_init"),
                                FV("DEFAULT", label="_obstack_allocated_p"),
                                FV("DEFAULT", label="_obstack_begin"),
                                FV("DEFAULT", label="_obstack_begin_1"),
                                FV("DEFAULT", label="_obstack_free"),
                                FV("DEFAULT", label="_obstack_memory_used"),
                                FV("DEFAULT", label="_obstack_newchunk"),
                                FV("DEFAULT", label="argmatch_die"),
                                FV("DEFAULT", label="exit_failure"),
                                FV("DEFAULT", label="ls_mode"),
                                FV("DEFAULT", label="obstack_alloc_failed_handler"),
                                FV("DEFAULT", label="optarg"),
                                FV("DEFAULT", label="optind"),
                                FV("DEFAULT", label="program_invocation_name"),
                                FV("DEFAULT", label="program_invocation_short_name"),
                                FV("DEFAULT", label="program_name"),
                                FV("DEFAULT", label="quote_quoting_options"),
                                FV("DEFAULT", label="quoting_style_args"),
                                FV("DEFAULT", label="quoting_style_vals"),
                                FV("DEFAULT", label="stderr"),
                                FV("DEFAULT", label="stdout"),
                                FV("DEFAULT", label="version_etc_copyright"),
                            ],
                            "elf_hdr_version": [FV("1 (current)")],
                            "elf_header_size": [FV(64)],
                            "elf_import": [
                                FV("__assert_fail"),
                                FV("__ctype_b_loc"),
                                FV("__ctype_get_mb_cur_max"),
                                FV("__ctype_tolower_loc"),
                                FV("__ctype_toupper_loc"),
                                FV("__cxa_atexit"),
                                FV("__cxa_finalize"),
                                FV("__errno_location"),
                                FV("__fpending"),
                                FV("__fprintf_chk"),
                                FV("__freading"),
                                FV("__fxstat"),
                                FV("__libc_start_main"),
                                FV("__lxstat"),
                                FV("__memcpy_chk"),
                                FV("__overflow"),
                                FV("__printf_chk"),
                                FV("__snprintf_chk"),
                                FV("__sprintf_chk"),
                                FV("__stack_chk_fail"),
                                FV("__strtoul_internal"),
                                FV("__uflow"),
                                FV("__xstat"),
                                FV("_exit"),
                                FV("_setjmp"),
                                FV("abort"),
                                FV("bindtextdomain"),
                                FV("calloc"),
                                FV("clock_gettime"),
                                FV("close"),
                                FV("closedir"),
                                FV("dcgettext"),
                                FV("dirfd"),
                                FV("error"),
                                FV("exit"),
                                FV("fclose"),
                                FV("fdopen"),
                                FV("fflush"),
                                FV("fflush_unlocked"),
                                FV("fgetfilecon"),
                                FV("fileno"),
                                FV("fnmatch"),
                                FV("fputs_unlocked"),
                                FV("free"),
                                FV("freecon"),
                                FV("fscanf"),
                                FV("fseeko"),
                                FV("fwrite"),
                                FV("fwrite_unlocked"),
                                FV("getcwd"),
                                FV("getenv"),
                                FV("getfilecon"),
                                FV("getgrgid"),
                                FV("getgrnam"),
                                FV("gethostname"),
                                FV("getopt_long"),
                                FV("getpwnam"),
                                FV("getpwuid"),
                                FV("gettimeofday"),
                                FV("getxattr"),
                                FV("gmtime_r"),
                                FV("ioctl"),
                                FV("isatty"),
                                FV("iswcntrl"),
                                FV("iswprint"),
                                FV("lgetfilecon"),
                                FV("localeconv"),
                                FV("localtime_r"),
                                FV("lseek"),
                                FV("malloc"),
                                FV("mbrtowc"),
                                FV("mbsinit"),
                                FV("mbstowcs"),
                                FV("memcmp"),
                                FV("memcpy"),
                                FV("memmove"),
                                FV("mempcpy"),
                                FV("memset"),
                                FV("mktime"),
                                FV("nl_langinfo"),
                                FV("open"),
                                FV("opendir"),
                                FV("raise"),
                                FV("readdir"),
                                FV("readlink"),
                                FV("realloc"),
                                FV("setenv"),
                                FV("setlocale"),
                                FV("sigaction"),
                                FV("sigaddset"),
                                FV("sigemptyset"),
                                FV("sigismember"),
                                FV("signal"),
                                FV("sigprocmask"),
                                FV("snprintf"),
                                FV("stpncpy"),
                                FV("strchr"),
                                FV("strcmp"),
                                FV("strcoll"),
                                FV("strcpy"),
                                FV("strftime"),
                                FV("strlen"),
                                FV("strncmp"),
                                FV("strrchr"),
                                FV("strspn"),
                                FV("strtoul"),
                                FV("tcgetpgrp"),
                                FV("textdomain"),
                                FV("timegm"),
                                FV("tzset"),
                                FV("ungetc"),
                                FV("unsetenv"),
                                FV("wcstombs"),
                                FV("wcswidth"),
                                FV("wcwidth"),
                            ],
                            "elf_import_binding": [
                                FV("GLOBAL", label="__assert_fail"),
                                FV("GLOBAL", label="__ctype_b_loc"),
                                FV("GLOBAL", label="__ctype_get_mb_cur_max"),
                                FV("GLOBAL", label="__ctype_tolower_loc"),
                                FV("GLOBAL", label="__ctype_toupper_loc"),
                                FV("GLOBAL", label="__cxa_atexit"),
                                FV("GLOBAL", label="__errno_location"),
                                FV("GLOBAL", label="__fpending"),
                                FV("GLOBAL", label="__fprintf_chk"),
                                FV("GLOBAL", label="__freading"),
                                FV("GLOBAL", label="__fxstat"),
                                FV("GLOBAL", label="__libc_start_main"),
                                FV("GLOBAL", label="__lxstat"),
                                FV("GLOBAL", label="__memcpy_chk"),
                                FV("GLOBAL", label="__overflow"),
                                FV("GLOBAL", label="__printf_chk"),
                                FV("GLOBAL", label="__snprintf_chk"),
                                FV("GLOBAL", label="__sprintf_chk"),
                                FV("GLOBAL", label="__stack_chk_fail"),
                                FV("GLOBAL", label="__strtoul_internal"),
                                FV("GLOBAL", label="__uflow"),
                                FV("GLOBAL", label="__xstat"),
                                FV("GLOBAL", label="_exit"),
                                FV("GLOBAL", label="_setjmp"),
                                FV("GLOBAL", label="abort"),
                                FV("GLOBAL", label="bindtextdomain"),
                                FV("GLOBAL", label="calloc"),
                                FV("GLOBAL", label="clock_gettime"),
                                FV("GLOBAL", label="close"),
                                FV("GLOBAL", label="closedir"),
                                FV("GLOBAL", label="dcgettext"),
                                FV("GLOBAL", label="dirfd"),
                                FV("GLOBAL", label="error"),
                                FV("GLOBAL", label="exit"),
                                FV("GLOBAL", label="fclose"),
                                FV("GLOBAL", label="fdopen"),
                                FV("GLOBAL", label="fflush"),
                                FV("GLOBAL", label="fflush_unlocked"),
                                FV("GLOBAL", label="fgetfilecon"),
                                FV("GLOBAL", label="fileno"),
                                FV("GLOBAL", label="fnmatch"),
                                FV("GLOBAL", label="fputs_unlocked"),
                                FV("GLOBAL", label="free"),
                                FV("GLOBAL", label="freecon"),
                                FV("GLOBAL", label="fscanf"),
                                FV("GLOBAL", label="fseeko"),
                                FV("GLOBAL", label="fwrite"),
                                FV("GLOBAL", label="fwrite_unlocked"),
                                FV("GLOBAL", label="getcwd"),
                                FV("GLOBAL", label="getenv"),
                                FV("GLOBAL", label="getfilecon"),
                                FV("GLOBAL", label="getgrgid"),
                                FV("GLOBAL", label="getgrnam"),
                                FV("GLOBAL", label="gethostname"),
                                FV("GLOBAL", label="getopt_long"),
                                FV("GLOBAL", label="getpwnam"),
                                FV("GLOBAL", label="getpwuid"),
                                FV("GLOBAL", label="gettimeofday"),
                                FV("GLOBAL", label="getxattr"),
                                FV("GLOBAL", label="gmtime_r"),
                                FV("GLOBAL", label="ioctl"),
                                FV("GLOBAL", label="isatty"),
                                FV("GLOBAL", label="iswcntrl"),
                                FV("GLOBAL", label="iswprint"),
                                FV("GLOBAL", label="lgetfilecon"),
                                FV("GLOBAL", label="localeconv"),
                                FV("GLOBAL", label="localtime_r"),
                                FV("GLOBAL", label="lseek"),
                                FV("GLOBAL", label="malloc"),
                                FV("GLOBAL", label="mbrtowc"),
                                FV("GLOBAL", label="mbsinit"),
                                FV("GLOBAL", label="mbstowcs"),
                                FV("GLOBAL", label="memcmp"),
                                FV("GLOBAL", label="memcpy"),
                                FV("GLOBAL", label="memmove"),
                                FV("GLOBAL", label="mempcpy"),
                                FV("GLOBAL", label="memset"),
                                FV("GLOBAL", label="mktime"),
                                FV("GLOBAL", label="nl_langinfo"),
                                FV("GLOBAL", label="open"),
                                FV("GLOBAL", label="opendir"),
                                FV("GLOBAL", label="raise"),
                                FV("GLOBAL", label="readdir"),
                                FV("GLOBAL", label="readlink"),
                                FV("GLOBAL", label="realloc"),
                                FV("GLOBAL", label="setenv"),
                                FV("GLOBAL", label="setlocale"),
                                FV("GLOBAL", label="sigaction"),
                                FV("GLOBAL", label="sigaddset"),
                                FV("GLOBAL", label="sigemptyset"),
                                FV("GLOBAL", label="sigismember"),
                                FV("GLOBAL", label="signal"),
                                FV("GLOBAL", label="sigprocmask"),
                                FV("GLOBAL", label="snprintf"),
                                FV("GLOBAL", label="stpncpy"),
                                FV("GLOBAL", label="strchr"),
                                FV("GLOBAL", label="strcmp"),
                                FV("GLOBAL", label="strcoll"),
                                FV("GLOBAL", label="strcpy"),
                                FV("GLOBAL", label="strftime"),
                                FV("GLOBAL", label="strlen"),
                                FV("GLOBAL", label="strncmp"),
                                FV("GLOBAL", label="strrchr"),
                                FV("GLOBAL", label="strspn"),
                                FV("GLOBAL", label="strtoul"),
                                FV("GLOBAL", label="tcgetpgrp"),
                                FV("GLOBAL", label="textdomain"),
                                FV("GLOBAL", label="timegm"),
                                FV("GLOBAL", label="tzset"),
                                FV("GLOBAL", label="ungetc"),
                                FV("GLOBAL", label="unsetenv"),
                                FV("GLOBAL", label="wcstombs"),
                                FV("GLOBAL", label="wcswidth"),
                                FV("GLOBAL", label="wcwidth"),
                                FV("WEAK", label="__cxa_finalize"),
                            ],
                            "elf_import_size": [
                                FV(0, label="__assert_fail"),
                                FV(0, label="__ctype_b_loc"),
                                FV(0, label="__ctype_get_mb_cur_max"),
                                FV(0, label="__ctype_tolower_loc"),
                                FV(0, label="__ctype_toupper_loc"),
                                FV(0, label="__cxa_atexit"),
                                FV(0, label="__cxa_finalize"),
                                FV(0, label="__errno_location"),
                                FV(0, label="__fpending"),
                                FV(0, label="__fprintf_chk"),
                                FV(0, label="__freading"),
                                FV(0, label="__fxstat"),
                                FV(0, label="__libc_start_main"),
                                FV(0, label="__lxstat"),
                                FV(0, label="__memcpy_chk"),
                                FV(0, label="__overflow"),
                                FV(0, label="__printf_chk"),
                                FV(0, label="__snprintf_chk"),
                                FV(0, label="__sprintf_chk"),
                                FV(0, label="__stack_chk_fail"),
                                FV(0, label="__strtoul_internal"),
                                FV(0, label="__uflow"),
                                FV(0, label="__xstat"),
                                FV(0, label="_exit"),
                                FV(0, label="_setjmp"),
                                FV(0, label="abort"),
                                FV(0, label="bindtextdomain"),
                                FV(0, label="calloc"),
                                FV(0, label="clock_gettime"),
                                FV(0, label="close"),
                                FV(0, label="closedir"),
                                FV(0, label="dcgettext"),
                                FV(0, label="dirfd"),
                                FV(0, label="error"),
                                FV(0, label="exit"),
                                FV(0, label="fclose"),
                                FV(0, label="fdopen"),
                                FV(0, label="fflush"),
                                FV(0, label="fflush_unlocked"),
                                FV(0, label="fgetfilecon"),
                                FV(0, label="fileno"),
                                FV(0, label="fnmatch"),
                                FV(0, label="fputs_unlocked"),
                                FV(0, label="free"),
                                FV(0, label="freecon"),
                                FV(0, label="fscanf"),
                                FV(0, label="fseeko"),
                                FV(0, label="fwrite"),
                                FV(0, label="fwrite_unlocked"),
                                FV(0, label="getcwd"),
                                FV(0, label="getenv"),
                                FV(0, label="getfilecon"),
                                FV(0, label="getgrgid"),
                                FV(0, label="getgrnam"),
                                FV(0, label="gethostname"),
                                FV(0, label="getopt_long"),
                                FV(0, label="getpwnam"),
                                FV(0, label="getpwuid"),
                                FV(0, label="gettimeofday"),
                                FV(0, label="getxattr"),
                                FV(0, label="gmtime_r"),
                                FV(0, label="ioctl"),
                                FV(0, label="isatty"),
                                FV(0, label="iswcntrl"),
                                FV(0, label="iswprint"),
                                FV(0, label="lgetfilecon"),
                                FV(0, label="localeconv"),
                                FV(0, label="localtime_r"),
                                FV(0, label="lseek"),
                                FV(0, label="malloc"),
                                FV(0, label="mbrtowc"),
                                FV(0, label="mbsinit"),
                                FV(0, label="mbstowcs"),
                                FV(0, label="memcmp"),
                                FV(0, label="memcpy"),
                                FV(0, label="memmove"),
                                FV(0, label="mempcpy"),
                                FV(0, label="memset"),
                                FV(0, label="mktime"),
                                FV(0, label="nl_langinfo"),
                                FV(0, label="open"),
                                FV(0, label="opendir"),
                                FV(0, label="raise"),
                                FV(0, label="readdir"),
                                FV(0, label="readlink"),
                                FV(0, label="realloc"),
                                FV(0, label="setenv"),
                                FV(0, label="setlocale"),
                                FV(0, label="sigaction"),
                                FV(0, label="sigaddset"),
                                FV(0, label="sigemptyset"),
                                FV(0, label="sigismember"),
                                FV(0, label="signal"),
                                FV(0, label="sigprocmask"),
                                FV(0, label="snprintf"),
                                FV(0, label="stpncpy"),
                                FV(0, label="strchr"),
                                FV(0, label="strcmp"),
                                FV(0, label="strcoll"),
                                FV(0, label="strcpy"),
                                FV(0, label="strftime"),
                                FV(0, label="strlen"),
                                FV(0, label="strncmp"),
                                FV(0, label="strrchr"),
                                FV(0, label="strspn"),
                                FV(0, label="strtoul"),
                                FV(0, label="tcgetpgrp"),
                                FV(0, label="textdomain"),
                                FV(0, label="timegm"),
                                FV(0, label="tzset"),
                                FV(0, label="ungetc"),
                                FV(0, label="unsetenv"),
                                FV(0, label="wcstombs"),
                                FV(0, label="wcswidth"),
                                FV(0, label="wcwidth"),
                            ],
                            "elf_import_type": [
                                FV("FUNC", label="__assert_fail"),
                                FV("FUNC", label="__ctype_b_loc"),
                                FV("FUNC", label="__ctype_get_mb_cur_max"),
                                FV("FUNC", label="__ctype_tolower_loc"),
                                FV("FUNC", label="__ctype_toupper_loc"),
                                FV("FUNC", label="__cxa_atexit"),
                                FV("FUNC", label="__cxa_finalize"),
                                FV("FUNC", label="__errno_location"),
                                FV("FUNC", label="__fpending"),
                                FV("FUNC", label="__fprintf_chk"),
                                FV("FUNC", label="__freading"),
                                FV("FUNC", label="__fxstat"),
                                FV("FUNC", label="__libc_start_main"),
                                FV("FUNC", label="__lxstat"),
                                FV("FUNC", label="__memcpy_chk"),
                                FV("FUNC", label="__overflow"),
                                FV("FUNC", label="__printf_chk"),
                                FV("FUNC", label="__snprintf_chk"),
                                FV("FUNC", label="__sprintf_chk"),
                                FV("FUNC", label="__stack_chk_fail"),
                                FV("FUNC", label="__strtoul_internal"),
                                FV("FUNC", label="__uflow"),
                                FV("FUNC", label="__xstat"),
                                FV("FUNC", label="_exit"),
                                FV("FUNC", label="_setjmp"),
                                FV("FUNC", label="abort"),
                                FV("FUNC", label="bindtextdomain"),
                                FV("FUNC", label="calloc"),
                                FV("FUNC", label="clock_gettime"),
                                FV("FUNC", label="close"),
                                FV("FUNC", label="closedir"),
                                FV("FUNC", label="dcgettext"),
                                FV("FUNC", label="dirfd"),
                                FV("FUNC", label="error"),
                                FV("FUNC", label="exit"),
                                FV("FUNC", label="fclose"),
                                FV("FUNC", label="fdopen"),
                                FV("FUNC", label="fflush"),
                                FV("FUNC", label="fflush_unlocked"),
                                FV("FUNC", label="fgetfilecon"),
                                FV("FUNC", label="fileno"),
                                FV("FUNC", label="fnmatch"),
                                FV("FUNC", label="fputs_unlocked"),
                                FV("FUNC", label="free"),
                                FV("FUNC", label="freecon"),
                                FV("FUNC", label="fscanf"),
                                FV("FUNC", label="fseeko"),
                                FV("FUNC", label="fwrite"),
                                FV("FUNC", label="fwrite_unlocked"),
                                FV("FUNC", label="getcwd"),
                                FV("FUNC", label="getenv"),
                                FV("FUNC", label="getfilecon"),
                                FV("FUNC", label="getgrgid"),
                                FV("FUNC", label="getgrnam"),
                                FV("FUNC", label="gethostname"),
                                FV("FUNC", label="getopt_long"),
                                FV("FUNC", label="getpwnam"),
                                FV("FUNC", label="getpwuid"),
                                FV("FUNC", label="gettimeofday"),
                                FV("FUNC", label="getxattr"),
                                FV("FUNC", label="gmtime_r"),
                                FV("FUNC", label="ioctl"),
                                FV("FUNC", label="isatty"),
                                FV("FUNC", label="iswcntrl"),
                                FV("FUNC", label="iswprint"),
                                FV("FUNC", label="lgetfilecon"),
                                FV("FUNC", label="localeconv"),
                                FV("FUNC", label="localtime_r"),
                                FV("FUNC", label="lseek"),
                                FV("FUNC", label="malloc"),
                                FV("FUNC", label="mbrtowc"),
                                FV("FUNC", label="mbsinit"),
                                FV("FUNC", label="mbstowcs"),
                                FV("FUNC", label="memcmp"),
                                FV("FUNC", label="memcpy"),
                                FV("FUNC", label="memmove"),
                                FV("FUNC", label="mempcpy"),
                                FV("FUNC", label="memset"),
                                FV("FUNC", label="mktime"),
                                FV("FUNC", label="nl_langinfo"),
                                FV("FUNC", label="open"),
                                FV("FUNC", label="opendir"),
                                FV("FUNC", label="raise"),
                                FV("FUNC", label="readdir"),
                                FV("FUNC", label="readlink"),
                                FV("FUNC", label="realloc"),
                                FV("FUNC", label="setenv"),
                                FV("FUNC", label="setlocale"),
                                FV("FUNC", label="sigaction"),
                                FV("FUNC", label="sigaddset"),
                                FV("FUNC", label="sigemptyset"),
                                FV("FUNC", label="sigismember"),
                                FV("FUNC", label="signal"),
                                FV("FUNC", label="sigprocmask"),
                                FV("FUNC", label="snprintf"),
                                FV("FUNC", label="stpncpy"),
                                FV("FUNC", label="strchr"),
                                FV("FUNC", label="strcmp"),
                                FV("FUNC", label="strcoll"),
                                FV("FUNC", label="strcpy"),
                                FV("FUNC", label="strftime"),
                                FV("FUNC", label="strlen"),
                                FV("FUNC", label="strncmp"),
                                FV("FUNC", label="strrchr"),
                                FV("FUNC", label="strspn"),
                                FV("FUNC", label="strtoul"),
                                FV("FUNC", label="tcgetpgrp"),
                                FV("FUNC", label="textdomain"),
                                FV("FUNC", label="timegm"),
                                FV("FUNC", label="tzset"),
                                FV("FUNC", label="ungetc"),
                                FV("FUNC", label="unsetenv"),
                                FV("FUNC", label="wcstombs"),
                                FV("FUNC", label="wcswidth"),
                                FV("FUNC", label="wcwidth"),
                            ],
                            "elf_import_value": [
                                FV(0, label="__assert_fail"),
                                FV(0, label="__ctype_b_loc"),
                                FV(0, label="__ctype_get_mb_cur_max"),
                                FV(0, label="__ctype_tolower_loc"),
                                FV(0, label="__ctype_toupper_loc"),
                                FV(0, label="__cxa_atexit"),
                                FV(0, label="__cxa_finalize"),
                                FV(0, label="__errno_location"),
                                FV(0, label="__fpending"),
                                FV(0, label="__fprintf_chk"),
                                FV(0, label="__freading"),
                                FV(0, label="__fxstat"),
                                FV(0, label="__libc_start_main"),
                                FV(0, label="__lxstat"),
                                FV(0, label="__memcpy_chk"),
                                FV(0, label="__overflow"),
                                FV(0, label="__printf_chk"),
                                FV(0, label="__snprintf_chk"),
                                FV(0, label="__sprintf_chk"),
                                FV(0, label="__stack_chk_fail"),
                                FV(0, label="__strtoul_internal"),
                                FV(0, label="__uflow"),
                                FV(0, label="__xstat"),
                                FV(0, label="_exit"),
                                FV(0, label="_setjmp"),
                                FV(0, label="abort"),
                                FV(0, label="bindtextdomain"),
                                FV(0, label="calloc"),
                                FV(0, label="clock_gettime"),
                                FV(0, label="close"),
                                FV(0, label="closedir"),
                                FV(0, label="dcgettext"),
                                FV(0, label="dirfd"),
                                FV(0, label="error"),
                                FV(0, label="exit"),
                                FV(0, label="fclose"),
                                FV(0, label="fdopen"),
                                FV(0, label="fflush"),
                                FV(0, label="fflush_unlocked"),
                                FV(0, label="fgetfilecon"),
                                FV(0, label="fileno"),
                                FV(0, label="fnmatch"),
                                FV(0, label="fputs_unlocked"),
                                FV(0, label="free"),
                                FV(0, label="freecon"),
                                FV(0, label="fscanf"),
                                FV(0, label="fseeko"),
                                FV(0, label="fwrite"),
                                FV(0, label="fwrite_unlocked"),
                                FV(0, label="getcwd"),
                                FV(0, label="getenv"),
                                FV(0, label="getfilecon"),
                                FV(0, label="getgrgid"),
                                FV(0, label="getgrnam"),
                                FV(0, label="gethostname"),
                                FV(0, label="getopt_long"),
                                FV(0, label="getpwnam"),
                                FV(0, label="getpwuid"),
                                FV(0, label="gettimeofday"),
                                FV(0, label="getxattr"),
                                FV(0, label="gmtime_r"),
                                FV(0, label="ioctl"),
                                FV(0, label="isatty"),
                                FV(0, label="iswcntrl"),
                                FV(0, label="iswprint"),
                                FV(0, label="lgetfilecon"),
                                FV(0, label="localeconv"),
                                FV(0, label="localtime_r"),
                                FV(0, label="lseek"),
                                FV(0, label="malloc"),
                                FV(0, label="mbrtowc"),
                                FV(0, label="mbsinit"),
                                FV(0, label="mbstowcs"),
                                FV(0, label="memcmp"),
                                FV(0, label="memcpy"),
                                FV(0, label="memmove"),
                                FV(0, label="mempcpy"),
                                FV(0, label="memset"),
                                FV(0, label="mktime"),
                                FV(0, label="nl_langinfo"),
                                FV(0, label="open"),
                                FV(0, label="opendir"),
                                FV(0, label="raise"),
                                FV(0, label="readdir"),
                                FV(0, label="readlink"),
                                FV(0, label="realloc"),
                                FV(0, label="setenv"),
                                FV(0, label="setlocale"),
                                FV(0, label="sigaction"),
                                FV(0, label="sigaddset"),
                                FV(0, label="sigemptyset"),
                                FV(0, label="sigismember"),
                                FV(0, label="signal"),
                                FV(0, label="sigprocmask"),
                                FV(0, label="snprintf"),
                                FV(0, label="stpncpy"),
                                FV(0, label="strchr"),
                                FV(0, label="strcmp"),
                                FV(0, label="strcoll"),
                                FV(0, label="strcpy"),
                                FV(0, label="strftime"),
                                FV(0, label="strlen"),
                                FV(0, label="strncmp"),
                                FV(0, label="strrchr"),
                                FV(0, label="strspn"),
                                FV(0, label="strtoul"),
                                FV(0, label="tcgetpgrp"),
                                FV(0, label="textdomain"),
                                FV(0, label="timegm"),
                                FV(0, label="tzset"),
                                FV(0, label="ungetc"),
                                FV(0, label="unsetenv"),
                                FV(0, label="wcstombs"),
                                FV(0, label="wcswidth"),
                                FV(0, label="wcwidth"),
                            ],
                            "elf_import_version": [
                                FV("* Local *", label="fgetfilecon"),
                                FV("* Local *", label="freecon"),
                                FV("* Local *", label="getfilecon"),
                                FV("* Local *", label="lgetfilecon"),
                                FV("GLIBC_2.14(7)", label="memcpy"),
                                FV("GLIBC_2.17(5)", label="clock_gettime"),
                                FV("GLIBC_2.2.5(3)", label="__assert_fail"),
                                FV("GLIBC_2.2.5(3)", label="__ctype_get_mb_cur_max"),
                                FV("GLIBC_2.2.5(3)", label="__cxa_atexit"),
                                FV("GLIBC_2.2.5(3)", label="__cxa_finalize"),
                                FV("GLIBC_2.2.5(3)", label="__errno_location"),
                                FV("GLIBC_2.2.5(3)", label="__fpending"),
                                FV("GLIBC_2.2.5(3)", label="__freading"),
                                FV("GLIBC_2.2.5(3)", label="__fxstat"),
                                FV("GLIBC_2.2.5(3)", label="__libc_start_main"),
                                FV("GLIBC_2.2.5(3)", label="__lxstat"),
                                FV("GLIBC_2.2.5(3)", label="__overflow"),
                                FV("GLIBC_2.2.5(3)", label="__strtoul_internal"),
                                FV("GLIBC_2.2.5(3)", label="__uflow"),
                                FV("GLIBC_2.2.5(3)", label="__xstat"),
                                FV("GLIBC_2.2.5(3)", label="_exit"),
                                FV("GLIBC_2.2.5(3)", label="_setjmp"),
                                FV("GLIBC_2.2.5(3)", label="abort"),
                                FV("GLIBC_2.2.5(3)", label="bindtextdomain"),
                                FV("GLIBC_2.2.5(3)", label="calloc"),
                                FV("GLIBC_2.2.5(3)", label="close"),
                                FV("GLIBC_2.2.5(3)", label="closedir"),
                                FV("GLIBC_2.2.5(3)", label="dcgettext"),
                                FV("GLIBC_2.2.5(3)", label="dirfd"),
                                FV("GLIBC_2.2.5(3)", label="error"),
                                FV("GLIBC_2.2.5(3)", label="exit"),
                                FV("GLIBC_2.2.5(3)", label="fclose"),
                                FV("GLIBC_2.2.5(3)", label="fdopen"),
                                FV("GLIBC_2.2.5(3)", label="fflush"),
                                FV("GLIBC_2.2.5(3)", label="fflush_unlocked"),
                                FV("GLIBC_2.2.5(3)", label="fileno"),
                                FV("GLIBC_2.2.5(3)", label="fnmatch"),
                                FV("GLIBC_2.2.5(3)", label="fputs_unlocked"),
                                FV("GLIBC_2.2.5(3)", label="free"),
                                FV("GLIBC_2.2.5(3)", label="fscanf"),
                                FV("GLIBC_2.2.5(3)", label="fseeko"),
                                FV("GLIBC_2.2.5(3)", label="fwrite"),
                                FV("GLIBC_2.2.5(3)", label="fwrite_unlocked"),
                                FV("GLIBC_2.2.5(3)", label="getcwd"),
                                FV("GLIBC_2.2.5(3)", label="getenv"),
                                FV("GLIBC_2.2.5(3)", label="getgrgid"),
                                FV("GLIBC_2.2.5(3)", label="getgrnam"),
                                FV("GLIBC_2.2.5(3)", label="gethostname"),
                                FV("GLIBC_2.2.5(3)", label="getopt_long"),
                                FV("GLIBC_2.2.5(3)", label="getpwnam"),
                                FV("GLIBC_2.2.5(3)", label="getpwuid"),
                                FV("GLIBC_2.2.5(3)", label="gettimeofday"),
                                FV("GLIBC_2.2.5(3)", label="gmtime_r"),
                                FV("GLIBC_2.2.5(3)", label="ioctl"),
                                FV("GLIBC_2.2.5(3)", label="isatty"),
                                FV("GLIBC_2.2.5(3)", label="iswcntrl"),
                                FV("GLIBC_2.2.5(3)", label="iswprint"),
                                FV("GLIBC_2.2.5(3)", label="localeconv"),
                                FV("GLIBC_2.2.5(3)", label="localtime_r"),
                                FV("GLIBC_2.2.5(3)", label="lseek"),
                                FV("GLIBC_2.2.5(3)", label="malloc"),
                                FV("GLIBC_2.2.5(3)", label="mbrtowc"),
                                FV("GLIBC_2.2.5(3)", label="mbsinit"),
                                FV("GLIBC_2.2.5(3)", label="mbstowcs"),
                                FV("GLIBC_2.2.5(3)", label="memcmp"),
                                FV("GLIBC_2.2.5(3)", label="memmove"),
                                FV("GLIBC_2.2.5(3)", label="mempcpy"),
                                FV("GLIBC_2.2.5(3)", label="memset"),
                                FV("GLIBC_2.2.5(3)", label="mktime"),
                                FV("GLIBC_2.2.5(3)", label="nl_langinfo"),
                                FV("GLIBC_2.2.5(3)", label="open"),
                                FV("GLIBC_2.2.5(3)", label="opendir"),
                                FV("GLIBC_2.2.5(3)", label="raise"),
                                FV("GLIBC_2.2.5(3)", label="readdir"),
                                FV("GLIBC_2.2.5(3)", label="readlink"),
                                FV("GLIBC_2.2.5(3)", label="realloc"),
                                FV("GLIBC_2.2.5(3)", label="setenv"),
                                FV("GLIBC_2.2.5(3)", label="setlocale"),
                                FV("GLIBC_2.2.5(3)", label="sigaction"),
                                FV("GLIBC_2.2.5(3)", label="sigaddset"),
                                FV("GLIBC_2.2.5(3)", label="sigemptyset"),
                                FV("GLIBC_2.2.5(3)", label="sigismember"),
                                FV("GLIBC_2.2.5(3)", label="signal"),
                                FV("GLIBC_2.2.5(3)", label="sigprocmask"),
                                FV("GLIBC_2.2.5(3)", label="snprintf"),
                                FV("GLIBC_2.2.5(3)", label="stpncpy"),
                                FV("GLIBC_2.2.5(3)", label="strchr"),
                                FV("GLIBC_2.2.5(3)", label="strcmp"),
                                FV("GLIBC_2.2.5(3)", label="strcoll"),
                                FV("GLIBC_2.2.5(3)", label="strcpy"),
                                FV("GLIBC_2.2.5(3)", label="strftime"),
                                FV("GLIBC_2.2.5(3)", label="strlen"),
                                FV("GLIBC_2.2.5(3)", label="strncmp"),
                                FV("GLIBC_2.2.5(3)", label="strrchr"),
                                FV("GLIBC_2.2.5(3)", label="strspn"),
                                FV("GLIBC_2.2.5(3)", label="strtoul"),
                                FV("GLIBC_2.2.5(3)", label="tcgetpgrp"),
                                FV("GLIBC_2.2.5(3)", label="textdomain"),
                                FV("GLIBC_2.2.5(3)", label="timegm"),
                                FV("GLIBC_2.2.5(3)", label="tzset"),
                                FV("GLIBC_2.2.5(3)", label="ungetc"),
                                FV("GLIBC_2.2.5(3)", label="unsetenv"),
                                FV("GLIBC_2.2.5(3)", label="wcstombs"),
                                FV("GLIBC_2.2.5(3)", label="wcswidth"),
                                FV("GLIBC_2.2.5(3)", label="wcwidth"),
                                FV("GLIBC_2.3(2)", label="__ctype_b_loc"),
                                FV("GLIBC_2.3(2)", label="__ctype_tolower_loc"),
                                FV("GLIBC_2.3(2)", label="__ctype_toupper_loc"),
                                FV("GLIBC_2.3(2)", label="getxattr"),
                                FV("GLIBC_2.3.4(4)", label="__fprintf_chk"),
                                FV("GLIBC_2.3.4(4)", label="__memcpy_chk"),
                                FV("GLIBC_2.3.4(4)", label="__printf_chk"),
                                FV("GLIBC_2.3.4(4)", label="__snprintf_chk"),
                                FV("GLIBC_2.3.4(4)", label="__sprintf_chk"),
                                FV("GLIBC_2.4(6)", label="__stack_chk_fail"),
                            ],
                            "elf_import_visibility": [
                                FV("DEFAULT", label="__assert_fail"),
                                FV("DEFAULT", label="__ctype_b_loc"),
                                FV("DEFAULT", label="__ctype_get_mb_cur_max"),
                                FV("DEFAULT", label="__ctype_tolower_loc"),
                                FV("DEFAULT", label="__ctype_toupper_loc"),
                                FV("DEFAULT", label="__cxa_atexit"),
                                FV("DEFAULT", label="__cxa_finalize"),
                                FV("DEFAULT", label="__errno_location"),
                                FV("DEFAULT", label="__fpending"),
                                FV("DEFAULT", label="__fprintf_chk"),
                                FV("DEFAULT", label="__freading"),
                                FV("DEFAULT", label="__fxstat"),
                                FV("DEFAULT", label="__libc_start_main"),
                                FV("DEFAULT", label="__lxstat"),
                                FV("DEFAULT", label="__memcpy_chk"),
                                FV("DEFAULT", label="__overflow"),
                                FV("DEFAULT", label="__printf_chk"),
                                FV("DEFAULT", label="__snprintf_chk"),
                                FV("DEFAULT", label="__sprintf_chk"),
                                FV("DEFAULT", label="__stack_chk_fail"),
                                FV("DEFAULT", label="__strtoul_internal"),
                                FV("DEFAULT", label="__uflow"),
                                FV("DEFAULT", label="__xstat"),
                                FV("DEFAULT", label="_exit"),
                                FV("DEFAULT", label="_setjmp"),
                                FV("DEFAULT", label="abort"),
                                FV("DEFAULT", label="bindtextdomain"),
                                FV("DEFAULT", label="calloc"),
                                FV("DEFAULT", label="clock_gettime"),
                                FV("DEFAULT", label="close"),
                                FV("DEFAULT", label="closedir"),
                                FV("DEFAULT", label="dcgettext"),
                                FV("DEFAULT", label="dirfd"),
                                FV("DEFAULT", label="error"),
                                FV("DEFAULT", label="exit"),
                                FV("DEFAULT", label="fclose"),
                                FV("DEFAULT", label="fdopen"),
                                FV("DEFAULT", label="fflush"),
                                FV("DEFAULT", label="fflush_unlocked"),
                                FV("DEFAULT", label="fgetfilecon"),
                                FV("DEFAULT", label="fileno"),
                                FV("DEFAULT", label="fnmatch"),
                                FV("DEFAULT", label="fputs_unlocked"),
                                FV("DEFAULT", label="free"),
                                FV("DEFAULT", label="freecon"),
                                FV("DEFAULT", label="fscanf"),
                                FV("DEFAULT", label="fseeko"),
                                FV("DEFAULT", label="fwrite"),
                                FV("DEFAULT", label="fwrite_unlocked"),
                                FV("DEFAULT", label="getcwd"),
                                FV("DEFAULT", label="getenv"),
                                FV("DEFAULT", label="getfilecon"),
                                FV("DEFAULT", label="getgrgid"),
                                FV("DEFAULT", label="getgrnam"),
                                FV("DEFAULT", label="gethostname"),
                                FV("DEFAULT", label="getopt_long"),
                                FV("DEFAULT", label="getpwnam"),
                                FV("DEFAULT", label="getpwuid"),
                                FV("DEFAULT", label="gettimeofday"),
                                FV("DEFAULT", label="getxattr"),
                                FV("DEFAULT", label="gmtime_r"),
                                FV("DEFAULT", label="ioctl"),
                                FV("DEFAULT", label="isatty"),
                                FV("DEFAULT", label="iswcntrl"),
                                FV("DEFAULT", label="iswprint"),
                                FV("DEFAULT", label="lgetfilecon"),
                                FV("DEFAULT", label="localeconv"),
                                FV("DEFAULT", label="localtime_r"),
                                FV("DEFAULT", label="lseek"),
                                FV("DEFAULT", label="malloc"),
                                FV("DEFAULT", label="mbrtowc"),
                                FV("DEFAULT", label="mbsinit"),
                                FV("DEFAULT", label="mbstowcs"),
                                FV("DEFAULT", label="memcmp"),
                                FV("DEFAULT", label="memcpy"),
                                FV("DEFAULT", label="memmove"),
                                FV("DEFAULT", label="mempcpy"),
                                FV("DEFAULT", label="memset"),
                                FV("DEFAULT", label="mktime"),
                                FV("DEFAULT", label="nl_langinfo"),
                                FV("DEFAULT", label="open"),
                                FV("DEFAULT", label="opendir"),
                                FV("DEFAULT", label="raise"),
                                FV("DEFAULT", label="readdir"),
                                FV("DEFAULT", label="readlink"),
                                FV("DEFAULT", label="realloc"),
                                FV("DEFAULT", label="setenv"),
                                FV("DEFAULT", label="setlocale"),
                                FV("DEFAULT", label="sigaction"),
                                FV("DEFAULT", label="sigaddset"),
                                FV("DEFAULT", label="sigemptyset"),
                                FV("DEFAULT", label="sigismember"),
                                FV("DEFAULT", label="signal"),
                                FV("DEFAULT", label="sigprocmask"),
                                FV("DEFAULT", label="snprintf"),
                                FV("DEFAULT", label="stpncpy"),
                                FV("DEFAULT", label="strchr"),
                                FV("DEFAULT", label="strcmp"),
                                FV("DEFAULT", label="strcoll"),
                                FV("DEFAULT", label="strcpy"),
                                FV("DEFAULT", label="strftime"),
                                FV("DEFAULT", label="strlen"),
                                FV("DEFAULT", label="strncmp"),
                                FV("DEFAULT", label="strrchr"),
                                FV("DEFAULT", label="strspn"),
                                FV("DEFAULT", label="strtoul"),
                                FV("DEFAULT", label="tcgetpgrp"),
                                FV("DEFAULT", label="textdomain"),
                                FV("DEFAULT", label="timegm"),
                                FV("DEFAULT", label="tzset"),
                                FV("DEFAULT", label="ungetc"),
                                FV("DEFAULT", label="unsetenv"),
                                FV("DEFAULT", label="wcstombs"),
                                FV("DEFAULT", label="wcswidth"),
                                FV("DEFAULT", label="wcwidth"),
                            ],
                            "elf_machine": [FV("Advanced Micro Devices X86-64")],
                            "elf_note": [FV(0), FV(1)],
                            "elf_note_abi": [FV("LINUX", label="0")],
                            "elf_note_description": [
                                FV("00 00 00 00 03 00 00 00 02 00 00 00 00 00 00 00", label="0"),
                                FV("95 67 f9 a2 8e 66 f4 d7 ec 4b af 31 cf bf 68 d0 41 0f 0a e6", label="1"),
                            ],
                            "elf_note_name": [FV("GNU", label="0"), FV("GNU", label="1")],
                            "elf_note_type": [FV("GNU_ABI_TAG", label="0"), FV("GNU_BUILD_ID", label="1")],
                            "elf_note_version": [FV("3.2.0", label="0")],
                            "elf_num_prog_headers": [FV(9)],
                            "elf_num_section_headers": [FV(28)],
                            "elf_obj_version": [FV("0x1")],
                            "elf_os_abi": [FV("UNIX - System V")],
                            "elf_processor_flag": [FV(0)],
                            "elf_program_header_offset": [FV(64)],
                            "elf_program_header_size": [FV(56)],
                            "elf_section": [
                                FV("", offset=0, size=0),
                                FV(".bss", offset=131688, size=4832),
                                FV(".data", offset=131072, size=616),
                                FV(".data.rel.ro", offset=126976, size=2616),
                                FV(".dynamic", offset=129592, size=512),
                                FV(".dynstr", offset=4480, size=1666),
                                FV(".dynsym", offset=904, size=3576),
                                FV(".eh_frame", offset=113192, size=11456),
                                FV(".eh_frame_hdr", offset=111008, size=2180),
                                FV(".fini", offset=90988, size=9),
                                FV(".fini_array", offset=126968, size=8),
                                FV(".gnu.hash", offset=664, size=236),
                                FV(".gnu.version", offset=6146, size=298),
                                FV(".gnu.version_r", offset=6448, size=112),
                                FV(".gnu_debuglink", offset=131688, size=52),
                                FV(".got", offset=130104, size=968),
                                FV(".init", offset=14168, size=23),
                                FV(".init_array", offset=126960, size=8),
                                FV(".interp", offset=568, size=28),
                                FV(".note.ABI-tag", offset=596, size=32),
                                FV(".note.gnu.build-id", offset=628, size=36),
                                FV(".plt", offset=14192, size=1792),
                                FV(".plt.got", offset=15984, size=24),
                                FV(".rela.dyn", offset=6560, size=4944),
                                FV(".rela.plt", offset=11504, size=2664),
                                FV(".rodata", offset=91008, size=19997),
                                FV(".shstrtab", offset=131740, size=257),
                                FV(".text", offset=16016, size=74969),
                            ],
                            "elf_section_alignment": [
                                FV(0, label=""),
                                FV(1, label=".dynstr"),
                                FV(1, label=".interp"),
                                FV(1, label=".shstrtab"),
                                FV(2, label=".gnu.version"),
                                FV(4, label=".eh_frame_hdr"),
                                FV(4, label=".fini"),
                                FV(4, label=".gnu_debuglink"),
                                FV(4, label=".init"),
                                FV(4, label=".note.ABI-tag"),
                                FV(4, label=".note.gnu.build-id"),
                                FV(8, label=".dynamic"),
                                FV(8, label=".dynsym"),
                                FV(8, label=".eh_frame"),
                                FV(8, label=".fini_array"),
                                FV(8, label=".gnu.hash"),
                                FV(8, label=".gnu.version_r"),
                                FV(8, label=".got"),
                                FV(8, label=".init_array"),
                                FV(8, label=".plt.got"),
                                FV(8, label=".rela.dyn"),
                                FV(8, label=".rela.plt"),
                                FV(16, label=".plt"),
                                FV(16, label=".text"),
                                FV(32, label=".bss"),
                                FV(32, label=".data"),
                                FV(32, label=".data.rel.ro"),
                                FV(32, label=".rodata"),
                            ],
                            "elf_section_entropy": [
                                FV(0.0, label=""),
                                FV(0.0, label=".bss"),
                                FV(1.061278124459133, label=".fini_array"),
                                FV(1.061278124459133, label=".init_array"),
                                FV(1.3372769059938467, label=".data"),
                                FV(1.4790257933697941, label=".dynsym"),
                                FV(1.560411603665633, label=".gnu.version"),
                                FV(1.561278124459133, label=".note.ABI-tag"),
                                FV(1.5906934529032921, label=".dynamic"),
                                FV(1.7482165554296587, label=".data.rel.ro"),
                                FV(1.7635166946747725, label=".rela.plt"),
                                FV(1.8304606895718958, label=".got"),
                                FV(2.2881291411027718, label=".rela.dyn"),
                                FV(2.5032583347756456, label=".fini"),
                                FV(2.93223163144275, label=".gnu.version_r"),
                                FV(3.1981203125901447, label=".plt.got"),
                                FV(3.940759832540089, label=".interp"),
                                FV(4.001822825622231, label=".init"),
                                FV(4.247167197306932, label=".note.gnu.build-id"),
                                FV(4.260173314495303, label=".gnu_debuglink"),
                                FV(4.279340466424887, label=".shstrtab"),
                                FV(4.344844971179864, label=".plt"),
                                FV(4.5926770244862665, label=".dynstr"),
                                FV(4.963995032136714, label=".eh_frame"),
                                FV(4.9785514101890245, label=".eh_frame_hdr"),
                                FV(5.373217272274347, label=".rodata"),
                                FV(5.571122656908482, label=".gnu.hash"),
                                FV(6.290053617606062, label=".text"),
                            ],
                            "elf_section_entry_size": [
                                FV(0, label=""),
                                FV(0, label=".bss"),
                                FV(0, label=".data"),
                                FV(0, label=".data.rel.ro"),
                                FV(0, label=".dynstr"),
                                FV(0, label=".eh_frame"),
                                FV(0, label=".eh_frame_hdr"),
                                FV(0, label=".fini"),
                                FV(0, label=".gnu.hash"),
                                FV(0, label=".gnu.version_r"),
                                FV(0, label=".gnu_debuglink"),
                                FV(0, label=".init"),
                                FV(0, label=".interp"),
                                FV(0, label=".note.ABI-tag"),
                                FV(0, label=".note.gnu.build-id"),
                                FV(0, label=".rodata"),
                                FV(0, label=".shstrtab"),
                                FV(0, label=".text"),
                                FV(2, label=".gnu.version"),
                                FV(8, label=".fini_array"),
                                FV(8, label=".got"),
                                FV(8, label=".init_array"),
                                FV(8, label=".plt.got"),
                                FV(16, label=".dynamic"),
                                FV(16, label=".plt"),
                                FV(24, label=".dynsym"),
                                FV(24, label=".rela.dyn"),
                                FV(24, label=".rela.plt"),
                            ],
                            "elf_section_flags": [
                                FV("", label=""),
                                FV("", label=".gnu_debuglink"),
                                FV("", label=".shstrtab"),
                                FV("A", label=".dynstr"),
                                FV("A", label=".dynsym"),
                                FV("A", label=".eh_frame"),
                                FV("A", label=".eh_frame_hdr"),
                                FV("A", label=".gnu.hash"),
                                FV("A", label=".gnu.version"),
                                FV("A", label=".gnu.version_r"),
                                FV("A", label=".interp"),
                                FV("A", label=".note.ABI-tag"),
                                FV("A", label=".note.gnu.build-id"),
                                FV("A", label=".rela.dyn"),
                                FV("A", label=".rodata"),
                                FV("AI", label=".rela.plt"),
                                FV("AX", label=".fini"),
                                FV("AX", label=".init"),
                                FV("AX", label=".plt"),
                                FV("AX", label=".plt.got"),
                                FV("AX", label=".text"),
                                FV("WA", label=".bss"),
                                FV("WA", label=".data"),
                                FV("WA", label=".data.rel.ro"),
                                FV("WA", label=".dynamic"),
                                FV("WA", label=".fini_array"),
                                FV("WA", label=".got"),
                                FV("WA", label=".init_array"),
                            ],
                            "elf_section_hash": [
                                FV("04df3a25922910e50972f7bb02082e7def49833e79d526f8c080d152e26d38c6", label=".data"),
                                FV("11bbd4b0e640d96947142a658aa1b78acaacace6f91a00b026a7286c5dd7a248", label=".got"),
                                FV(
                                    "16055c4e69d59a5135cfc8eeee7cc7be7acd17dd23fa2e3d146abeb17c5d5c24",
                                    label=".gnu.hash",
                                ),
                                FV(
                                    "17c48d3cde602a9f6fe558ffcbd01e1fad1dc8ab53dcfd1d313a5f23778f864f",
                                    label=".fini_array",
                                ),
                                FV("201f51e3b331a568871f063cdf06ca6aad096f443999bd9657d9ef1345d1c144", label=".text"),
                                FV(
                                    "2cc54af57729d1cd55c1012e5cdc9cae92ae51f85aedbb23e84b7779ea961181",
                                    label=".eh_frame_hdr",
                                ),
                                FV(
                                    "2ed177d7de7d6a079e459198ca3ee65b9e8c53e4b40fbf6e153b9eb889c8f15c", label=".rodata"
                                ),
                                FV("335891e8dc1393b953520a03ba2a2848e23cbd0889f63f59c73eb7e4e3976951", label=".init"),
                                FV("66e6f54550612182b4ad78f30b140dd08318b968db3878de2db65fef87dc04d7", label=".fini"),
                                FV(
                                    "6acbbbc874a7d162a6e847eaf54d0e03f9cb479bf275338ddc0721282fe699dc",
                                    label=".note.gnu.build-id",
                                ),
                                FV(
                                    "6e48317ad93a8ac2dc04321465ede06d1274543fc8ab172e68171a9d684bb313",
                                    label=".note.ABI-tag",
                                ),
                                FV(
                                    "6ff73b078d884baf1cdeed8afb17be2d6201a1b47ec76789f6ee1b02042e278d",
                                    label=".init_array",
                                ),
                                FV(
                                    "7dd04160d4cc10814c4ec469fbba1a44e25ac569266fb77c28831cc60173e3d1",
                                    label=".gnu.version",
                                ),
                                FV(
                                    "8cb25b4ca8474a030bd67490db27b2567a8084af548d9708f9b25dcf1b654807",
                                    label=".data.rel.ro",
                                ),
                                FV(
                                    "9097c98ea70f6f3b01d50145eb72bf55ad1f4e9713bccf27bd6405d6254eed00", label=".interp"
                                ),
                                FV(
                                    "949a4acbb02c06a353aac51e27927d8e16841ff92ee990bdbb3ab99674a02830", label=".dynsym"
                                ),
                                FV(
                                    "95ca5ff0448cfb93968af6b9ed7f296530afaea2d99e6b134b880b53164745f2",
                                    label=".dynamic",
                                ),
                                FV(
                                    "9b64e7801fe4869313e82f5d98ddd371cb104cdc73ae3094acbae84fd0627be2",
                                    label=".gnu.version_r",
                                ),
                                FV(
                                    "a7849c05149741df9a82566b72c1dc6aa9b29c09aab9c672ca4b5b2d547d2389", label=".dynstr"
                                ),
                                FV(
                                    "abe7902c3b5acaabe3b247b9084891d8eb6f17e3cfb2d3fb1ed425932a4774e4",
                                    label=".shstrtab",
                                ),
                                FV(
                                    "b1e38bcc9f5d9b952f03c86595d31bf6b60d1064945c50b41a44e08342aab5a1",
                                    label=".plt.got",
                                ),
                                FV(
                                    "b4007df63ee9e2c4979f7e06043a2c232f9afc3ab959636982553ae42c2bf386",
                                    label=".gnu_debuglink",
                                ),
                                FV(
                                    "c661ea9bc54969a047ab9801f5e6a1477518e2b92bcda0bcc24ddc162aef91bf",
                                    label=".eh_frame",
                                ),
                                FV("dab5318bbee24332d25a66b558a068587375047028c2197aa7dbfd996c92fce4", label=".plt"),
                                FV("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", label=""),
                                FV("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", label=".bss"),
                                FV(
                                    "f43514df4586efaaea63b6b3b5bd777cd1ae67020fc851a93b35451b65a2206a",
                                    label=".rela.plt",
                                ),
                                FV(
                                    "fff394f3f3d1043240c64c4ceed1697302139de130fe2a00268468f0f7662086",
                                    label=".rela.dyn",
                                ),
                            ],
                            "elf_section_header_offset": [FV(132000)],
                            "elf_section_header_size": [FV(64)],
                            "elf_section_information": [
                                FV(0, label=""),
                                FV(0, label=".bss"),
                                FV(0, label=".data"),
                                FV(0, label=".data.rel.ro"),
                                FV(0, label=".dynamic"),
                                FV(0, label=".dynstr"),
                                FV(0, label=".eh_frame"),
                                FV(0, label=".eh_frame_hdr"),
                                FV(0, label=".fini"),
                                FV(0, label=".fini_array"),
                                FV(0, label=".gnu.hash"),
                                FV(0, label=".gnu.version"),
                                FV(0, label=".gnu_debuglink"),
                                FV(0, label=".got"),
                                FV(0, label=".init"),
                                FV(0, label=".init_array"),
                                FV(0, label=".interp"),
                                FV(0, label=".note.ABI-tag"),
                                FV(0, label=".note.gnu.build-id"),
                                FV(0, label=".plt"),
                                FV(0, label=".plt.got"),
                                FV(0, label=".rela.dyn"),
                                FV(0, label=".rodata"),
                                FV(0, label=".shstrtab"),
                                FV(0, label=".text"),
                                FV(1, label=".dynsym"),
                                FV(1, label=".gnu.version_r"),
                                FV(23, label=".rela.plt"),
                            ],
                            "elf_section_link": [
                                FV(0, label=""),
                                FV(0, label=".bss"),
                                FV(0, label=".data"),
                                FV(0, label=".data.rel.ro"),
                                FV(0, label=".dynstr"),
                                FV(0, label=".eh_frame"),
                                FV(0, label=".eh_frame_hdr"),
                                FV(0, label=".fini"),
                                FV(0, label=".fini_array"),
                                FV(0, label=".gnu_debuglink"),
                                FV(0, label=".got"),
                                FV(0, label=".init"),
                                FV(0, label=".init_array"),
                                FV(0, label=".interp"),
                                FV(0, label=".note.ABI-tag"),
                                FV(0, label=".note.gnu.build-id"),
                                FV(0, label=".plt"),
                                FV(0, label=".plt.got"),
                                FV(0, label=".rodata"),
                                FV(0, label=".shstrtab"),
                                FV(0, label=".text"),
                                FV(5, label=".gnu.hash"),
                                FV(5, label=".gnu.version"),
                                FV(5, label=".rela.dyn"),
                                FV(5, label=".rela.plt"),
                                FV(6, label=".dynamic"),
                                FV(6, label=".dynsym"),
                                FV(6, label=".gnu.version_r"),
                            ],
                            "elf_section_name_table_idx": [FV(27)],
                            "elf_section_num_flags": [
                                FV(0, label=""),
                                FV(0, label=".gnu_debuglink"),
                                FV(0, label=".shstrtab"),
                                FV(2, label=".dynstr"),
                                FV(2, label=".dynsym"),
                                FV(2, label=".eh_frame"),
                                FV(2, label=".eh_frame_hdr"),
                                FV(2, label=".gnu.hash"),
                                FV(2, label=".gnu.version"),
                                FV(2, label=".gnu.version_r"),
                                FV(2, label=".interp"),
                                FV(2, label=".note.ABI-tag"),
                                FV(2, label=".note.gnu.build-id"),
                                FV(2, label=".rela.dyn"),
                                FV(2, label=".rodata"),
                                FV(3, label=".bss"),
                                FV(3, label=".data"),
                                FV(3, label=".data.rel.ro"),
                                FV(3, label=".dynamic"),
                                FV(3, label=".fini_array"),
                                FV(3, label=".got"),
                                FV(3, label=".init_array"),
                                FV(6, label=".fini"),
                                FV(6, label=".init"),
                                FV(6, label=".plt"),
                                FV(6, label=".plt.got"),
                                FV(6, label=".text"),
                                FV(66, label=".rela.plt"),
                            ],
                            "elf_section_segments": [
                                FV("", label=""),
                                FV("", label=".gnu_debuglink"),
                                FV("", label=".shstrtab"),
                                FV("INTERP - LOAD", label=".interp"),
                                FV("LOAD", label=".bss"),
                                FV("LOAD", label=".data"),
                                FV("LOAD", label=".dynstr"),
                                FV("LOAD", label=".dynsym"),
                                FV("LOAD", label=".eh_frame"),
                                FV("LOAD", label=".fini"),
                                FV("LOAD", label=".gnu.hash"),
                                FV("LOAD", label=".gnu.version"),
                                FV("LOAD", label=".gnu.version_r"),
                                FV("LOAD", label=".init"),
                                FV("LOAD", label=".plt"),
                                FV("LOAD", label=".plt.got"),
                                FV("LOAD", label=".rela.dyn"),
                                FV("LOAD", label=".rela.plt"),
                                FV("LOAD", label=".rodata"),
                                FV("LOAD", label=".text"),
                                FV("LOAD - DYNAMIC - GNU_RELRO", label=".dynamic"),
                                FV("LOAD - GNU_EH_FRAME", label=".eh_frame_hdr"),
                                FV("LOAD - GNU_RELRO", label=".data.rel.ro"),
                                FV("LOAD - GNU_RELRO", label=".fini_array"),
                                FV("LOAD - GNU_RELRO", label=".got"),
                                FV("LOAD - GNU_RELRO", label=".init_array"),
                                FV("LOAD - NOTE", label=".note.ABI-tag"),
                                FV("LOAD - NOTE", label=".note.gnu.build-id"),
                            ],
                            "elf_section_type": [
                                FV("DYNAMIC", label=".dynamic"),
                                FV("DYNSYM", label=".dynsym"),
                                FV("FINI_ARRAY", label=".fini_array"),
                                FV("GNU_HASH", label=".gnu.hash"),
                                FV("INIT_ARRAY", label=".init_array"),
                                FV("NOBITS", label=".bss"),
                                FV("NOTE", label=".note.ABI-tag"),
                                FV("NOTE", label=".note.gnu.build-id"),
                                FV("NULL", label=""),
                                FV("PROGBITS", label=".data"),
                                FV("PROGBITS", label=".data.rel.ro"),
                                FV("PROGBITS", label=".eh_frame"),
                                FV("PROGBITS", label=".eh_frame_hdr"),
                                FV("PROGBITS", label=".fini"),
                                FV("PROGBITS", label=".gnu_debuglink"),
                                FV("PROGBITS", label=".got"),
                                FV("PROGBITS", label=".init"),
                                FV("PROGBITS", label=".interp"),
                                FV("PROGBITS", label=".plt"),
                                FV("PROGBITS", label=".plt.got"),
                                FV("PROGBITS", label=".rodata"),
                                FV("PROGBITS", label=".text"),
                                FV("RELA", label=".rela.dyn"),
                                FV("RELA", label=".rela.plt"),
                                FV("STRTAB", label=".dynstr"),
                                FV("STRTAB", label=".shstrtab"),
                                FV("VERNEED", label=".gnu.version_r"),
                                FV("VERSYM", label=".gnu.version"),
                            ],
                            "elf_section_virtual_address": [
                                FV(0, label=""),
                                FV(0, label=".gnu_debuglink"),
                                FV(0, label=".shstrtab"),
                                FV(568, label=".interp"),
                                FV(596, label=".note.ABI-tag"),
                                FV(628, label=".note.gnu.build-id"),
                                FV(664, label=".gnu.hash"),
                                FV(904, label=".dynsym"),
                                FV(4480, label=".dynstr"),
                                FV(6146, label=".gnu.version"),
                                FV(6448, label=".gnu.version_r"),
                                FV(6560, label=".rela.dyn"),
                                FV(11504, label=".rela.plt"),
                                FV(14168, label=".init"),
                                FV(14192, label=".plt"),
                                FV(15984, label=".plt.got"),
                                FV(16016, label=".text"),
                                FV(90988, label=".fini"),
                                FV(91008, label=".rodata"),
                                FV(111008, label=".eh_frame_hdr"),
                                FV(113192, label=".eh_frame"),
                                FV(2224112, label=".init_array"),
                                FV(2224120, label=".fini_array"),
                                FV(2224128, label=".data.rel.ro"),
                                FV(2226744, label=".dynamic"),
                                FV(2227256, label=".got"),
                                FV(2228224, label=".data"),
                                FV(2228864, label=".bss"),
                            ],
                            "elf_segment": [
                                FV(0, offset=64, size=504),
                                FV(1, offset=568, size=28),
                                FV(2, offset=0, size=124648),
                                FV(3, offset=126960, size=4728),
                                FV(4, offset=129592, size=512),
                                FV(5, offset=596, size=68),
                                FV(6, offset=111008, size=2180),
                                FV(7, offset=0, size=0),
                                FV(8, offset=126960, size=4112),
                            ],
                            "elf_segment_alignment": [
                                FV(1, label="1"),
                                FV(1, label="8"),
                                FV(4, label="5"),
                                FV(4, label="6"),
                                FV(8, label="0"),
                                FV(8, label="4"),
                                FV(16, label="7"),
                                FV(2097152, label="2"),
                                FV(2097152, label="3"),
                            ],
                            "elf_segment_flags": [
                                FV("R--", label="1"),
                                FV("R--", label="5"),
                                FV("R--", label="6"),
                                FV("R--", label="8"),
                                FV("R-X", label="0"),
                                FV("R-X", label="2"),
                                FV("RW-", label="3"),
                                FV("RW-", label="4"),
                                FV("RW-", label="7"),
                            ],
                            "elf_segment_physical_address": [
                                FV(0, label="2"),
                                FV(0, label="7"),
                                FV(64, label="0"),
                                FV(568, label="1"),
                                FV(596, label="5"),
                                FV(111008, label="6"),
                                FV(2224112, label="3"),
                                FV(2224112, label="8"),
                                FV(2226744, label="4"),
                            ],
                            "elf_segment_sections": [
                                FV("", label="0"),
                                FV("", label="7"),
                                FV(".dynamic", label="4"),
                                FV(".eh_frame_hdr", label="6"),
                                FV(".init_array, .fini_array, .data.rel.ro, .dynamic, .got", label="8"),
                                FV(".init_array, .fini_array, .data.rel.ro, .dynamic, .got, .data, .bss", label="3"),
                                FV(".interp", label="1"),
                                FV(
                                    ".interp, .note.ABI-tag, .note.gnu.build-id, .gnu.hash, .dynsym, .dynstr, .gnu.version, .gnu.version_r, .rela.dyn, .rela.plt, .init, .plt, .plt.got, .text, .fini, .rodata, .eh_frame_hdr, .eh_frame",
                                    label="2",
                                ),
                                FV(".note.ABI-tag, .note.gnu.build-id", label="5"),
                            ],
                            "elf_segment_type": [
                                FV("DYNAMIC", label="4"),
                                FV("GNU_EH_FRAME", label="6"),
                                FV("GNU_RELRO", label="8"),
                                FV("GNU_STACK", label="7"),
                                FV("INTERP", label="1"),
                                FV("LOAD", label="2"),
                                FV("LOAD", label="3"),
                                FV("NOTE", label="5"),
                                FV("PHDR", label="0"),
                            ],
                            "elf_segment_virtual_address": [
                                FV(0, label="2"),
                                FV(0, label="7"),
                                FV(64, label="0"),
                                FV(568, label="1"),
                                FV(596, label="5"),
                                FV(111008, label="6"),
                                FV(2224112, label="3"),
                                FV(2224112, label="8"),
                                FV(2226744, label="4"),
                            ],
                            "elf_segment_virtual_size": [
                                FV(0, label="7"),
                                FV(28, label="1"),
                                FV(68, label="5"),
                                FV(504, label="0"),
                                FV(512, label="4"),
                                FV(2180, label="6"),
                                FV(4112, label="8"),
                                FV(9584, label="3"),
                                FV(124648, label="2"),
                            ],
                            "elf_type": [FV("DYN (Shared object file)")],
                        },
                    )
                ],
            ),
        )
