"""
LIEF ELF functional test suite.

Functionally test an Android ELF (Sentry) for AArch64.

"""

from azul_runner import FV, DataLabel, Event, JobResult, State, test_template

from azul_plugin_lief.lief_elf import LiefELF


class TestExecute(test_template.TestPlugin):
    """Parent class of all Lief ELF tests."""

    PLUGIN_TO_TEST = LiefELF

    def test_lief_elf_android_aarch64(self):
        """Tests on a NDK C++ ELF for AArch64."""
        result = self.do_execution(
            data_in=[
                (
                    DataLabel.CONTENT,
                    self.load_test_file_bytes(
                        "3c88cc5407f10f270bbe802cfaf7effc32a6c75445f93431612a8ed32c06270f",
                        "Benign libsentry-android.so ELF64.",
                    ),
                )
            ]
        )

        self.assertJobResult(
            result,
            JobResult(
                state=State(State.Label.COMPLETED),
                events=[
                    Event(
                        entity_type="binary",
                        entity_id="3c88cc5407f10f270bbe802cfaf7effc32a6c75445f93431612a8ed32c06270f",
                        features={
                            "elf_abi_version": [FV(0)],
                            "elf_class": [FV("ELF64")],
                            "elf_data": [FV("2's complement, little endian")],
                            "elf_entrypoint": [FV(7404)],
                            "elf_export": [
                                FV("Java_io_sentry_android_ndk_NativeModuleListLoader_nativeClearModuleList"),
                                FV("Java_io_sentry_android_ndk_NativeModuleListLoader_nativeLoadModuleList"),
                                FV("Java_io_sentry_android_ndk_NativeScope_nativeAddBreadcrumb"),
                                FV("Java_io_sentry_android_ndk_NativeScope_nativeRemoveExtra"),
                                FV("Java_io_sentry_android_ndk_NativeScope_nativeRemoveTag"),
                                FV("Java_io_sentry_android_ndk_NativeScope_nativeRemoveUser"),
                                FV("Java_io_sentry_android_ndk_NativeScope_nativeSetExtra"),
                                FV("Java_io_sentry_android_ndk_NativeScope_nativeSetTag"),
                                FV("Java_io_sentry_android_ndk_NativeScope_nativeSetUser"),
                                FV("Java_io_sentry_android_ndk_SentryNdk_initSentryNative"),
                                FV("Java_io_sentry_android_ndk_SentryNdk_shutdown"),
                            ],
                            "elf_export_binding": [
                                FV(
                                    "GLOBAL",
                                    label="Java_io_sentry_android_ndk_NativeModuleListLoader_nativeClearModuleList",
                                ),
                                FV(
                                    "GLOBAL",
                                    label="Java_io_sentry_android_ndk_NativeModuleListLoader_nativeLoadModuleList",
                                ),
                                FV("GLOBAL", label="Java_io_sentry_android_ndk_NativeScope_nativeAddBreadcrumb"),
                                FV("GLOBAL", label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveExtra"),
                                FV("GLOBAL", label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveTag"),
                                FV("GLOBAL", label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveUser"),
                                FV("GLOBAL", label="Java_io_sentry_android_ndk_NativeScope_nativeSetExtra"),
                                FV("GLOBAL", label="Java_io_sentry_android_ndk_NativeScope_nativeSetTag"),
                                FV("GLOBAL", label="Java_io_sentry_android_ndk_NativeScope_nativeSetUser"),
                                FV("GLOBAL", label="Java_io_sentry_android_ndk_SentryNdk_initSentryNative"),
                                FV("GLOBAL", label="Java_io_sentry_android_ndk_SentryNdk_shutdown"),
                            ],
                            "elf_export_size": [
                                FV(4, label="Java_io_sentry_android_ndk_NativeModuleListLoader_nativeClearModuleList"),
                                FV(4, label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveUser"),
                                FV(4, label="Java_io_sentry_android_ndk_SentryNdk_shutdown"),
                                FV(88, label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveExtra"),
                                FV(88, label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveTag"),
                                FV(160, label="Java_io_sentry_android_ndk_NativeScope_nativeSetTag"),
                                FV(164, label="Java_io_sentry_android_ndk_NativeScope_nativeSetExtra"),
                                FV(400, label="Java_io_sentry_android_ndk_NativeScope_nativeSetUser"),
                                FV(636, label="Java_io_sentry_android_ndk_NativeScope_nativeAddBreadcrumb"),
                                FV(884, label="Java_io_sentry_android_ndk_SentryNdk_initSentryNative"),
                                FV(
                                    1328,
                                    label="Java_io_sentry_android_ndk_NativeModuleListLoader_nativeLoadModuleList",
                                ),
                            ],
                            "elf_export_type": [
                                FV(
                                    "FUNC",
                                    label="Java_io_sentry_android_ndk_NativeModuleListLoader_nativeClearModuleList",
                                ),
                                FV(
                                    "FUNC",
                                    label="Java_io_sentry_android_ndk_NativeModuleListLoader_nativeLoadModuleList",
                                ),
                                FV("FUNC", label="Java_io_sentry_android_ndk_NativeScope_nativeAddBreadcrumb"),
                                FV("FUNC", label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveExtra"),
                                FV("FUNC", label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveTag"),
                                FV("FUNC", label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveUser"),
                                FV("FUNC", label="Java_io_sentry_android_ndk_NativeScope_nativeSetExtra"),
                                FV("FUNC", label="Java_io_sentry_android_ndk_NativeScope_nativeSetTag"),
                                FV("FUNC", label="Java_io_sentry_android_ndk_NativeScope_nativeSetUser"),
                                FV("FUNC", label="Java_io_sentry_android_ndk_SentryNdk_initSentryNative"),
                                FV("FUNC", label="Java_io_sentry_android_ndk_SentryNdk_shutdown"),
                            ],
                            "elf_export_value": [
                                FV(7488, label="Java_io_sentry_android_ndk_NativeScope_nativeSetTag"),
                                FV(7648, label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveTag"),
                                FV(7736, label="Java_io_sentry_android_ndk_NativeScope_nativeSetExtra"),
                                FV(7900, label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveExtra"),
                                FV(7988, label="Java_io_sentry_android_ndk_NativeScope_nativeSetUser"),
                                FV(8388, label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveUser"),
                                FV(8392, label="Java_io_sentry_android_ndk_NativeScope_nativeAddBreadcrumb"),
                                FV(9028, label="Java_io_sentry_android_ndk_SentryNdk_initSentryNative"),
                                FV(
                                    10392,
                                    label="Java_io_sentry_android_ndk_NativeModuleListLoader_nativeClearModuleList",
                                ),
                                FV(
                                    10396,
                                    label="Java_io_sentry_android_ndk_NativeModuleListLoader_nativeLoadModuleList",
                                ),
                                FV(11724, label="Java_io_sentry_android_ndk_SentryNdk_shutdown"),
                            ],
                            "elf_export_version": [
                                FV(
                                    "* Global *",
                                    label="Java_io_sentry_android_ndk_NativeModuleListLoader_nativeClearModuleList",
                                ),
                                FV(
                                    "* Global *",
                                    label="Java_io_sentry_android_ndk_NativeModuleListLoader_nativeLoadModuleList",
                                ),
                                FV("* Global *", label="Java_io_sentry_android_ndk_NativeScope_nativeAddBreadcrumb"),
                                FV("* Global *", label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveExtra"),
                                FV("* Global *", label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveTag"),
                                FV("* Global *", label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveUser"),
                                FV("* Global *", label="Java_io_sentry_android_ndk_NativeScope_nativeSetExtra"),
                                FV("* Global *", label="Java_io_sentry_android_ndk_NativeScope_nativeSetTag"),
                                FV("* Global *", label="Java_io_sentry_android_ndk_NativeScope_nativeSetUser"),
                                FV("* Global *", label="Java_io_sentry_android_ndk_SentryNdk_initSentryNative"),
                                FV("* Global *", label="Java_io_sentry_android_ndk_SentryNdk_shutdown"),
                            ],
                            "elf_export_visibility": [
                                FV(
                                    "DEFAULT",
                                    label="Java_io_sentry_android_ndk_NativeModuleListLoader_nativeClearModuleList",
                                ),
                                FV(
                                    "DEFAULT",
                                    label="Java_io_sentry_android_ndk_NativeModuleListLoader_nativeLoadModuleList",
                                ),
                                FV("DEFAULT", label="Java_io_sentry_android_ndk_NativeScope_nativeAddBreadcrumb"),
                                FV("DEFAULT", label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveExtra"),
                                FV("DEFAULT", label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveTag"),
                                FV("DEFAULT", label="Java_io_sentry_android_ndk_NativeScope_nativeRemoveUser"),
                                FV("DEFAULT", label="Java_io_sentry_android_ndk_NativeScope_nativeSetExtra"),
                                FV("DEFAULT", label="Java_io_sentry_android_ndk_NativeScope_nativeSetTag"),
                                FV("DEFAULT", label="Java_io_sentry_android_ndk_NativeScope_nativeSetUser"),
                                FV("DEFAULT", label="Java_io_sentry_android_ndk_SentryNdk_initSentryNative"),
                                FV("DEFAULT", label="Java_io_sentry_android_ndk_SentryNdk_shutdown"),
                            ],
                            "elf_hdr_version": [FV("1 (current)")],
                            "elf_header_size": [FV(64)],
                            "elf_import": [
                                FV("__cxa_atexit"),
                                FV("__cxa_finalize"),
                                FV("__stack_chk_fail"),
                                FV("__strncpy_chk2"),
                                FV("__vsnprintf_chk"),
                                FV("sentry_add_breadcrumb"),
                                FV("sentry_clear_modulecache"),
                                FV("sentry_close"),
                                FV("sentry_envelope_free"),
                                FV("sentry_envelope_write_to_file"),
                                FV("sentry_free"),
                                FV("sentry_get_modules_list"),
                                FV("sentry_init"),
                                FV("sentry_malloc"),
                                FV("sentry_options_free"),
                                FV("sentry_options_new"),
                                FV("sentry_options_set_auto_session_tracking"),
                                FV("sentry_options_set_database_path"),
                                FV("sentry_options_set_debug"),
                                FV("sentry_options_set_dist"),
                                FV("sentry_options_set_dsn"),
                                FV("sentry_options_set_environment"),
                                FV("sentry_options_set_max_breadcrumbs"),
                                FV("sentry_options_set_release"),
                                FV("sentry_options_set_transport"),
                                FV("sentry_remove_extra"),
                                FV("sentry_remove_tag"),
                                FV("sentry_remove_user"),
                                FV("sentry_set_extra"),
                                FV("sentry_set_tag"),
                                FV("sentry_set_user"),
                                FV("sentry_transport_free"),
                                FV("sentry_transport_new"),
                                FV("sentry_transport_set_free_func"),
                                FV("sentry_transport_set_state"),
                                FV("sentry_uuid_as_string"),
                                FV("sentry_uuid_new_v4"),
                                FV("sentry_value_as_int32"),
                                FV("sentry_value_as_string"),
                                FV("sentry_value_decref"),
                                FV("sentry_value_get_by_index"),
                                FV("sentry_value_get_by_key"),
                                FV("sentry_value_get_length"),
                                FV("sentry_value_get_type"),
                                FV("sentry_value_is_null"),
                                FV("sentry_value_new_breadcrumb"),
                                FV("sentry_value_new_object"),
                                FV("sentry_value_new_string"),
                                FV("sentry_value_set_by_key"),
                                FV("strlen"),
                                FV("strncpy"),
                                FV("strrchr"),
                            ],
                            "elf_import_binding": [
                                FV("GLOBAL", label="__cxa_atexit"),
                                FV("GLOBAL", label="__cxa_finalize"),
                                FV("GLOBAL", label="__stack_chk_fail"),
                                FV("GLOBAL", label="__strncpy_chk2"),
                                FV("GLOBAL", label="__vsnprintf_chk"),
                                FV("GLOBAL", label="sentry_add_breadcrumb"),
                                FV("GLOBAL", label="sentry_clear_modulecache"),
                                FV("GLOBAL", label="sentry_close"),
                                FV("GLOBAL", label="sentry_envelope_free"),
                                FV("GLOBAL", label="sentry_envelope_write_to_file"),
                                FV("GLOBAL", label="sentry_free"),
                                FV("GLOBAL", label="sentry_get_modules_list"),
                                FV("GLOBAL", label="sentry_init"),
                                FV("GLOBAL", label="sentry_malloc"),
                                FV("GLOBAL", label="sentry_options_free"),
                                FV("GLOBAL", label="sentry_options_new"),
                                FV("GLOBAL", label="sentry_options_set_auto_session_tracking"),
                                FV("GLOBAL", label="sentry_options_set_database_path"),
                                FV("GLOBAL", label="sentry_options_set_debug"),
                                FV("GLOBAL", label="sentry_options_set_dist"),
                                FV("GLOBAL", label="sentry_options_set_dsn"),
                                FV("GLOBAL", label="sentry_options_set_environment"),
                                FV("GLOBAL", label="sentry_options_set_max_breadcrumbs"),
                                FV("GLOBAL", label="sentry_options_set_release"),
                                FV("GLOBAL", label="sentry_options_set_transport"),
                                FV("GLOBAL", label="sentry_remove_extra"),
                                FV("GLOBAL", label="sentry_remove_tag"),
                                FV("GLOBAL", label="sentry_remove_user"),
                                FV("GLOBAL", label="sentry_set_extra"),
                                FV("GLOBAL", label="sentry_set_tag"),
                                FV("GLOBAL", label="sentry_set_user"),
                                FV("GLOBAL", label="sentry_transport_free"),
                                FV("GLOBAL", label="sentry_transport_new"),
                                FV("GLOBAL", label="sentry_transport_set_free_func"),
                                FV("GLOBAL", label="sentry_transport_set_state"),
                                FV("GLOBAL", label="sentry_uuid_as_string"),
                                FV("GLOBAL", label="sentry_uuid_new_v4"),
                                FV("GLOBAL", label="sentry_value_as_int32"),
                                FV("GLOBAL", label="sentry_value_as_string"),
                                FV("GLOBAL", label="sentry_value_decref"),
                                FV("GLOBAL", label="sentry_value_get_by_index"),
                                FV("GLOBAL", label="sentry_value_get_by_key"),
                                FV("GLOBAL", label="sentry_value_get_length"),
                                FV("GLOBAL", label="sentry_value_get_type"),
                                FV("GLOBAL", label="sentry_value_is_null"),
                                FV("GLOBAL", label="sentry_value_new_breadcrumb"),
                                FV("GLOBAL", label="sentry_value_new_object"),
                                FV("GLOBAL", label="sentry_value_new_string"),
                                FV("GLOBAL", label="sentry_value_set_by_key"),
                                FV("GLOBAL", label="strlen"),
                                FV("GLOBAL", label="strncpy"),
                                FV("GLOBAL", label="strrchr"),
                            ],
                            "elf_import_size": [
                                FV(0, label="__cxa_atexit"),
                                FV(0, label="__cxa_finalize"),
                                FV(0, label="__stack_chk_fail"),
                                FV(0, label="__strncpy_chk2"),
                                FV(0, label="__vsnprintf_chk"),
                                FV(0, label="sentry_add_breadcrumb"),
                                FV(0, label="sentry_clear_modulecache"),
                                FV(0, label="sentry_close"),
                                FV(0, label="sentry_envelope_free"),
                                FV(0, label="sentry_envelope_write_to_file"),
                                FV(0, label="sentry_free"),
                                FV(0, label="sentry_get_modules_list"),
                                FV(0, label="sentry_init"),
                                FV(0, label="sentry_malloc"),
                                FV(0, label="sentry_options_free"),
                                FV(0, label="sentry_options_new"),
                                FV(0, label="sentry_options_set_auto_session_tracking"),
                                FV(0, label="sentry_options_set_database_path"),
                                FV(0, label="sentry_options_set_debug"),
                                FV(0, label="sentry_options_set_dist"),
                                FV(0, label="sentry_options_set_dsn"),
                                FV(0, label="sentry_options_set_environment"),
                                FV(0, label="sentry_options_set_max_breadcrumbs"),
                                FV(0, label="sentry_options_set_release"),
                                FV(0, label="sentry_options_set_transport"),
                                FV(0, label="sentry_remove_extra"),
                                FV(0, label="sentry_remove_tag"),
                                FV(0, label="sentry_remove_user"),
                                FV(0, label="sentry_set_extra"),
                                FV(0, label="sentry_set_tag"),
                                FV(0, label="sentry_set_user"),
                                FV(0, label="sentry_transport_free"),
                                FV(0, label="sentry_transport_new"),
                                FV(0, label="sentry_transport_set_free_func"),
                                FV(0, label="sentry_transport_set_state"),
                                FV(0, label="sentry_uuid_as_string"),
                                FV(0, label="sentry_uuid_new_v4"),
                                FV(0, label="sentry_value_as_int32"),
                                FV(0, label="sentry_value_as_string"),
                                FV(0, label="sentry_value_decref"),
                                FV(0, label="sentry_value_get_by_index"),
                                FV(0, label="sentry_value_get_by_key"),
                                FV(0, label="sentry_value_get_length"),
                                FV(0, label="sentry_value_get_type"),
                                FV(0, label="sentry_value_is_null"),
                                FV(0, label="sentry_value_new_breadcrumb"),
                                FV(0, label="sentry_value_new_object"),
                                FV(0, label="sentry_value_new_string"),
                                FV(0, label="sentry_value_set_by_key"),
                                FV(0, label="strlen"),
                                FV(0, label="strncpy"),
                                FV(0, label="strrchr"),
                            ],
                            "elf_import_type": [
                                FV("FUNC", label="__cxa_atexit"),
                                FV("FUNC", label="__cxa_finalize"),
                                FV("FUNC", label="__stack_chk_fail"),
                                FV("FUNC", label="__strncpy_chk2"),
                                FV("FUNC", label="__vsnprintf_chk"),
                                FV("FUNC", label="sentry_add_breadcrumb"),
                                FV("FUNC", label="sentry_clear_modulecache"),
                                FV("FUNC", label="sentry_close"),
                                FV("FUNC", label="sentry_envelope_free"),
                                FV("FUNC", label="sentry_envelope_write_to_file"),
                                FV("FUNC", label="sentry_free"),
                                FV("FUNC", label="sentry_get_modules_list"),
                                FV("FUNC", label="sentry_init"),
                                FV("FUNC", label="sentry_malloc"),
                                FV("FUNC", label="sentry_options_free"),
                                FV("FUNC", label="sentry_options_new"),
                                FV("FUNC", label="sentry_options_set_auto_session_tracking"),
                                FV("FUNC", label="sentry_options_set_database_path"),
                                FV("FUNC", label="sentry_options_set_debug"),
                                FV("FUNC", label="sentry_options_set_dist"),
                                FV("FUNC", label="sentry_options_set_dsn"),
                                FV("FUNC", label="sentry_options_set_environment"),
                                FV("FUNC", label="sentry_options_set_max_breadcrumbs"),
                                FV("FUNC", label="sentry_options_set_release"),
                                FV("FUNC", label="sentry_options_set_transport"),
                                FV("FUNC", label="sentry_remove_extra"),
                                FV("FUNC", label="sentry_remove_tag"),
                                FV("FUNC", label="sentry_remove_user"),
                                FV("FUNC", label="sentry_set_extra"),
                                FV("FUNC", label="sentry_set_tag"),
                                FV("FUNC", label="sentry_set_user"),
                                FV("FUNC", label="sentry_transport_free"),
                                FV("FUNC", label="sentry_transport_new"),
                                FV("FUNC", label="sentry_transport_set_free_func"),
                                FV("FUNC", label="sentry_transport_set_state"),
                                FV("FUNC", label="sentry_uuid_as_string"),
                                FV("FUNC", label="sentry_uuid_new_v4"),
                                FV("FUNC", label="sentry_value_as_int32"),
                                FV("FUNC", label="sentry_value_as_string"),
                                FV("FUNC", label="sentry_value_decref"),
                                FV("FUNC", label="sentry_value_get_by_index"),
                                FV("FUNC", label="sentry_value_get_by_key"),
                                FV("FUNC", label="sentry_value_get_length"),
                                FV("FUNC", label="sentry_value_get_type"),
                                FV("FUNC", label="sentry_value_is_null"),
                                FV("FUNC", label="sentry_value_new_breadcrumb"),
                                FV("FUNC", label="sentry_value_new_object"),
                                FV("FUNC", label="sentry_value_new_string"),
                                FV("FUNC", label="sentry_value_set_by_key"),
                                FV("FUNC", label="strlen"),
                                FV("FUNC", label="strncpy"),
                                FV("FUNC", label="strrchr"),
                            ],
                            "elf_import_value": [
                                FV(0, label="__cxa_atexit"),
                                FV(0, label="__cxa_finalize"),
                                FV(0, label="__stack_chk_fail"),
                                FV(0, label="__strncpy_chk2"),
                                FV(0, label="__vsnprintf_chk"),
                                FV(0, label="sentry_add_breadcrumb"),
                                FV(0, label="sentry_clear_modulecache"),
                                FV(0, label="sentry_close"),
                                FV(0, label="sentry_envelope_free"),
                                FV(0, label="sentry_envelope_write_to_file"),
                                FV(0, label="sentry_free"),
                                FV(0, label="sentry_get_modules_list"),
                                FV(0, label="sentry_init"),
                                FV(0, label="sentry_malloc"),
                                FV(0, label="sentry_options_free"),
                                FV(0, label="sentry_options_new"),
                                FV(0, label="sentry_options_set_auto_session_tracking"),
                                FV(0, label="sentry_options_set_database_path"),
                                FV(0, label="sentry_options_set_debug"),
                                FV(0, label="sentry_options_set_dist"),
                                FV(0, label="sentry_options_set_dsn"),
                                FV(0, label="sentry_options_set_environment"),
                                FV(0, label="sentry_options_set_max_breadcrumbs"),
                                FV(0, label="sentry_options_set_release"),
                                FV(0, label="sentry_options_set_transport"),
                                FV(0, label="sentry_remove_extra"),
                                FV(0, label="sentry_remove_tag"),
                                FV(0, label="sentry_remove_user"),
                                FV(0, label="sentry_set_extra"),
                                FV(0, label="sentry_set_tag"),
                                FV(0, label="sentry_set_user"),
                                FV(0, label="sentry_transport_free"),
                                FV(0, label="sentry_transport_new"),
                                FV(0, label="sentry_transport_set_free_func"),
                                FV(0, label="sentry_transport_set_state"),
                                FV(0, label="sentry_uuid_as_string"),
                                FV(0, label="sentry_uuid_new_v4"),
                                FV(0, label="sentry_value_as_int32"),
                                FV(0, label="sentry_value_as_string"),
                                FV(0, label="sentry_value_decref"),
                                FV(0, label="sentry_value_get_by_index"),
                                FV(0, label="sentry_value_get_by_key"),
                                FV(0, label="sentry_value_get_length"),
                                FV(0, label="sentry_value_get_type"),
                                FV(0, label="sentry_value_is_null"),
                                FV(0, label="sentry_value_new_breadcrumb"),
                                FV(0, label="sentry_value_new_object"),
                                FV(0, label="sentry_value_new_string"),
                                FV(0, label="sentry_value_set_by_key"),
                                FV(0, label="strlen"),
                                FV(0, label="strncpy"),
                                FV(0, label="strrchr"),
                            ],
                            "elf_import_version": [
                                FV("* Global *", label="sentry_add_breadcrumb"),
                                FV("* Global *", label="sentry_clear_modulecache"),
                                FV("* Global *", label="sentry_close"),
                                FV("* Global *", label="sentry_envelope_free"),
                                FV("* Global *", label="sentry_envelope_write_to_file"),
                                FV("* Global *", label="sentry_free"),
                                FV("* Global *", label="sentry_get_modules_list"),
                                FV("* Global *", label="sentry_init"),
                                FV("* Global *", label="sentry_malloc"),
                                FV("* Global *", label="sentry_options_free"),
                                FV("* Global *", label="sentry_options_new"),
                                FV("* Global *", label="sentry_options_set_auto_session_tracking"),
                                FV("* Global *", label="sentry_options_set_database_path"),
                                FV("* Global *", label="sentry_options_set_debug"),
                                FV("* Global *", label="sentry_options_set_dist"),
                                FV("* Global *", label="sentry_options_set_dsn"),
                                FV("* Global *", label="sentry_options_set_environment"),
                                FV("* Global *", label="sentry_options_set_max_breadcrumbs"),
                                FV("* Global *", label="sentry_options_set_release"),
                                FV("* Global *", label="sentry_options_set_transport"),
                                FV("* Global *", label="sentry_remove_extra"),
                                FV("* Global *", label="sentry_remove_tag"),
                                FV("* Global *", label="sentry_remove_user"),
                                FV("* Global *", label="sentry_set_extra"),
                                FV("* Global *", label="sentry_set_tag"),
                                FV("* Global *", label="sentry_set_user"),
                                FV("* Global *", label="sentry_transport_free"),
                                FV("* Global *", label="sentry_transport_new"),
                                FV("* Global *", label="sentry_transport_set_free_func"),
                                FV("* Global *", label="sentry_transport_set_state"),
                                FV("* Global *", label="sentry_uuid_as_string"),
                                FV("* Global *", label="sentry_uuid_new_v4"),
                                FV("* Global *", label="sentry_value_as_int32"),
                                FV("* Global *", label="sentry_value_as_string"),
                                FV("* Global *", label="sentry_value_decref"),
                                FV("* Global *", label="sentry_value_get_by_index"),
                                FV("* Global *", label="sentry_value_get_by_key"),
                                FV("* Global *", label="sentry_value_get_length"),
                                FV("* Global *", label="sentry_value_get_type"),
                                FV("* Global *", label="sentry_value_is_null"),
                                FV("* Global *", label="sentry_value_new_breadcrumb"),
                                FV("* Global *", label="sentry_value_new_object"),
                                FV("* Global *", label="sentry_value_new_string"),
                                FV("* Global *", label="sentry_value_set_by_key"),
                                FV("LIBC(2)", label="__cxa_atexit"),
                                FV("LIBC(2)", label="__cxa_finalize"),
                                FV("LIBC(2)", label="__stack_chk_fail"),
                                FV("LIBC(2)", label="__strncpy_chk2"),
                                FV("LIBC(2)", label="__vsnprintf_chk"),
                                FV("LIBC(2)", label="strlen"),
                                FV("LIBC(2)", label="strncpy"),
                                FV("LIBC(2)", label="strrchr"),
                            ],
                            "elf_import_visibility": [
                                FV("DEFAULT", label="__cxa_atexit"),
                                FV("DEFAULT", label="__cxa_finalize"),
                                FV("DEFAULT", label="__stack_chk_fail"),
                                FV("DEFAULT", label="__strncpy_chk2"),
                                FV("DEFAULT", label="__vsnprintf_chk"),
                                FV("DEFAULT", label="sentry_add_breadcrumb"),
                                FV("DEFAULT", label="sentry_clear_modulecache"),
                                FV("DEFAULT", label="sentry_close"),
                                FV("DEFAULT", label="sentry_envelope_free"),
                                FV("DEFAULT", label="sentry_envelope_write_to_file"),
                                FV("DEFAULT", label="sentry_free"),
                                FV("DEFAULT", label="sentry_get_modules_list"),
                                FV("DEFAULT", label="sentry_init"),
                                FV("DEFAULT", label="sentry_malloc"),
                                FV("DEFAULT", label="sentry_options_free"),
                                FV("DEFAULT", label="sentry_options_new"),
                                FV("DEFAULT", label="sentry_options_set_auto_session_tracking"),
                                FV("DEFAULT", label="sentry_options_set_database_path"),
                                FV("DEFAULT", label="sentry_options_set_debug"),
                                FV("DEFAULT", label="sentry_options_set_dist"),
                                FV("DEFAULT", label="sentry_options_set_dsn"),
                                FV("DEFAULT", label="sentry_options_set_environment"),
                                FV("DEFAULT", label="sentry_options_set_max_breadcrumbs"),
                                FV("DEFAULT", label="sentry_options_set_release"),
                                FV("DEFAULT", label="sentry_options_set_transport"),
                                FV("DEFAULT", label="sentry_remove_extra"),
                                FV("DEFAULT", label="sentry_remove_tag"),
                                FV("DEFAULT", label="sentry_remove_user"),
                                FV("DEFAULT", label="sentry_set_extra"),
                                FV("DEFAULT", label="sentry_set_tag"),
                                FV("DEFAULT", label="sentry_set_user"),
                                FV("DEFAULT", label="sentry_transport_free"),
                                FV("DEFAULT", label="sentry_transport_new"),
                                FV("DEFAULT", label="sentry_transport_set_free_func"),
                                FV("DEFAULT", label="sentry_transport_set_state"),
                                FV("DEFAULT", label="sentry_uuid_as_string"),
                                FV("DEFAULT", label="sentry_uuid_new_v4"),
                                FV("DEFAULT", label="sentry_value_as_int32"),
                                FV("DEFAULT", label="sentry_value_as_string"),
                                FV("DEFAULT", label="sentry_value_decref"),
                                FV("DEFAULT", label="sentry_value_get_by_index"),
                                FV("DEFAULT", label="sentry_value_get_by_key"),
                                FV("DEFAULT", label="sentry_value_get_length"),
                                FV("DEFAULT", label="sentry_value_get_type"),
                                FV("DEFAULT", label="sentry_value_is_null"),
                                FV("DEFAULT", label="sentry_value_new_breadcrumb"),
                                FV("DEFAULT", label="sentry_value_new_object"),
                                FV("DEFAULT", label="sentry_value_new_string"),
                                FV("DEFAULT", label="sentry_value_set_by_key"),
                                FV("DEFAULT", label="strlen"),
                                FV("DEFAULT", label="strncpy"),
                                FV("DEFAULT", label="strrchr"),
                            ],
                            "elf_machine": [FV("AArch64")],
                            "elf_note": [FV(0), FV(1)],
                            "elf_note_description": [
                                FV(
                                    "15 00 00 00 72 32 33 62 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 37 37 37 39 36 32 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00",
                                    label="0",
                                ),
                                FV("f0 84 6e 1f 81 55 2d d3 3e d8 86 fd 15 1a 9f b0 f9 39 01 85", label="1"),
                            ],
                            "elf_note_name": [FV("Android", label="0"), FV("GNU", label="1")],
                            "elf_note_ndk_build_number": [FV("7779620", label="0")],
                            "elf_note_ndk_version": [FV("r23b", label="0")],
                            "elf_note_sdk_version": [FV("21", label="0")],
                            "elf_note_type": [FV("ANDROID_IDENT", label="0"), FV("GNU_BUILD_ID", label="1")],
                            "elf_num_prog_headers": [FV(8)],
                            "elf_num_section_headers": [FV(23)],
                            "elf_obj_version": [FV("0x1")],
                            "elf_os_abi": [FV("UNIX - System V")],
                            "elf_processor_flag": [FV(0)],
                            "elf_program_header_offset": [FV(64)],
                            "elf_program_header_size": [FV(56)],
                            "elf_section": [
                                FV("", offset=0, size=0),
                                FV(".comment", offset=13672, size=277),
                                FV(".data.rel.ro", offset=12768, size=8),
                                FV(".dynamic", offset=12792, size=432),
                                FV(".dynstr", offset=3020, size=1802),
                                FV(".dynsym", offset=704, size=1536),
                                FV(".eh_frame", offset=6736, size=668),
                                FV(".eh_frame_hdr", offset=6572, size=164),
                                FV(".fini_array", offset=12776, size=16),
                                FV(".gnu.hash", offset=2400, size=100),
                                FV(".gnu.version", offset=2240, size=128),
                                FV(".gnu.version_r", offset=2368, size=32),
                                FV(".got", offset=13224, size=8),
                                FV(".got.plt", offset=13232, size=440),
                                FV(".hash", offset=2500, size=520),
                                FV(".note.android.ident", offset=512, size=152),
                                FV(".note.gnu.build-id", offset=664, size=36),
                                FV(".plt", offset=11904, size=864),
                                FV(".rela.dyn", offset=4824, size=96),
                                FV(".rela.plt", offset=4920, size=1248),
                                FV(".rodata", offset=6168, size=403),
                                FV(".shstrtab", offset=13949, size=219),
                                FV(".text", offset=7404, size=4488),
                            ],
                            "elf_section_alignment": [
                                FV(0, label=""),
                                FV(1, label=".comment"),
                                FV(1, label=".dynstr"),
                                FV(1, label=".rodata"),
                                FV(1, label=".shstrtab"),
                                FV(2, label=".gnu.version"),
                                FV(4, label=".eh_frame_hdr"),
                                FV(4, label=".gnu.version_r"),
                                FV(4, label=".hash"),
                                FV(4, label=".note.android.ident"),
                                FV(4, label=".note.gnu.build-id"),
                                FV(4, label=".text"),
                                FV(8, label=".data.rel.ro"),
                                FV(8, label=".dynamic"),
                                FV(8, label=".dynsym"),
                                FV(8, label=".eh_frame"),
                                FV(8, label=".fini_array"),
                                FV(8, label=".gnu.hash"),
                                FV(8, label=".got"),
                                FV(8, label=".got.plt"),
                                FV(8, label=".rela.dyn"),
                                FV(8, label=".rela.plt"),
                                FV(16, label=".plt"),
                            ],
                            "elf_section_entropy": [
                                FV(0.0, label=""),
                                FV(-0.0, label=".data.rel.ro"),
                                FV(-0.0, label=".fini_array"),
                                FV(-0.0, label=".got"),
                                FV(1.0253042936602572, label=".got.plt"),
                                FV(1.1711992029444898, label=".note.android.ident"),
                                FV(1.2700883430413608, label=".gnu.version"),
                                FV(1.2925142659819988, label=".hash"),
                                FV(1.3520077791550043, label=".dynsym"),
                                FV(1.6034862426498901, label=".rela.dyn"),
                                FV(1.6786570571601478, label=".rela.plt"),
                                FV(1.7281171772778907, label=".dynamic"),
                                FV(1.9925416913014384, label=".gnu.version_r"),
                                FV(3.365152757362557, label=".eh_frame_hdr"),
                                FV(3.7744121009174, label=".eh_frame"),
                                FV(4.1916116417513765, label=".note.gnu.build-id"),
                                FV(4.197660819748763, label=".shstrtab"),
                                FV(4.361605985698939, label=".dynstr"),
                                FV(4.4260541689673465, label=".plt"),
                                FV(4.570473543983608, label=".gnu.hash"),
                                FV(4.75609078668789, label=".rodata"),
                                FV(5.094278929152885, label=".comment"),
                                FV(5.5978082953613155, label=".text"),
                            ],
                            "elf_section_entry_size": [
                                FV(0, label=""),
                                FV(0, label=".data.rel.ro"),
                                FV(0, label=".dynstr"),
                                FV(0, label=".eh_frame"),
                                FV(0, label=".eh_frame_hdr"),
                                FV(0, label=".fini_array"),
                                FV(0, label=".gnu.hash"),
                                FV(0, label=".gnu.version_r"),
                                FV(0, label=".got"),
                                FV(0, label=".got.plt"),
                                FV(0, label=".note.android.ident"),
                                FV(0, label=".note.gnu.build-id"),
                                FV(0, label=".plt"),
                                FV(0, label=".shstrtab"),
                                FV(0, label=".text"),
                                FV(1, label=".comment"),
                                FV(1, label=".rodata"),
                                FV(2, label=".gnu.version"),
                                FV(4, label=".hash"),
                                FV(16, label=".dynamic"),
                                FV(24, label=".dynsym"),
                                FV(24, label=".rela.dyn"),
                                FV(24, label=".rela.plt"),
                            ],
                            "elf_section_flags": [
                                FV("", label=""),
                                FV("", label=".shstrtab"),
                                FV("A", label=".dynstr"),
                                FV("A", label=".dynsym"),
                                FV("A", label=".eh_frame"),
                                FV("A", label=".eh_frame_hdr"),
                                FV("A", label=".gnu.hash"),
                                FV("A", label=".gnu.version"),
                                FV("A", label=".gnu.version_r"),
                                FV("A", label=".hash"),
                                FV("A", label=".note.android.ident"),
                                FV("A", label=".note.gnu.build-id"),
                                FV("A", label=".rela.dyn"),
                                FV("AI", label=".rela.plt"),
                                FV("AMS", label=".rodata"),
                                FV("AX", label=".plt"),
                                FV("AX", label=".text"),
                                FV("MS", label=".comment"),
                                FV("WA", label=".data.rel.ro"),
                                FV("WA", label=".dynamic"),
                                FV("WA", label=".fini_array"),
                                FV("WA", label=".got"),
                                FV("WA", label=".got.plt"),
                            ],
                            "elf_section_hash": [
                                FV(
                                    "07da4c357a6e43b2f6f28c58631f9efa93afa56c26b89d82ee46f3b5957f0e03",
                                    label=".note.android.ident",
                                ),
                                FV(
                                    "19821f2bb3e40fad22c9dc453a448387b0c0c1d6b3219b048edca5143a10439c", label=".rodata"
                                ),
                                FV("29881d6d7744965c8f5abd3c02dca1b790943de6b1257ee2f0ca34bb522d6854", label=".hash"),
                                FV(
                                    "299bd5e9e53c19f26a4f7e36affd2e00b02a12ca38c9a8045bf19bd87fa357cd", label=".dynsym"
                                ),
                                FV(
                                    "2b13df46dc4e37838a7998f98dc32cae35036ba5fd9ea0bde3cf97b4f43762d2",
                                    label=".eh_frame_hdr",
                                ),
                                FV(
                                    "35f0f930ee9fa0f9d75840bf36cbbbadb6eb872207ca0d799290f0ac07b5eacf",
                                    label=".rela.dyn",
                                ),
                                FV(
                                    "374708fff7719dd5979ec875d56cd2286f6d3cf7ec317a3b25632aab28ec37bb",
                                    label=".fini_array",
                                ),
                                FV(
                                    "3a0796043b9f20e0c5defd670468402c6f88d5627d0bc9f10ff6af7b1c18b48d",
                                    label=".shstrtab",
                                ),
                                FV(
                                    "4a0ff76c26cab48bc16417c0f285ce73607d336eab19ecb334bdbe0fdae48328",
                                    label=".dynamic",
                                ),
                                FV("4bc5e70468e84ca023428c552fb75747b96a078e6d59986d0d9ac6ddcdf013f7", label=".plt"),
                                FV(
                                    "64883685c515164118e5396c3b1bfbcdc93b6adba94bff08504c041f7945057d",
                                    label=".note.gnu.build-id",
                                ),
                                FV(
                                    "7cc7778b092f77588565e1e4fa67adba02194b619baaf705629f336d6637215c",
                                    label=".rela.plt",
                                ),
                                FV(
                                    "86cdc69a168d9e55ddb456e6a890909d19943641132f31b4468be7bb7aa1b938",
                                    label=".eh_frame",
                                ),
                                FV(
                                    "9e84301b8bbe848eda3c98ed0dc02ba008ccfa84b8993dd28cbda127da1e8557", label=".dynstr"
                                ),
                                FV("a37d6a016cd804567603bcebcb5da6365356fe89285b9df44510074ba7ccea18", label=".text"),
                                FV(
                                    "acaabc1ddcc4bcb336bbd46405b99a3d8c452083e4db69ece005a009206738e9",
                                    label=".got.plt",
                                ),
                                FV(
                                    "af5570f5a1810b7af78caf4bc70a660f0df51e42baf91d4de5b2328de0e83dfc",
                                    label=".data.rel.ro",
                                ),
                                FV("af5570f5a1810b7af78caf4bc70a660f0df51e42baf91d4de5b2328de0e83dfc", label=".got"),
                                FV(
                                    "b11ae4ee1c92b3f55861d42feda72fdb0f04a84371b6d1cb41256909f6304fc6",
                                    label=".gnu.version",
                                ),
                                FV(
                                    "bee0e2c54efe05ddf108b0620fa32dc6b26f26f27accef9b358d74dae569d63a",
                                    label=".comment",
                                ),
                                FV(
                                    "bf9f2bafee8f2eb69acbace69a643516b07b88f4b7cc1f2d7f676f26c56f3bff",
                                    label=".gnu.version_r",
                                ),
                                FV(
                                    "c224513f85d530378d000d7ccbbb4e2254dfab4e07241f3041b8ea6a70fd1c34",
                                    label=".gnu.hash",
                                ),
                                FV("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", label=""),
                            ],
                            "elf_section_header_offset": [FV(14168)],
                            "elf_section_header_size": [FV(64)],
                            "elf_section_information": [
                                FV(0, label=""),
                                FV(0, label=".comment"),
                                FV(0, label=".data.rel.ro"),
                                FV(0, label=".dynamic"),
                                FV(0, label=".dynstr"),
                                FV(0, label=".eh_frame"),
                                FV(0, label=".eh_frame_hdr"),
                                FV(0, label=".fini_array"),
                                FV(0, label=".gnu.hash"),
                                FV(0, label=".gnu.version"),
                                FV(0, label=".got"),
                                FV(0, label=".got.plt"),
                                FV(0, label=".hash"),
                                FV(0, label=".note.android.ident"),
                                FV(0, label=".note.gnu.build-id"),
                                FV(0, label=".plt"),
                                FV(0, label=".rela.dyn"),
                                FV(0, label=".rodata"),
                                FV(0, label=".shstrtab"),
                                FV(0, label=".text"),
                                FV(1, label=".dynsym"),
                                FV(1, label=".gnu.version_r"),
                                FV(20, label=".rela.plt"),
                            ],
                            "elf_section_link": [
                                FV(0, label=""),
                                FV(0, label=".comment"),
                                FV(0, label=".data.rel.ro"),
                                FV(0, label=".dynstr"),
                                FV(0, label=".eh_frame"),
                                FV(0, label=".eh_frame_hdr"),
                                FV(0, label=".fini_array"),
                                FV(0, label=".got"),
                                FV(0, label=".got.plt"),
                                FV(0, label=".note.android.ident"),
                                FV(0, label=".note.gnu.build-id"),
                                FV(0, label=".plt"),
                                FV(0, label=".rodata"),
                                FV(0, label=".shstrtab"),
                                FV(0, label=".text"),
                                FV(3, label=".gnu.hash"),
                                FV(3, label=".gnu.version"),
                                FV(3, label=".hash"),
                                FV(3, label=".rela.dyn"),
                                FV(3, label=".rela.plt"),
                                FV(8, label=".dynamic"),
                                FV(8, label=".dynsym"),
                                FV(8, label=".gnu.version_r"),
                            ],
                            "elf_section_name_table_idx": [FV(22)],
                            "elf_section_num_flags": [
                                FV(0, label=""),
                                FV(0, label=".shstrtab"),
                                FV(2, label=".dynstr"),
                                FV(2, label=".dynsym"),
                                FV(2, label=".eh_frame"),
                                FV(2, label=".eh_frame_hdr"),
                                FV(2, label=".gnu.hash"),
                                FV(2, label=".gnu.version"),
                                FV(2, label=".gnu.version_r"),
                                FV(2, label=".hash"),
                                FV(2, label=".note.android.ident"),
                                FV(2, label=".note.gnu.build-id"),
                                FV(2, label=".rela.dyn"),
                                FV(3, label=".data.rel.ro"),
                                FV(3, label=".dynamic"),
                                FV(3, label=".fini_array"),
                                FV(3, label=".got"),
                                FV(3, label=".got.plt"),
                                FV(6, label=".plt"),
                                FV(6, label=".text"),
                                FV(48, label=".comment"),
                                FV(50, label=".rodata"),
                                FV(66, label=".rela.plt"),
                            ],
                            "elf_section_segments": [
                                FV("", label=""),
                                FV("", label=".comment"),
                                FV("", label=".shstrtab"),
                                FV("LOAD", label=".dynstr"),
                                FV("LOAD", label=".dynsym"),
                                FV("LOAD", label=".eh_frame"),
                                FV("LOAD", label=".gnu.hash"),
                                FV("LOAD", label=".gnu.version"),
                                FV("LOAD", label=".gnu.version_r"),
                                FV("LOAD", label=".hash"),
                                FV("LOAD", label=".plt"),
                                FV("LOAD", label=".rela.dyn"),
                                FV("LOAD", label=".rela.plt"),
                                FV("LOAD", label=".rodata"),
                                FV("LOAD", label=".text"),
                                FV("LOAD - DYNAMIC - GNU_RELRO", label=".dynamic"),
                                FV("LOAD - GNU_EH_FRAME", label=".eh_frame_hdr"),
                                FV("LOAD - GNU_RELRO", label=".data.rel.ro"),
                                FV("LOAD - GNU_RELRO", label=".fini_array"),
                                FV("LOAD - GNU_RELRO", label=".got"),
                                FV("LOAD - GNU_RELRO", label=".got.plt"),
                                FV("LOAD - NOTE", label=".note.android.ident"),
                                FV("LOAD - NOTE", label=".note.gnu.build-id"),
                            ],
                            "elf_section_type": [
                                FV("DYNAMIC", label=".dynamic"),
                                FV("DYNSYM", label=".dynsym"),
                                FV("FINI_ARRAY", label=".fini_array"),
                                FV("GNU_HASH", label=".gnu.hash"),
                                FV("HASH", label=".hash"),
                                FV("NOTE", label=".note.android.ident"),
                                FV("NOTE", label=".note.gnu.build-id"),
                                FV("NULL", label=""),
                                FV("PROGBITS", label=".comment"),
                                FV("PROGBITS", label=".data.rel.ro"),
                                FV("PROGBITS", label=".eh_frame"),
                                FV("PROGBITS", label=".eh_frame_hdr"),
                                FV("PROGBITS", label=".got"),
                                FV("PROGBITS", label=".got.plt"),
                                FV("PROGBITS", label=".plt"),
                                FV("PROGBITS", label=".rodata"),
                                FV("PROGBITS", label=".text"),
                                FV("RELA", label=".rela.dyn"),
                                FV("RELA", label=".rela.plt"),
                                FV("STRTAB", label=".dynstr"),
                                FV("STRTAB", label=".shstrtab"),
                                FV("VERNEED", label=".gnu.version_r"),
                                FV("VERSYM", label=".gnu.version"),
                            ],
                            "elf_section_virtual_address": [
                                FV(0, label=""),
                                FV(0, label=".comment"),
                                FV(0, label=".shstrtab"),
                                FV(512, label=".note.android.ident"),
                                FV(664, label=".note.gnu.build-id"),
                                FV(704, label=".dynsym"),
                                FV(2240, label=".gnu.version"),
                                FV(2368, label=".gnu.version_r"),
                                FV(2400, label=".gnu.hash"),
                                FV(2500, label=".hash"),
                                FV(3020, label=".dynstr"),
                                FV(4824, label=".rela.dyn"),
                                FV(4920, label=".rela.plt"),
                                FV(6168, label=".rodata"),
                                FV(6572, label=".eh_frame_hdr"),
                                FV(6736, label=".eh_frame"),
                                FV(7404, label=".text"),
                                FV(11904, label=".plt"),
                                FV(16864, label=".data.rel.ro"),
                                FV(16872, label=".fini_array"),
                                FV(16888, label=".dynamic"),
                                FV(17320, label=".got"),
                                FV(17328, label=".got.plt"),
                            ],
                            "elf_segment": [
                                FV(0, offset=64, size=448),
                                FV(1, offset=0, size=12768),
                                FV(2, offset=12768, size=904),
                                FV(3, offset=12792, size=432),
                                FV(4, offset=12768, size=904),
                                FV(5, offset=6572, size=164),
                                FV(6, offset=0, size=0),
                                FV(7, offset=512, size=188),
                            ],
                            "elf_segment_alignment": [
                                FV(0, label="6"),
                                FV(1, label="4"),
                                FV(4, label="5"),
                                FV(4, label="7"),
                                FV(8, label="0"),
                                FV(8, label="3"),
                                FV(4096, label="1"),
                                FV(4096, label="2"),
                            ],
                            "elf_segment_flags": [
                                FV("R--", label="0"),
                                FV("R--", label="4"),
                                FV("R--", label="5"),
                                FV("R--", label="7"),
                                FV("R-X", label="1"),
                                FV("RW-", label="2"),
                                FV("RW-", label="3"),
                                FV("RW-", label="6"),
                            ],
                            "elf_segment_physical_address": [
                                FV(0, label="1"),
                                FV(0, label="6"),
                                FV(64, label="0"),
                                FV(512, label="7"),
                                FV(6572, label="5"),
                                FV(16864, label="2"),
                                FV(16864, label="4"),
                                FV(16888, label="3"),
                            ],
                            "elf_segment_sections": [
                                FV("", label="0"),
                                FV("", label="6"),
                                FV(".data.rel.ro, .fini_array, .dynamic, .got, .got.plt", label="2"),
                                FV(".data.rel.ro, .fini_array, .dynamic, .got, .got.plt", label="4"),
                                FV(".dynamic", label="3"),
                                FV(".eh_frame_hdr", label="5"),
                                FV(".note.android.ident, .note.gnu.build-id", label="7"),
                                FV(
                                    ".note.android.ident, .note.gnu.build-id, .dynsym, .gnu.version, .gnu.version_r, .gnu.hash, .hash, .dynstr, .rela.dyn, .rela.plt, .rodata, .eh_frame_hdr, .eh_frame, .text, .plt",
                                    label="1",
                                ),
                            ],
                            "elf_segment_type": [
                                FV("DYNAMIC", label="3"),
                                FV("GNU_EH_FRAME", label="5"),
                                FV("GNU_RELRO", label="4"),
                                FV("GNU_STACK", label="6"),
                                FV("LOAD", label="1"),
                                FV("LOAD", label="2"),
                                FV("NOTE", label="7"),
                                FV("PHDR", label="0"),
                            ],
                            "elf_segment_virtual_address": [
                                FV(0, label="1"),
                                FV(0, label="6"),
                                FV(64, label="0"),
                                FV(512, label="7"),
                                FV(6572, label="5"),
                                FV(16864, label="2"),
                                FV(16864, label="4"),
                                FV(16888, label="3"),
                            ],
                            "elf_segment_virtual_size": [
                                FV(0, label="6"),
                                FV(164, label="5"),
                                FV(188, label="7"),
                                FV(432, label="3"),
                                FV(448, label="0"),
                                FV(904, label="2"),
                                FV(3616, label="4"),
                                FV(12768, label="1"),
                            ],
                            "elf_type": [FV("DYN (Shared object file)")],
                        },
                    )
                ],
            ),
        )
