"""
LIEF PE test suite
===================

Test the LIEF PE plugin

"""

import datetime

from azul_runner import (
    FV,
    DataLabel,
    Event,
    EventData,
    EventParent,
    JobResult,
    State,
    test_template,
)

from azul_plugin_lief.lief_pe import AzulPluginLiefPE


class TestExecute(test_template.TestPlugin):
    PLUGIN_TO_TEST = AzulPluginLiefPE

    def test_lief_pe_certificate_extraction(self):
        """Sigcheck executable for extracting certificate values."""
        result = self.do_execution(
            data_in=[
                (
                    DataLabel.CONTENT,
                    self.load_test_file_bytes(
                        "4fe9a2bd4b160a5352333d00d0b0c10f13685af7acdb48e9e9d0c3877a19eed4",
                        "Benign Windows 32EXE, sigcheck.exe used for validation PE signatures.",
                    ),
                )
            ]
        )
        self.assertJobResult(
            result,
            JobResult(
                state=State(State.Label.COMPLETED),
                events=[
                    Event(
                        sha256="4fe9a2bd4b160a5352333d00d0b0c10f13685af7acdb48e9e9d0c3877a19eed4",
                        features={
                            "authentihash": [FV("c8361aec219d230e6aba29521f523e79cac271f3ce45418d80681438dcdbedc0")],
                            "pe_characteristics": [FV("EXECUTABLE_IMAGE"), FV("NEED_32BIT_MACHINE")],
                            "pe_checksum": [FV("507855")],
                            "pe_code_base": [FV("4096")],
                            "pe_code_size": [FV("272384")],
                            "pe_compile_time": [FV("2022-07-18T14:54:12")],
                            "pe_data_base": [FV("278528")],
                            "pe_debug_characteristics": [
                                FV("0", label="CODEVIEW"),
                                FV("0", label="POGO"),
                                FV("0", label="VC_FEATURE"),
                            ],
                            "pe_debug_codeview_age": [FV("1")],
                            "pe_debug_codeview_filename": [FV("D:\\a\\1\\s\\Win32\\Release\\sigcheck.pdb")],
                            "pe_debug_codeview_guid": [FV("973d9dae-eebe-48ae-af5f-bf5abcadef08")],
                            "pe_debug_codeview_signature": [FV("PDB_70")],
                            "pe_debug_offset": [
                                FV("388880", label="CODEVIEW"),
                                FV("388940", label="VC_FEATURE"),
                                FV("388960", label="POGO"),
                            ],
                            "pe_debug_size": [
                                FV("20", label="VC_FEATURE"),
                                FV("60", label="CODEVIEW"),
                                FV("964", label="POGO"),
                            ],
                            "pe_debug_timestamp": [
                                FV("2022-07-18T14:54:12", label="CODEVIEW"),
                                FV("2022-07-18T14:54:12", label="POGO"),
                                FV("2022-07-18T14:54:12", label="VC_FEATURE"),
                            ],
                            "pe_debug_type": [
                                FV("CODEVIEW", offset=388880, size=60),
                                FV("POGO", offset=388960, size=964),
                                FV("VC_FEATURE", offset=388940, size=20),
                            ],
                            "pe_debug_version": [
                                FV("0.0", label="CODEVIEW"),
                                FV("0.0", label="POGO"),
                                FV("0.0", label="VC_FEATURE"),
                            ],
                            "pe_dll_characteristics": [
                                FV("DYNAMIC_BASE"),
                                FV("NX_COMPAT"),
                                FV("TERMINAL_SERVER_AWARE"),
                            ],
                            "pe_dos_stub": [
                                FV(
                                    "Dh+6DgC0Cc0huAFMzSFUaGlzIHByb2dyYW0gY2Fubm90IGJlIHJ1biBpbiBET1MgbW9kZS4NDQokAAAAAAAAAA=="
                                )
                            ],
                            "pe_entry_point": [FV("97047")],
                            "pe_file_alignment": [FV("512")],
                            "pe_header_size": [FV("1024")],
                            "pe_heap_commit_size": [FV("4096")],
                            "pe_heap_reserve_size": [FV("1048576")],
                            "pe_image_base": [FV("4194304")],
                            "pe_image_size": [FV("454656")],
                            "pe_image_version": [FV("0.0")],
                            "pe_import_function": [
                                FV("AllocateAndInitializeSid", label="ADVAPI32.dll"),
                                FV("CLSIDFromString", label="ole32.dll"),
                                FV("CertAddCertificateContextToStore", label="CRYPT32.dll"),
                                FV("CertCloseStore", label="CRYPT32.dll"),
                                FV("CertCreateCTLContext", label="CRYPT32.dll"),
                                FV("CertDuplicateCertificateContext", label="CRYPT32.dll"),
                                FV("CertEnumCertificatesInStore", label="CRYPT32.dll"),
                                FV("CertFreeCertificateChain", label="CRYPT32.dll"),
                                FV("CertFreeCertificateContext", label="CRYPT32.dll"),
                                FV("CertGetCertificateChain", label="CRYPT32.dll"),
                                FV("CertGetCertificateContextProperty", label="CRYPT32.dll"),
                                FV("CertGetNameStringW", label="CRYPT32.dll"),
                                FV("CertGetStoreProperty", label="CRYPT32.dll"),
                                FV("CertGetValidUsages", label="CRYPT32.dll"),
                                FV("CertOpenStore", label="CRYPT32.dll"),
                                FV("CloseHandle", label="KERNEL32.dll"),
                                FV("CoCreateInstance", label="ole32.dll"),
                                FV("CompareStringW", label="KERNEL32.dll"),
                                FV("CreateCompatibleDC", label="GDI32.dll"),
                                FV("CreateEventW", label="KERNEL32.dll"),
                                FV("CreateFileA", label="KERNEL32.dll"),
                                FV("CreateFileMappingW", label="KERNEL32.dll"),
                                FV("CreateFileW", label="KERNEL32.dll"),
                                FV("CryptAcquireContextW", label="ADVAPI32.dll"),
                                FV("CryptCATClose", label="WINTRUST.dll"),
                                FV("CryptCATEnumerateAttr", label="WINTRUST.dll"),
                                FV("CryptCATEnumerateCatAttr", label="WINTRUST.dll"),
                                FV("CryptCATEnumerateMember", label="WINTRUST.dll"),
                                FV("CryptCATOpen", label="WINTRUST.dll"),
                                FV("CryptCreateHash", label="ADVAPI32.dll"),
                                FV("CryptDestroyHash", label="ADVAPI32.dll"),
                                FV("CryptFindOIDInfo", label="CRYPT32.dll"),
                                FV("CryptGetHashParam", label="ADVAPI32.dll"),
                                FV("CryptHashData", label="ADVAPI32.dll"),
                                FV("CryptReleaseContext", label="ADVAPI32.dll"),
                                FV("CryptSIPLoad", label="CRYPT32.dll"),
                                FV("CryptSIPRetrieveSubjectGuidForCatalogFile", label="CRYPT32.dll"),
                                FV("DecodePointer", label="KERNEL32.dll"),
                                FV("DeleteCriticalSection", label="KERNEL32.dll"),
                                FV("DeleteDC", label="GDI32.dll"),
                                FV("DeleteFileW", label="KERNEL32.dll"),
                                FV("DialogBoxIndirectParamW", label="USER32.dll"),
                                FV("DosDateTimeToFileTime", label="KERNEL32.dll"),
                                FV("EncodePointer", label="KERNEL32.dll"),
                                FV("EndDialog", label="USER32.dll"),
                                FV("EndDoc", label="GDI32.dll"),
                                FV("EndPage", label="GDI32.dll"),
                                FV("EnterCriticalSection", label="KERNEL32.dll"),
                                FV("EnumSystemLocalesW", label="KERNEL32.dll"),
                                FV("EqualSid", label="ADVAPI32.dll"),
                                FV("ExitProcess", label="KERNEL32.dll"),
                                FV("ExpandEnvironmentStringsA", label="KERNEL32.dll"),
                                FV("FileTimeToLocalFileTime", label="KERNEL32.dll"),
                                FV("FileTimeToSystemTime", label="KERNEL32.dll"),
                                FV("FindClose", label="KERNEL32.dll"),
                                FV("FindFirstFileExW", label="KERNEL32.dll"),
                                FV("FindFirstFileW", label="KERNEL32.dll"),
                                FV("FindNextFileW", label="KERNEL32.dll"),
                                FV("FindResourceW", label="KERNEL32.dll"),
                                FV("FlushFileBuffers", label="KERNEL32.dll"),
                                FV("FormatMessageW", label="KERNEL32.dll"),
                                FV("FreeEnvironmentStringsW", label="KERNEL32.dll"),
                                FV("FreeLibrary", label="KERNEL32.dll"),
                                FV("FreeResource", label="KERNEL32.dll"),
                                FV("FreeSid", label="ADVAPI32.dll"),
                                FV("GetACP", label="KERNEL32.dll"),
                                FV("GetCPInfo", label="KERNEL32.dll"),
                                FV("GetCommandLineA", label="KERNEL32.dll"),
                                FV("GetCommandLineW", label="KERNEL32.dll"),
                                FV("GetConsoleCP", label="KERNEL32.dll"),
                                FV("GetConsoleMode", label="KERNEL32.dll"),
                                FV("GetConsoleOutputCP", label="KERNEL32.dll"),
                                FV("GetCurrentDirectoryA", label="KERNEL32.dll"),
                                FV("GetCurrentDirectoryW", label="KERNEL32.dll"),
                                FV("GetCurrentProcess", label="KERNEL32.dll"),
                                FV("GetCurrentProcessId", label="KERNEL32.dll"),
                                FV("GetCurrentThreadId", label="KERNEL32.dll"),
                                FV("GetDateFormatW", label="KERNEL32.dll"),
                                FV("GetDeviceCaps", label="GDI32.dll"),
                                FV("GetDlgItem", label="USER32.dll"),
                                FV("GetEnvironmentStringsW", label="KERNEL32.dll"),
                                FV("GetFileAttributesW", label="KERNEL32.dll"),
                                FV("GetFileInformationByHandle", label="KERNEL32.dll"),
                                FV("GetFileSize", label="KERNEL32.dll"),
                                FV("GetFileSizeEx", label="KERNEL32.dll"),
                                FV("GetFileType", label="KERNEL32.dll"),
                                FV("GetFileVersionInfoSizeW", label="VERSION.dll"),
                                FV("GetFileVersionInfoW", label="VERSION.dll"),
                                FV("GetFullPathNameW", label="KERNEL32.dll"),
                                FV("GetLastError", label="KERNEL32.dll"),
                                FV("GetLocaleInfoW", label="KERNEL32.dll"),
                                FV("GetModuleFileNameW", label="KERNEL32.dll"),
                                FV("GetModuleHandleExW", label="KERNEL32.dll"),
                                FV("GetModuleHandleW", label="KERNEL32.dll"),
                                FV("GetOEMCP", label="KERNEL32.dll"),
                                FV("GetProcAddress", label="KERNEL32.dll"),
                                FV("GetProcessHeap", label="KERNEL32.dll"),
                                FV("GetStartupInfoW", label="KERNEL32.dll"),
                                FV("GetStdHandle", label="KERNEL32.dll"),
                                FV("GetStringTypeW", label="KERNEL32.dll"),
                                FV("GetSysColorBrush", label="USER32.dll"),
                                FV("GetSystemTimeAsFileTime", label="KERNEL32.dll"),
                                FV("GetTimeFormatW", label="KERNEL32.dll"),
                                FV("GetTokenInformation", label="ADVAPI32.dll"),
                                FV("GetUserDefaultLCID", label="KERNEL32.dll"),
                                FV("GetVersion", label="KERNEL32.dll"),
                                FV("GetVersionExW", label="KERNEL32.dll"),
                                FV("HeapAlloc", label="KERNEL32.dll"),
                                FV("HeapFree", label="KERNEL32.dll"),
                                FV("HeapReAlloc", label="KERNEL32.dll"),
                                FV("HeapSize", label="KERNEL32.dll"),
                                FV("InflateRect", label="USER32.dll"),
                                FV("InitializeCriticalSectionAndSpinCount", label="KERNEL32.dll"),
                                FV("InitializeCriticalSectionEx", label="KERNEL32.dll"),
                                FV("InitializeSListHead", label="KERNEL32.dll"),
                                FV("IsDebuggerPresent", label="KERNEL32.dll"),
                                FV("IsProcessorFeaturePresent", label="KERNEL32.dll"),
                                FV("IsValidCodePage", label="KERNEL32.dll"),
                                FV("IsValidLocale", label="KERNEL32.dll"),
                                FV("LCMapStringEx", label="KERNEL32.dll"),
                                FV("LCMapStringW", label="KERNEL32.dll"),
                                FV("LeaveCriticalSection", label="KERNEL32.dll"),
                                FV("LoadCursorW", label="USER32.dll"),
                                FV("LoadLibraryExW", label="KERNEL32.dll"),
                                FV("LoadLibraryW", label="KERNEL32.dll"),
                                FV("LoadResource", label="KERNEL32.dll"),
                                FV("LocalAlloc", label="KERNEL32.dll"),
                                FV("LocalFileTimeToFileTime", label="KERNEL32.dll"),
                                FV("LocalFree", label="KERNEL32.dll"),
                                FV("LockResource", label="KERNEL32.dll"),
                                FV("MapViewOfFile", label="KERNEL32.dll"),
                                FV("MessageBoxW", label="USER32.dll"),
                                FV("MulDiv", label="KERNEL32.dll"),
                                FV("MultiByteToWideChar", label="KERNEL32.dll"),
                                FV("OpenProcessToken", label="ADVAPI32.dll"),
                                FV("OutputDebugStringW", label="KERNEL32.dll"),
                                FV("PrintDlgW", label="COMDLG32.dll"),
                                FV("QueryPerformanceCounter", label="KERNEL32.dll"),
                                FV("RaiseException", label="KERNEL32.dll"),
                                FV("ReadConsoleInputW", label="KERNEL32.dll"),
                                FV("ReadConsoleW", label="KERNEL32.dll"),
                                FV("ReadFile", label="KERNEL32.dll"),
                                FV("RegCloseKey", label="ADVAPI32.dll"),
                                FV("RegCreateKeyExW", label="ADVAPI32.dll"),
                                FV("RegCreateKeyW", label="ADVAPI32.dll"),
                                FV("RegDeleteValueW", label="ADVAPI32.dll"),
                                FV("RegEnumKeyW", label="ADVAPI32.dll"),
                                FV("RegOpenKeyExW", label="ADVAPI32.dll"),
                                FV("RegOpenKeyW", label="ADVAPI32.dll"),
                                FV("RegQueryValueExW", label="ADVAPI32.dll"),
                                FV("RegSetValueExW", label="ADVAPI32.dll"),
                                FV("RtlUnwind", label="KERNEL32.dll"),
                                FV("SendMessageW", label="USER32.dll"),
                                FV("SetConsoleMode", label="KERNEL32.dll"),
                                FV("SetCursor", label="USER32.dll"),
                                FV("SetEndOfFile", label="KERNEL32.dll"),
                                FV("SetEnvironmentVariableW", label="KERNEL32.dll"),
                                FV("SetFileInformationByHandle", label="KERNEL32.dll"),
                                FV("SetFilePointer", label="KERNEL32.dll"),
                                FV("SetFilePointerEx", label="KERNEL32.dll"),
                                FV("SetLastError", label="KERNEL32.dll"),
                                FV("SetMapMode", label="GDI32.dll"),
                                FV("SetStdHandle", label="KERNEL32.dll"),
                                FV("SetUnhandledExceptionFilter", label="KERNEL32.dll"),
                                FV("SetWindowTextW", label="USER32.dll"),
                                FV("ShellExecuteW", label="SHELL32.dll"),
                                FV("SizeofResource", label="KERNEL32.dll"),
                                FV("StartDocW", label="GDI32.dll"),
                                FV("StartPage", label="GDI32.dll"),
                                FV("TerminateProcess", label="KERNEL32.dll"),
                                FV("TlsAlloc", label="KERNEL32.dll"),
                                FV("TlsFree", label="KERNEL32.dll"),
                                FV("TlsGetValue", label="KERNEL32.dll"),
                                FV("TlsSetValue", label="KERNEL32.dll"),
                                FV("UnhandledExceptionFilter", label="KERNEL32.dll"),
                                FV("UnmapViewOfFile", label="KERNEL32.dll"),
                                FV("VerQueryValueW", label="VERSION.dll"),
                                FV("WideCharToMultiByte", label="KERNEL32.dll"),
                                FV("WinHttpCloseHandle", label="WINHTTP.dll"),
                                FV("WinHttpConnect", label="WINHTTP.dll"),
                                FV("WinHttpGetProxyForUrl", label="WINHTTP.dll"),
                                FV("WinHttpOpen", label="WINHTTP.dll"),
                                FV("WinHttpOpenRequest", label="WINHTTP.dll"),
                                FV("WinHttpQueryDataAvailable", label="WINHTTP.dll"),
                                FV("WinHttpQueryHeaders", label="WINHTTP.dll"),
                                FV("WinHttpReadData", label="WINHTTP.dll"),
                                FV("WinHttpReceiveResponse", label="WINHTTP.dll"),
                                FV("WinHttpSendRequest", label="WINHTTP.dll"),
                                FV("WinHttpSetOption", label="WINHTTP.dll"),
                                FV("WinHttpWriteData", label="WINHTTP.dll"),
                                FV("WriteConsoleW", label="KERNEL32.dll"),
                                FV("WriteFile", label="KERNEL32.dll"),
                            ],
                            "pe_import_function_count": [
                                FV("1", label="COMDLG32.dll"),
                                FV("1", label="SHELL32.dll"),
                                FV("1", label="SHLWAPI.dll"),
                                FV("10", label="USER32.dll"),
                                FV("114", label="KERNEL32.dll"),
                                FV("12", label="WINHTTP.dll"),
                                FV("16", label="CRYPT32.dll"),
                                FV("2", label="ole32.dll"),
                                FV("20", label="ADVAPI32.dll"),
                                FV("3", label="Cabinet.dll"),
                                FV("3", label="VERSION.dll"),
                                FV("5", label="WINTRUST.dll"),
                                FV("7", label="OLEAUT32.dll"),
                                FV("8", label="GDI32.dll"),
                            ],
                            "pe_import_function_fullname": [
                                FV("ADVAPI32.dll!AllocateAndInitializeSid"),
                                FV("ADVAPI32.dll!CryptAcquireContextW"),
                                FV("ADVAPI32.dll!CryptCreateHash"),
                                FV("ADVAPI32.dll!CryptDestroyHash"),
                                FV("ADVAPI32.dll!CryptGetHashParam"),
                                FV("ADVAPI32.dll!CryptHashData"),
                                FV("ADVAPI32.dll!CryptReleaseContext"),
                                FV("ADVAPI32.dll!EqualSid"),
                                FV("ADVAPI32.dll!FreeSid"),
                                FV("ADVAPI32.dll!GetTokenInformation"),
                                FV("ADVAPI32.dll!OpenProcessToken"),
                                FV("ADVAPI32.dll!RegCloseKey"),
                                FV("ADVAPI32.dll!RegCreateKeyExW"),
                                FV("ADVAPI32.dll!RegCreateKeyW"),
                                FV("ADVAPI32.dll!RegDeleteValueW"),
                                FV("ADVAPI32.dll!RegEnumKeyW"),
                                FV("ADVAPI32.dll!RegOpenKeyExW"),
                                FV("ADVAPI32.dll!RegOpenKeyW"),
                                FV("ADVAPI32.dll!RegQueryValueExW"),
                                FV("ADVAPI32.dll!RegSetValueExW"),
                                FV("COMDLG32.dll!PrintDlgW"),
                                FV("CRYPT32.dll!CertAddCertificateContextToStore"),
                                FV("CRYPT32.dll!CertCloseStore"),
                                FV("CRYPT32.dll!CertCreateCTLContext"),
                                FV("CRYPT32.dll!CertDuplicateCertificateContext"),
                                FV("CRYPT32.dll!CertEnumCertificatesInStore"),
                                FV("CRYPT32.dll!CertFreeCertificateChain"),
                                FV("CRYPT32.dll!CertFreeCertificateContext"),
                                FV("CRYPT32.dll!CertGetCertificateChain"),
                                FV("CRYPT32.dll!CertGetCertificateContextProperty"),
                                FV("CRYPT32.dll!CertGetNameStringW"),
                                FV("CRYPT32.dll!CertGetStoreProperty"),
                                FV("CRYPT32.dll!CertGetValidUsages"),
                                FV("CRYPT32.dll!CertOpenStore"),
                                FV("CRYPT32.dll!CryptFindOIDInfo"),
                                FV("CRYPT32.dll!CryptSIPLoad"),
                                FV("CRYPT32.dll!CryptSIPRetrieveSubjectGuidForCatalogFile"),
                                FV("Cabinet.dll!20"),
                                FV("Cabinet.dll!22"),
                                FV("Cabinet.dll!23"),
                                FV("GDI32.dll!CreateCompatibleDC"),
                                FV("GDI32.dll!DeleteDC"),
                                FV("GDI32.dll!EndDoc"),
                                FV("GDI32.dll!EndPage"),
                                FV("GDI32.dll!GetDeviceCaps"),
                                FV("GDI32.dll!SetMapMode"),
                                FV("GDI32.dll!StartDocW"),
                                FV("GDI32.dll!StartPage"),
                                FV("KERNEL32.dll!CloseHandle"),
                                FV("KERNEL32.dll!CompareStringW"),
                                FV("KERNEL32.dll!CreateEventW"),
                                FV("KERNEL32.dll!CreateFileA"),
                                FV("KERNEL32.dll!CreateFileMappingW"),
                                FV("KERNEL32.dll!CreateFileW"),
                                FV("KERNEL32.dll!DecodePointer"),
                                FV("KERNEL32.dll!DeleteCriticalSection"),
                                FV("KERNEL32.dll!DeleteFileW"),
                                FV("KERNEL32.dll!DosDateTimeToFileTime"),
                                FV("KERNEL32.dll!EncodePointer"),
                                FV("KERNEL32.dll!EnterCriticalSection"),
                                FV("KERNEL32.dll!EnumSystemLocalesW"),
                                FV("KERNEL32.dll!ExitProcess"),
                                FV("KERNEL32.dll!ExpandEnvironmentStringsA"),
                                FV("KERNEL32.dll!FileTimeToLocalFileTime"),
                                FV("KERNEL32.dll!FileTimeToSystemTime"),
                                FV("KERNEL32.dll!FindClose"),
                                FV("KERNEL32.dll!FindFirstFileExW"),
                                FV("KERNEL32.dll!FindFirstFileW"),
                                FV("KERNEL32.dll!FindNextFileW"),
                                FV("KERNEL32.dll!FindResourceW"),
                                FV("KERNEL32.dll!FlushFileBuffers"),
                                FV("KERNEL32.dll!FormatMessageW"),
                                FV("KERNEL32.dll!FreeEnvironmentStringsW"),
                                FV("KERNEL32.dll!FreeLibrary"),
                                FV("KERNEL32.dll!FreeResource"),
                                FV("KERNEL32.dll!GetACP"),
                                FV("KERNEL32.dll!GetCPInfo"),
                                FV("KERNEL32.dll!GetCommandLineA"),
                                FV("KERNEL32.dll!GetCommandLineW"),
                                FV("KERNEL32.dll!GetConsoleCP"),
                                FV("KERNEL32.dll!GetConsoleMode"),
                                FV("KERNEL32.dll!GetConsoleOutputCP"),
                                FV("KERNEL32.dll!GetCurrentDirectoryA"),
                                FV("KERNEL32.dll!GetCurrentDirectoryW"),
                                FV("KERNEL32.dll!GetCurrentProcess"),
                                FV("KERNEL32.dll!GetCurrentProcessId"),
                                FV("KERNEL32.dll!GetCurrentThreadId"),
                                FV("KERNEL32.dll!GetDateFormatW"),
                                FV("KERNEL32.dll!GetEnvironmentStringsW"),
                                FV("KERNEL32.dll!GetFileAttributesW"),
                                FV("KERNEL32.dll!GetFileInformationByHandle"),
                                FV("KERNEL32.dll!GetFileSize"),
                                FV("KERNEL32.dll!GetFileSizeEx"),
                                FV("KERNEL32.dll!GetFileType"),
                                FV("KERNEL32.dll!GetFullPathNameW"),
                                FV("KERNEL32.dll!GetLastError"),
                                FV("KERNEL32.dll!GetLocaleInfoW"),
                                FV("KERNEL32.dll!GetModuleFileNameW"),
                                FV("KERNEL32.dll!GetModuleHandleExW"),
                                FV("KERNEL32.dll!GetModuleHandleW"),
                                FV("KERNEL32.dll!GetOEMCP"),
                                FV("KERNEL32.dll!GetProcAddress"),
                                FV("KERNEL32.dll!GetProcessHeap"),
                                FV("KERNEL32.dll!GetStartupInfoW"),
                                FV("KERNEL32.dll!GetStdHandle"),
                                FV("KERNEL32.dll!GetStringTypeW"),
                                FV("KERNEL32.dll!GetSystemTimeAsFileTime"),
                                FV("KERNEL32.dll!GetTimeFormatW"),
                                FV("KERNEL32.dll!GetUserDefaultLCID"),
                                FV("KERNEL32.dll!GetVersion"),
                                FV("KERNEL32.dll!GetVersionExW"),
                                FV("KERNEL32.dll!HeapAlloc"),
                                FV("KERNEL32.dll!HeapFree"),
                                FV("KERNEL32.dll!HeapReAlloc"),
                                FV("KERNEL32.dll!HeapSize"),
                                FV("KERNEL32.dll!InitializeCriticalSectionAndSpinCount"),
                                FV("KERNEL32.dll!InitializeCriticalSectionEx"),
                                FV("KERNEL32.dll!InitializeSListHead"),
                                FV("KERNEL32.dll!IsDebuggerPresent"),
                                FV("KERNEL32.dll!IsProcessorFeaturePresent"),
                                FV("KERNEL32.dll!IsValidCodePage"),
                                FV("KERNEL32.dll!IsValidLocale"),
                                FV("KERNEL32.dll!LCMapStringEx"),
                                FV("KERNEL32.dll!LCMapStringW"),
                                FV("KERNEL32.dll!LeaveCriticalSection"),
                                FV("KERNEL32.dll!LoadLibraryExW"),
                                FV("KERNEL32.dll!LoadLibraryW"),
                                FV("KERNEL32.dll!LoadResource"),
                                FV("KERNEL32.dll!LocalAlloc"),
                                FV("KERNEL32.dll!LocalFileTimeToFileTime"),
                                FV("KERNEL32.dll!LocalFree"),
                                FV("KERNEL32.dll!LockResource"),
                                FV("KERNEL32.dll!MapViewOfFile"),
                                FV("KERNEL32.dll!MulDiv"),
                                FV("KERNEL32.dll!MultiByteToWideChar"),
                                FV("KERNEL32.dll!OutputDebugStringW"),
                                FV("KERNEL32.dll!QueryPerformanceCounter"),
                                FV("KERNEL32.dll!RaiseException"),
                                FV("KERNEL32.dll!ReadConsoleInputW"),
                                FV("KERNEL32.dll!ReadConsoleW"),
                                FV("KERNEL32.dll!ReadFile"),
                                FV("KERNEL32.dll!RtlUnwind"),
                                FV("KERNEL32.dll!SetConsoleMode"),
                                FV("KERNEL32.dll!SetEndOfFile"),
                                FV("KERNEL32.dll!SetEnvironmentVariableW"),
                                FV("KERNEL32.dll!SetFileInformationByHandle"),
                                FV("KERNEL32.dll!SetFilePointer"),
                                FV("KERNEL32.dll!SetFilePointerEx"),
                                FV("KERNEL32.dll!SetLastError"),
                                FV("KERNEL32.dll!SetStdHandle"),
                                FV("KERNEL32.dll!SetUnhandledExceptionFilter"),
                                FV("KERNEL32.dll!SizeofResource"),
                                FV("KERNEL32.dll!TerminateProcess"),
                                FV("KERNEL32.dll!TlsAlloc"),
                                FV("KERNEL32.dll!TlsFree"),
                                FV("KERNEL32.dll!TlsGetValue"),
                                FV("KERNEL32.dll!TlsSetValue"),
                                FV("KERNEL32.dll!UnhandledExceptionFilter"),
                                FV("KERNEL32.dll!UnmapViewOfFile"),
                                FV("KERNEL32.dll!WideCharToMultiByte"),
                                FV("KERNEL32.dll!WriteConsoleW"),
                                FV("KERNEL32.dll!WriteFile"),
                                FV("OLEAUT32.dll!12"),
                                FV("OLEAUT32.dll!150"),
                                FV("OLEAUT32.dll!2"),
                                FV("OLEAUT32.dll!6"),
                                FV("OLEAUT32.dll!7"),
                                FV("OLEAUT32.dll!8"),
                                FV("OLEAUT32.dll!9"),
                                FV("SHELL32.dll!ShellExecuteW"),
                                FV("SHLWAPI.dll!176"),
                                FV("USER32.dll!DialogBoxIndirectParamW"),
                                FV("USER32.dll!EndDialog"),
                                FV("USER32.dll!GetDlgItem"),
                                FV("USER32.dll!GetSysColorBrush"),
                                FV("USER32.dll!InflateRect"),
                                FV("USER32.dll!LoadCursorW"),
                                FV("USER32.dll!MessageBoxW"),
                                FV("USER32.dll!SendMessageW"),
                                FV("USER32.dll!SetCursor"),
                                FV("USER32.dll!SetWindowTextW"),
                                FV("VERSION.dll!GetFileVersionInfoSizeW"),
                                FV("VERSION.dll!GetFileVersionInfoW"),
                                FV("VERSION.dll!VerQueryValueW"),
                                FV("WINHTTP.dll!WinHttpCloseHandle"),
                                FV("WINHTTP.dll!WinHttpConnect"),
                                FV("WINHTTP.dll!WinHttpGetProxyForUrl"),
                                FV("WINHTTP.dll!WinHttpOpen"),
                                FV("WINHTTP.dll!WinHttpOpenRequest"),
                                FV("WINHTTP.dll!WinHttpQueryDataAvailable"),
                                FV("WINHTTP.dll!WinHttpQueryHeaders"),
                                FV("WINHTTP.dll!WinHttpReadData"),
                                FV("WINHTTP.dll!WinHttpReceiveResponse"),
                                FV("WINHTTP.dll!WinHttpSendRequest"),
                                FV("WINHTTP.dll!WinHttpSetOption"),
                                FV("WINHTTP.dll!WinHttpWriteData"),
                                FV("WINTRUST.dll!CryptCATClose"),
                                FV("WINTRUST.dll!CryptCATEnumerateAttr"),
                                FV("WINTRUST.dll!CryptCATEnumerateCatAttr"),
                                FV("WINTRUST.dll!CryptCATEnumerateMember"),
                                FV("WINTRUST.dll!CryptCATOpen"),
                                FV("ole32.dll!CLSIDFromString"),
                                FV("ole32.dll!CoCreateInstance"),
                            ],
                            "pe_import_function_hint": [
                                FV("1002", label="KERNEL32.dll!LocalAlloc"),
                                FV("1004", label="KERNEL32.dll!LocalFileTimeToFileTime"),
                                FV("1007", label="KERNEL32.dll!LocalFree"),
                                FV("1019", label="KERNEL32.dll!LockResource"),
                                FV("1022", label="KERNEL32.dll!MapViewOfFile"),
                                FV("1038", label="KERNEL32.dll!MulDiv"),
                                FV("1039", label="KERNEL32.dll!MultiByteToWideChar"),
                                FV("1079", label="KERNEL32.dll!OutputDebugStringW"),
                                FV("1133", label="KERNEL32.dll!QueryPerformanceCounter"),
                                FV("1155", label="KERNEL32.dll!RaiseException"),
                                FV("1163", label="KERNEL32.dll!ReadConsoleInputW"),
                                FV("1169", label="KERNEL32.dll!ReadConsoleW"),
                                FV("1172", label="KERNEL32.dll!ReadFile"),
                                FV("12", label="ole32.dll!CLSIDFromString"),
                                FV("1269", label="KERNEL32.dll!RtlUnwind"),
                                FV("1307", label="KERNEL32.dll!SetConsoleMode"),
                                FV("1330", label="KERNEL32.dll!SetEndOfFile"),
                                FV("1334", label="KERNEL32.dll!SetEnvironmentVariableW"),
                                FV("1346", label="KERNEL32.dll!SetFileInformationByHandle"),
                                FV("1348", label="KERNEL32.dll!SetFilePointer"),
                                FV("1349", label="KERNEL32.dll!SetFilePointerEx"),
                                FV("1365", label="KERNEL32.dll!SetLastError"),
                                FV("1392", label="KERNEL32.dll!SetStdHandle"),
                                FV("1428", label="KERNEL32.dll!SetUnhandledExceptionFilter"),
                                FV("1443", label="KERNEL32.dll!SizeofResource"),
                                FV("1460", label="KERNEL32.dll!TerminateProcess"),
                                FV("1478", label="KERNEL32.dll!TlsAlloc"),
                                FV("1479", label="KERNEL32.dll!TlsFree"),
                                FV("148", label="KERNEL32.dll!CloseHandle"),
                                FV("1480", label="KERNEL32.dll!TlsGetValue"),
                                FV("1481", label="KERNEL32.dll!TlsSetValue"),
                                FV("149", label="CRYPT32.dll!CryptFindOIDInfo"),
                                FV("1493", label="KERNEL32.dll!UnhandledExceptionFilter"),
                                FV("1496", label="KERNEL32.dll!UnmapViewOfFile"),
                                FV("1574", label="KERNEL32.dll!WideCharToMultiByte"),
                                FV("1593", label="KERNEL32.dll!WriteConsoleW"),
                                FV("1594", label="KERNEL32.dll!WriteFile"),
                                FV("16", label="VERSION.dll!VerQueryValueW"),
                                FV("170", label="KERNEL32.dll!CompareStringW"),
                                FV("18", label="CRYPT32.dll!CertCloseStore"),
                                FV("184", label="USER32.dll!DialogBoxIndirectParamW"),
                                FV("194", label="ADVAPI32.dll!CryptAcquireContextW"),
                                FV("196", label="ADVAPI32.dll!CryptCreateHash"),
                                FV("199", label="ADVAPI32.dll!CryptDestroyHash"),
                                FV("206", label="KERNEL32.dll!CreateEventW"),
                                FV("21", label="COMDLG32.dll!PrintDlgW"),
                                FV("210", label="CRYPT32.dll!CryptSIPLoad"),
                                FV("210", label="KERNEL32.dll!CreateFileA"),
                                FV("213", label="ADVAPI32.dll!CryptGetHashParam"),
                                FV("215", label="CRYPT32.dll!CryptSIPRetrieveSubjectGuidForCatalogFile"),
                                FV("215", label="KERNEL32.dll!CreateFileMappingW"),
                                FV("217", label="ADVAPI32.dll!CryptHashData"),
                                FV("218", label="KERNEL32.dll!CreateFileW"),
                                FV("220", label="ADVAPI32.dll!CryptReleaseContext"),
                                FV("242", label="USER32.dll!EndDialog"),
                                FV("25", label="CRYPT32.dll!CertCreateCTLContext"),
                                FV("261", label="ADVAPI32.dll!EqualSid"),
                                FV("27", label="WINTRUST.dll!CryptCATClose"),
                                FV("28", label="WINTRUST.dll!CryptCATEnumerateAttr"),
                                FV("283", label="KERNEL32.dll!DecodePointer"),
                                FV("287", label="ADVAPI32.dll!FreeSid"),
                                FV("29", label="WINTRUST.dll!CryptCATEnumerateCatAttr"),
                                FV("290", label="KERNEL32.dll!DeleteCriticalSection"),
                                FV("295", label="KERNEL32.dll!DeleteFileW"),
                                FV("30", label="WINTRUST.dll!CryptCATEnumerateMember"),
                                FV("312", label="KERNEL32.dll!DosDateTimeToFileTime"),
                                FV("32", label="ADVAPI32.dll!AllocateAndInitializeSid"),
                                FV("321", label="KERNEL32.dll!EncodePointer"),
                                FV("325", label="KERNEL32.dll!EnterCriticalSection"),
                                FV("332", label="USER32.dll!GetDlgItem"),
                                FV("347", label="ADVAPI32.dll!GetTokenInformation"),
                                FV("35", label="WINHTTP.dll!WinHttpGetProxyForUrl"),
                                FV("36", label="WINTRUST.dll!CryptCATOpen"),
                                FV("360", label="KERNEL32.dll!EnumSystemLocalesW"),
                                FV("37", label="CRYPT32.dll!CertDuplicateCertificateContext"),
                                FV("370", label="KERNEL32.dll!ExitProcess"),
                                FV("373", label="KERNEL32.dll!ExpandEnvironmentStringsA"),
                                FV("381", label="KERNEL32.dll!FileTimeToLocalFileTime"),
                                FV("382", label="KERNEL32.dll!FileTimeToSystemTime"),
                                FV("393", label="KERNEL32.dll!FindClose"),
                                FV("396", label="GDI32.dll!DeleteDC"),
                                FV("399", label="KERNEL32.dll!FindFirstFileExW"),
                                FV("4", label="CRYPT32.dll!CertAddCertificateContextToStore"),
                                FV("40", label="ole32.dll!CoCreateInstance"),
                                FV("404", label="KERNEL32.dll!FindFirstFileW"),
                                FV("409", label="GDI32.dll!EndDoc"),
                                FV("412", label="GDI32.dll!EndPage"),
                                FV("416", label="KERNEL32.dll!FindNextFileW"),
                                FV("426", label="KERNEL32.dll!FindResourceW"),
                                FV("432", label="SHELL32.dll!ShellExecuteW"),
                                FV("435", label="KERNEL32.dll!FlushFileBuffers"),
                                FV("44", label="CRYPT32.dll!CertEnumCertificatesInStore"),
                                FV("443", label="KERNEL32.dll!FormatMessageW"),
                                FV("446", label="KERNEL32.dll!FreeEnvironmentStringsW"),
                                FV("447", label="KERNEL32.dll!FreeLibrary"),
                                FV("45", label="WINHTTP.dll!WinHttpOpen"),
                                FV("451", label="KERNEL32.dll!FreeResource"),
                                FV("452", label="USER32.dll!GetSysColorBrush"),
                                FV("454", label="KERNEL32.dll!GetACP"),
                                FV("46", label="WINHTTP.dll!WinHttpOpenRequest"),
                                FV("469", label="KERNEL32.dll!GetCPInfo"),
                                FV("49", label="GDI32.dll!CreateCompatibleDC"),
                                FV("490", label="KERNEL32.dll!GetCommandLineA"),
                                FV("491", label="KERNEL32.dll!GetCommandLineW"),
                                FV("51", label="WINHTTP.dll!WinHttpQueryDataAvailable"),
                                FV("510", label="KERNEL32.dll!GetConsoleCP"),
                                FV("52", label="WINHTTP.dll!WinHttpQueryHeaders"),
                                FV("520", label="USER32.dll!InflateRect"),
                                FV("523", label="ADVAPI32.dll!OpenProcessToken"),
                                FV("528", label="KERNEL32.dll!GetConsoleMode"),
                                FV("532", label="KERNEL32.dll!GetConsoleOutputCP"),
                                FV("548", label="KERNEL32.dll!GetCurrentDirectoryA"),
                                FV("549", label="KERNEL32.dll!GetCurrentDirectoryW"),
                                FV("55", label="WINHTTP.dll!WinHttpReadData"),
                                FV("556", label="KERNEL32.dll!GetCurrentProcess"),
                                FV("557", label="KERNEL32.dll!GetCurrentProcessId"),
                                FV("561", label="KERNEL32.dll!GetCurrentThreadId"),
                                FV("566", label="KERNEL32.dll!GetDateFormatW"),
                                FV("588", label="KERNEL32.dll!GetEnvironmentStringsW"),
                                FV("59", label="WINHTTP.dll!WinHttpReceiveResponse"),
                                FV("593", label="ADVAPI32.dll!RegCloseKey"),
                                FV("597", label="USER32.dll!LoadCursorW"),
                                FV("602", label="ADVAPI32.dll!RegCreateKeyExW"),
                                FV("602", label="KERNEL32.dll!GetFileAttributesW"),
                                FV("604", label="KERNEL32.dll!GetFileInformationByHandle"),
                                FV("605", label="ADVAPI32.dll!RegCreateKeyW"),
                                FV("608", label="KERNEL32.dll!GetFileSize"),
                                FV("609", label="KERNEL32.dll!GetFileSizeEx"),
                                FV("61", label="CRYPT32.dll!CertFreeCertificateChain"),
                                FV("611", label="KERNEL32.dll!GetFileType"),
                                FV("617", label="ADVAPI32.dll!RegDeleteValueW"),
                                FV("622", label="KERNEL32.dll!GetFullPathNameW"),
                                FV("625", label="ADVAPI32.dll!RegEnumKeyW"),
                                FV("63", label="WINHTTP.dll!WinHttpSendRequest"),
                                FV("631", label="KERNEL32.dll!GetLastError"),
                                FV("635", label="KERNEL32.dll!GetLocaleInfoW"),
                                FV("64", label="CRYPT32.dll!CertFreeCertificateContext"),
                                FV("642", label="ADVAPI32.dll!RegOpenKeyExW"),
                                FV("645", label="ADVAPI32.dll!RegOpenKeyW"),
                                FV("647", label="USER32.dll!MessageBoxW"),
                                FV("651", label="GDI32.dll!GetDeviceCaps"),
                                FV("651", label="KERNEL32.dll!GetModuleFileNameW"),
                                FV("654", label="KERNEL32.dll!GetModuleHandleExW"),
                                FV("655", label="ADVAPI32.dll!RegQueryValueExW"),
                                FV("655", label="KERNEL32.dll!GetModuleHandleW"),
                                FV("66", label="WINHTTP.dll!WinHttpSetOption"),
                                FV("671", label="ADVAPI32.dll!RegSetValueExW"),
                                FV("687", label="KERNEL32.dll!GetOEMCP"),
                                FV("69", label="CRYPT32.dll!CertGetCertificateChain"),
                                FV("7", label="VERSION.dll!GetFileVersionInfoSizeW"),
                                FV("70", label="CRYPT32.dll!CertGetCertificateContextProperty"),
                                FV("710", label="KERNEL32.dll!GetProcAddress"),
                                FV("717", label="KERNEL32.dll!GetProcessHeap"),
                                FV("746", label="KERNEL32.dll!GetStartupInfoW"),
                                FV("748", label="KERNEL32.dll!GetStdHandle"),
                                FV("75", label="CRYPT32.dll!CertGetNameStringW"),
                                FV("753", label="KERNEL32.dll!GetStringTypeW"),
                                FV("771", label="KERNEL32.dll!GetSystemTimeAsFileTime"),
                                FV("78", label="CRYPT32.dll!CertGetStoreProperty"),
                                FV("791", label="USER32.dll!SendMessageW"),
                                FV("8", label="VERSION.dll!GetFileVersionInfoW"),
                                FV("8", label="WINHTTP.dll!WinHttpCloseHandle"),
                                FV("80", label="CRYPT32.dll!CertGetValidUsages"),
                                FV("80", label="WINHTTP.dll!WinHttpWriteData"),
                                FV("806", label="USER32.dll!SetCursor"),
                                FV("810", label="KERNEL32.dll!GetTimeFormatW"),
                                FV("816", label="KERNEL32.dll!GetUserDefaultLCID"),
                                FV("823", label="KERNEL32.dll!GetVersion"),
                                FV("825", label="KERNEL32.dll!GetVersionExW"),
                                FV("867", label="KERNEL32.dll!HeapAlloc"),
                                FV("871", label="KERNEL32.dll!HeapFree"),
                                FV("874", label="KERNEL32.dll!HeapReAlloc"),
                                FV("876", label="KERNEL32.dll!HeapSize"),
                                FV("89", label="CRYPT32.dll!CertOpenStore"),
                                FV("893", label="KERNEL32.dll!InitializeCriticalSectionAndSpinCount"),
                                FV("894", label="KERNEL32.dll!InitializeCriticalSectionEx"),
                                FV("895", label="USER32.dll!SetWindowTextW"),
                                FV("897", label="KERNEL32.dll!InitializeSListHead"),
                                FV("9", label="WINHTTP.dll!WinHttpConnect"),
                                FV("913", label="GDI32.dll!SetMapMode"),
                                FV("925", label="KERNEL32.dll!IsDebuggerPresent"),
                                FV("933", label="KERNEL32.dll!IsProcessorFeaturePresent"),
                                FV("939", label="KERNEL32.dll!IsValidCodePage"),
                                FV("941", label="GDI32.dll!StartDocW"),
                                FV("941", label="KERNEL32.dll!IsValidLocale"),
                                FV("943", label="GDI32.dll!StartPage"),
                                FV("976", label="KERNEL32.dll!LCMapStringEx"),
                                FV("977", label="KERNEL32.dll!LCMapStringW"),
                                FV("989", label="KERNEL32.dll!LeaveCriticalSection"),
                                FV("995", label="KERNEL32.dll!LoadLibraryExW"),
                                FV("996", label="KERNEL32.dll!LoadLibraryW"),
                                FV("999", label="KERNEL32.dll!LoadResource"),
                            ],
                            "pe_import_function_ordinal": [
                                FV("12", label="OLEAUT32.dll"),
                                FV("150", label="OLEAUT32.dll"),
                                FV("176", label="SHLWAPI.dll"),
                                FV("2", label="OLEAUT32.dll"),
                                FV("20", label="Cabinet.dll"),
                                FV("22", label="Cabinet.dll"),
                                FV("23", label="Cabinet.dll"),
                                FV("6", label="OLEAUT32.dll"),
                                FV("7", label="OLEAUT32.dll"),
                                FV("8", label="OLEAUT32.dll"),
                                FV("9", label="OLEAUT32.dll"),
                            ],
                            "pe_import_hash": [FV("b92687042a1801c2437d45a8eff471c9")],
                            "pe_import_hash_sorted": [FV("b2865d99eeaa36e5491d4014becc8edb")],
                            "pe_import_module": [
                                FV("ADVAPI32.dll"),
                                FV("COMDLG32.dll"),
                                FV("CRYPT32.dll"),
                                FV("Cabinet.dll"),
                                FV("GDI32.dll"),
                                FV("KERNEL32.dll"),
                                FV("OLEAUT32.dll"),
                                FV("SHELL32.dll"),
                                FV("SHLWAPI.dll"),
                                FV("USER32.dll"),
                                FV("VERSION.dll"),
                                FV("WINHTTP.dll"),
                                FV("WINTRUST.dll"),
                                FV("ole32.dll"),
                            ],
                            "pe_import_module_count": [FV("14")],
                            "pe_init_data_size": [FV("170496")],
                            "pe_linker_version": [FV("14.32")],
                            "pe_loader_flags": [FV("0")],
                            "pe_machine": [FV("I386")],
                            "pe_num_rva_and_sizes": [FV("16")],
                            "pe_os_version": [FV("6.0")],
                            "pe_overlay_hash": [FV("255cd35385a15007ee2d59c44d387f3d")],
                            "pe_overlay_size": [FV("10144")],
                            "pe_resource": [
                                FV("c6856898b42d40bd117b74e7300b1ea523f5ada29f90f904853df7b20a45005d"),
                                FV("e8467c5ad34c385b9ebb3e95a410d07f954ca570a474b42247868fa4d8be51d1"),
                            ],
                            "pe_resource_language": [FV("ENGLISH US")],
                            "pe_resource_name": [
                                FV("1", label="c6856898b42d40bd117b74e7300b1ea523f5ada29f90f904853df7b20a45005d"),
                                FV("1", label="e8467c5ad34c385b9ebb3e95a410d07f954ca570a474b42247868fa4d8be51d1"),
                            ],
                            "pe_resource_size": [
                                FV("1663", label="c6856898b42d40bd117b74e7300b1ea523f5ada29f90f904853df7b20a45005d"),
                                FV("840", label="e8467c5ad34c385b9ebb3e95a410d07f954ca570a474b42247868fa4d8be51d1"),
                            ],
                            "pe_resource_type": [
                                FV(
                                    "RT_MANIFEST",
                                    label="c6856898b42d40bd117b74e7300b1ea523f5ada29f90f904853df7b20a45005d",
                                ),
                                FV(
                                    "RT_VERSION",
                                    label="e8467c5ad34c385b9ebb3e95a410d07f954ca570a474b42247868fa4d8be51d1",
                                ),
                            ],
                            "pe_section": [
                                FV(".data", offset=397824, size=19456),
                                FV(".rdata", offset=273408, size=124416),
                                FV(".reloc", offset=420352, size=15360),
                                FV(".rsrc", offset=417280, size=3072),
                                FV(".text", offset=1024, size=272384),
                            ],
                            "pe_section_alignment": [FV("4096")],
                            "pe_section_characteristics": [
                                FV("CNT_CODE", label=".text"),
                                FV("CNT_INITIALIZED_DATA", label=".data"),
                                FV("CNT_INITIALIZED_DATA", label=".rdata"),
                                FV("CNT_INITIALIZED_DATA", label=".reloc"),
                                FV("CNT_INITIALIZED_DATA", label=".rsrc"),
                                FV("MEM_DISCARDABLE", label=".reloc"),
                                FV("MEM_EXECUTE", label=".text"),
                                FV("MEM_READ", label=".data"),
                                FV("MEM_READ", label=".rdata"),
                                FV("MEM_READ", label=".reloc"),
                                FV("MEM_READ", label=".rsrc"),
                                FV("MEM_READ", label=".text"),
                                FV("MEM_WRITE", label=".data"),
                            ],
                            "pe_section_count": [FV("5")],
                            "pe_section_hash": [
                                FV("1e48702fcb492784044dcee4491f3302", label=".text"),
                                FV("26aa79cfb5c8b790dd6953a228966cc3", label=".rdata"),
                                FV("97d87139dc0fc1415b4396013310220e", label=".data"),
                                FV("b2e9cb89e386b8daa73be2e30981946c", label=".rsrc"),
                                FV("f0270a7bbfa76abfa0a4855fa2f8a35b", label=".reloc"),
                            ],
                            "pe_section_line_nums_address": [
                                FV("0", label=".data"),
                                FV("0", label=".rdata"),
                                FV("0", label=".reloc"),
                                FV("0", label=".rsrc"),
                                FV("0", label=".text"),
                            ],
                            "pe_section_line_nums_count": [
                                FV("0", label=".data"),
                                FV("0", label=".rdata"),
                                FV("0", label=".reloc"),
                                FV("0", label=".rsrc"),
                                FV("0", label=".text"),
                            ],
                            "pe_section_raw_address": [
                                FV("1024", label=".text"),
                                FV("273408", label=".rdata"),
                                FV("397824", label=".data"),
                                FV("417280", label=".rsrc"),
                                FV("420352", label=".reloc"),
                            ],
                            "pe_section_raw_hash": [
                                FV("67de79f5b31005e1078a7a67511ba62d", label=".rsrc"),
                                FV("7bc3864866deb499bdfb589de36d68fe", label=".reloc"),
                                FV("7bda5925ac1306c2e1b9b352fa2f5af2", label=".rdata"),
                                FV("97d87139dc0fc1415b4396013310220e", label=".data"),
                                FV("b20d64b4cf1e0330f69a29a21519af60", label=".text"),
                            ],
                            "pe_section_raw_size": [
                                FV("124416", label=".rdata"),
                                FV("15360", label=".reloc"),
                                FV("19456", label=".data"),
                                FV("272384", label=".text"),
                                FV("3072", label=".rsrc"),
                            ],
                            "pe_section_relocs_address": [
                                FV("0", label=".data"),
                                FV("0", label=".rdata"),
                                FV("0", label=".reloc"),
                                FV("0", label=".rsrc"),
                                FV("0", label=".text"),
                            ],
                            "pe_section_relocs_count": [
                                FV("0", label=".data"),
                                FV("0", label=".rdata"),
                                FV("0", label=".reloc"),
                                FV("0", label=".rsrc"),
                                FV("0", label=".text"),
                            ],
                            "pe_section_virtual_address": [
                                FV("278528", label=".rdata"),
                                FV("405504", label=".data"),
                                FV("4096", label=".text"),
                                FV("434176", label=".rsrc"),
                                FV("438272", label=".reloc"),
                            ],
                            "pe_section_virtual_size": [
                                FV("124350", label=".rdata"),
                                FV("14948", label=".reloc"),
                                FV("2664", label=".rsrc"),
                                FV("272342", label=".text"),
                                FV("27564", label=".data"),
                            ],
                            "pe_stack_commit_size": [FV("4096")],
                            "pe_stack_reserve_size": [FV("1048576")],
                            "pe_subsystem": [FV("WINDOWS_CUI")],
                            "pe_subsystem_version": [FV("6.0")],
                            "pe_uninit_data_size": [FV("0")],
                            "pe_win32_version": [FV("0")],
                            "signature_counter_signer_issuer": [
                                FV(
                                    "C=US, ST=Washington, L=Redmond, O=Microsoft Corporation, CN=Microsoft Time-Stamp PCA 2010"
                                )
                            ],
                            "signature_counter_signer_name": [
                                FV(
                                    "C=US, ST=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft Operations Puerto Rico, OU=Thales TSS ESN:32BD-E3D5-3B1D, CN=Microsoft Time-Stamp Service"
                                )
                            ],
                            "signature_counter_signer_serial": [
                                FV("33:00:00:01:ad:fc:df:4d:58:e3:5d:32:e9:00:01:00:00:01:ad")
                            ],
                            "signature_counter_signer_valid_from": [FV("2022-03-02T18:51:36+00:00")],
                            "signature_counter_signer_valid_to": [FV("2023-05-11T18:51:36+00:00")],
                            "signature_more_info": [FV("https://www.sysinternals.com")],
                            "signature_program_name": [FV("Sigcheck")],
                            "signature_signer_issuer": [
                                FV(
                                    "C=US, ST=Washington, L=Redmond, O=Microsoft Corporation, CN=Microsoft Code Signing PCA 2011"
                                )
                            ],
                            "signature_signer_name": [
                                FV("C=US, ST=Washington, L=Redmond, O=Microsoft Corporation, CN=Microsoft Corporation")
                            ],
                            "signature_signer_serial": [
                                FV("33:00:00:02:52:8b:33:aa:f8:95:f3:39:db:00:00:00:00:02:52")
                            ],
                            "signature_signer_valid_from": [FV("2021-09-02T18:32:59+00:00")],
                            "signature_signer_valid_to": [FV("2022-09-01T18:32:59+00:00")],
                            "signature_verification": [FV("OK")],
                            "tag": [FV("pe_has_overlay")],
                        },
                    ),
                    Event(
                        sha256="68569b3e94f6a2510c9f11717520f04308c5368ff0414505568cbd44bcc6c5f5",
                        parent=EventParent(sha256="4fe9a2bd4b160a5352333d00d0b0c10f13685af7acdb48e9e9d0c3877a19eed4"),
                        relationship={"action": "extracted", "type": "overlay", "offset": "0x6a600"},
                        data=[
                            EventData(
                                hash="68569b3e94f6a2510c9f11717520f04308c5368ff0414505568cbd44bcc6c5f5",
                                label="content",
                            )
                        ],
                        features={"tag": [FV("pe_overlay")]},
                    ),
                    Event(
                        sha256="c9feafa7b52bd692c0852c4e38f6ce700c09f95ecd363182f224529ef7f159c1",
                        parent=EventParent(sha256="4fe9a2bd4b160a5352333d00d0b0c10f13685af7acdb48e9e9d0c3877a19eed4"),
                        relationship={"action": "extracted", "type": "without overlay"},
                        data=[
                            EventData(
                                hash="c9feafa7b52bd692c0852c4e38f6ce700c09f95ecd363182f224529ef7f159c1",
                                label="content",
                            )
                        ],
                        features={"tag": [FV("pe_parent_has_overlay")]},
                    ),
                    Event(
                        sha256="e8467c5ad34c385b9ebb3e95a410d07f954ca570a474b42247868fa4d8be51d1",
                        parent=EventParent(sha256="4fe9a2bd4b160a5352333d00d0b0c10f13685af7acdb48e9e9d0c3877a19eed4"),
                        relationship={"action": "extracted", "type": "resource", "name": "1", "restype": "RT_VERSION"},
                        data=[
                            EventData(
                                hash="e8467c5ad34c385b9ebb3e95a410d07f954ca570a474b42247868fa4d8be51d1",
                                label="content",
                            )
                        ],
                        features={"tag": [FV("pe_resource")]},
                    ),
                    Event(
                        sha256="c6856898b42d40bd117b74e7300b1ea523f5ada29f90f904853df7b20a45005d",
                        parent=EventParent(sha256="4fe9a2bd4b160a5352333d00d0b0c10f13685af7acdb48e9e9d0c3877a19eed4"),
                        relationship={
                            "action": "extracted",
                            "type": "resource",
                            "name": "1",
                            "restype": "RT_MANIFEST",
                        },
                        data=[
                            EventData(
                                hash="c6856898b42d40bd117b74e7300b1ea523f5ada29f90f904853df7b20a45005d",
                                label="content",
                            )
                        ],
                        features={"tag": [FV("pe_resource")]},
                    ),
                ],
                data={
                    "68569b3e94f6a2510c9f11717520f04308c5368ff0414505568cbd44bcc6c5f5": b"",
                    "c9feafa7b52bd692c0852c4e38f6ce700c09f95ecd363182f224529ef7f159c1": b"",
                    "e8467c5ad34c385b9ebb3e95a410d07f954ca570a474b42247868fa4d8be51d1": b"",
                    "c6856898b42d40bd117b74e7300b1ea523f5ada29f90f904853df7b20a45005d": b"",
                },
            ),
        )

    def test_lief_pe_certificate_extra_info_empty(self):
        """Sigcheck executable for extracting certificate values where the extra info is empty."""
        result = self.do_execution(
            data_in=[
                (
                    DataLabel.CONTENT,
                    self.load_test_file_bytes(
                        "12d3544622b9005118bce74e5ca4ef71ce61a69e60d1c7327d4f472f72043d2e",
                        "Benign Windows 32DLL no extra information in signed certificate.",
                    ),
                )
            ]
        )
        self.assertJobResult(
            result,
            JobResult(
                state=State(State.Label.COMPLETED),
                events=[
                    Event(
                        sha256="12d3544622b9005118bce74e5ca4ef71ce61a69e60d1c7327d4f472f72043d2e",
                        features={
                            "authentihash": [FV("945c42c1a0f660ec0e224bfd6dda620001b2dc063abb75becedb6c7b81100a78")],
                            "pe_characteristics": [
                                FV("DLL"),
                                FV("EXECUTABLE_IMAGE"),
                                FV("LINE_NUMS_STRIPPED"),
                                FV("LOCAL_SYMS_STRIPPED"),
                                FV("NEED_32BIT_MACHINE"),
                            ],
                            "pe_checksum": [FV("20186")],
                            "pe_code_base": [FV("4096")],
                            "pe_code_size": [FV("5120")],
                            "pe_compile_time": [FV("2006-07-28T07:57:11")],
                            "pe_data_base": [FV("12288")],
                            "pe_dos_stub": [
                                FV(
                                    "Dh+6DgC0Cc0huAFMzSFUaGlzIHByb2dyYW0gY2Fubm90IGJlIHJ1biBpbiBET1MgbW9kZS4NDQokAAAAAAAAAA=="
                                )
                            ],
                            "pe_entry_point": [FV("8032")],
                            "pe_export": [FV("Update.dll")],
                            "pe_export_base": [FV("1")],
                            "pe_export_characteristics": [FV("00000000")],
                            "pe_export_count": [FV("9")],
                            "pe_export_function": [
                                FV("??0CUpdate@@QAA@XZ"),
                                FV("??4CUpdate@@QAAAAV0@ABV0@@Z"),
                                FV("?StartupProccess@CUpdate@@CAKPAG@Z"),
                                FV("?StopProcess@CUpdate@@CAKXZ"),
                                FV("?TerminateRavProcess@CUpdate@@CAKXZ"),
                                FV("?Update@CUpdate@@SAHXZ"),
                                FV("?UpdateFile@CUpdate@@CAHPAG0@Z"),
                                FV("?UpdateProc@CUpdate@@CAHXZ"),
                                FV("?UpdateVerUpdateTime@CUpdate@@CAHAAVCRsConf@@@Z"),
                            ],
                            "pe_export_function_address": [
                                FV("5880", label="??4CUpdate@@QAAAAV0@ABV0@@Z"),
                                FV("6024", label="??0CUpdate@@QAA@XZ"),
                                FV("6028", label="?TerminateRavProcess@CUpdate@@CAKXZ"),
                                FV("6432", label="?UpdateVerUpdateTime@CUpdate@@CAHAAVCRsConf@@@Z"),
                                FV("6832", label="?StopProcess@CUpdate@@CAKXZ"),
                                FV("6836", label="?UpdateFile@CUpdate@@CAHPAG0@Z"),
                                FV("6844", label="?StartupProccess@CUpdate@@CAKPAG@Z"),
                                FV("6928", label="?UpdateProc@CUpdate@@CAHXZ"),
                                FV("7596", label="?Update@CUpdate@@SAHXZ"),
                            ],
                            "pe_export_time": [FV("2006-07-28T07:57:11")],
                            "pe_export_version": [FV("0.0")],
                            "pe_file_alignment": [FV("512")],
                            "pe_header_size": [FV("1024")],
                            "pe_heap_commit_size": [FV("4096")],
                            "pe_heap_reserve_size": [FV("1048576")],
                            "pe_image_base": [FV("1048576")],
                            "pe_image_size": [FV("28672")],
                            "pe_image_version": [FV("0.0")],
                            "pe_import_function": [
                                FV("CloseToolhelp32Snapshot", label="toolhelp.dll"),
                                FV("CreateToolhelp32Snapshot", label="toolhelp.dll"),
                                FV("Process32First", label="toolhelp.dll"),
                                FV("Process32Next", label="toolhelp.dll"),
                            ],
                            "pe_import_function_count": [FV("36", label="COREDLL.dll"), FV("4", label="toolhelp.dll")],
                            "pe_import_function_fullname": [
                                FV("COREDLL.dll!1044"),
                                FV("COREDLL.dll!1047"),
                                FV("COREDLL.dll!1068"),
                                FV("COREDLL.dll!1092"),
                                FV("COREDLL.dll!1094"),
                                FV("COREDLL.dll!1095"),
                                FV("COREDLL.dll!1097"),
                                FV("COREDLL.dll!1108"),
                                FV("COREDLL.dll!1110"),
                                FV("COREDLL.dll!1118"),
                                FV("COREDLL.dll!1120"),
                                FV("COREDLL.dll!1121"),
                                FV("COREDLL.dll!1122"),
                                FV("COREDLL.dll!1125"),
                                FV("COREDLL.dll!1126"),
                                FV("COREDLL.dll!1130"),
                                FV("COREDLL.dll!1131"),
                                FV("COREDLL.dll!1145"),
                                FV("COREDLL.dll!164"),
                                FV("COREDLL.dll!196"),
                                FV("COREDLL.dll!23"),
                                FV("COREDLL.dll!230"),
                                FV("COREDLL.dll!33"),
                                FV("COREDLL.dll!34"),
                                FV("COREDLL.dll!35"),
                                FV("COREDLL.dll!36"),
                                FV("COREDLL.dll!455"),
                                FV("COREDLL.dll!461"),
                                FV("COREDLL.dll!464"),
                                FV("COREDLL.dll!493"),
                                FV("COREDLL.dll!509"),
                                FV("COREDLL.dll!516"),
                                FV("COREDLL.dll!537"),
                                FV("COREDLL.dll!544"),
                                FV("COREDLL.dll!553"),
                                FV("COREDLL.dll!69"),
                                FV("toolhelp.dll!CloseToolhelp32Snapshot"),
                                FV("toolhelp.dll!CreateToolhelp32Snapshot"),
                                FV("toolhelp.dll!Process32First"),
                                FV("toolhelp.dll!Process32Next"),
                            ],
                            "pe_import_function_hint": [
                                FV("0", label="toolhelp.dll!CloseToolhelp32Snapshot"),
                                FV("1", label="toolhelp.dll!CreateToolhelp32Snapshot"),
                                FV("10", label="toolhelp.dll!Process32Next"),
                                FV("9", label="toolhelp.dll!Process32First"),
                            ],
                            "pe_import_function_ordinal": [
                                FV("1044", label="COREDLL.dll"),
                                FV("1047", label="COREDLL.dll"),
                                FV("1068", label="COREDLL.dll"),
                                FV("1092", label="COREDLL.dll"),
                                FV("1094", label="COREDLL.dll"),
                                FV("1095", label="COREDLL.dll"),
                                FV("1097", label="COREDLL.dll"),
                                FV("1108", label="COREDLL.dll"),
                                FV("1110", label="COREDLL.dll"),
                                FV("1118", label="COREDLL.dll"),
                                FV("1120", label="COREDLL.dll"),
                                FV("1121", label="COREDLL.dll"),
                                FV("1122", label="COREDLL.dll"),
                                FV("1125", label="COREDLL.dll"),
                                FV("1126", label="COREDLL.dll"),
                                FV("1130", label="COREDLL.dll"),
                                FV("1131", label="COREDLL.dll"),
                                FV("1145", label="COREDLL.dll"),
                                FV("164", label="COREDLL.dll"),
                                FV("196", label="COREDLL.dll"),
                                FV("23", label="COREDLL.dll"),
                                FV("230", label="COREDLL.dll"),
                                FV("33", label="COREDLL.dll"),
                                FV("34", label="COREDLL.dll"),
                                FV("35", label="COREDLL.dll"),
                                FV("36", label="COREDLL.dll"),
                                FV("455", label="COREDLL.dll"),
                                FV("461", label="COREDLL.dll"),
                                FV("464", label="COREDLL.dll"),
                                FV("493", label="COREDLL.dll"),
                                FV("509", label="COREDLL.dll"),
                                FV("516", label="COREDLL.dll"),
                                FV("537", label="COREDLL.dll"),
                                FV("544", label="COREDLL.dll"),
                                FV("553", label="COREDLL.dll"),
                                FV("69", label="COREDLL.dll"),
                            ],
                            "pe_import_hash": [FV("a987a68252d7dd726aa66e53a76d47e2")],
                            "pe_import_hash_sorted": [FV("fc1e4de270556dcce4c34a0ade21e187")],
                            "pe_import_module": [FV("COREDLL.dll"), FV("toolhelp.dll")],
                            "pe_import_module_count": [FV("2")],
                            "pe_init_data_size": [FV("4608")],
                            "pe_linker_version": [FV("6.24")],
                            "pe_loader_flags": [FV("0")],
                            "pe_machine": [FV("ARM")],
                            "pe_num_rva_and_sizes": [FV("16")],
                            "pe_os_version": [FV("4.0")],
                            "pe_overlay_hash": [FV("fe36ee2ae1c20b8ac8f8df0fa9a9f4ea")],
                            "pe_overlay_size": [FV("1024")],
                            "pe_section": [
                                FV(".data", offset=7168, size=2048),
                                FV(".pdata", offset=9216, size=512),
                                FV(".rdata", offset=6144, size=1024),
                                FV(".reloc", offset=9728, size=1024),
                                FV(".text", offset=1024, size=5120),
                            ],
                            "pe_section_alignment": [FV("4096")],
                            "pe_section_characteristics": [
                                FV("CNT_CODE", label=".text"),
                                FV("CNT_INITIALIZED_DATA", label=".data"),
                                FV("CNT_INITIALIZED_DATA", label=".pdata"),
                                FV("CNT_INITIALIZED_DATA", label=".rdata"),
                                FV("CNT_INITIALIZED_DATA", label=".reloc"),
                                FV("MEM_DISCARDABLE", label=".reloc"),
                                FV("MEM_EXECUTE", label=".text"),
                                FV("MEM_READ", label=".data"),
                                FV("MEM_READ", label=".pdata"),
                                FV("MEM_READ", label=".rdata"),
                                FV("MEM_READ", label=".reloc"),
                                FV("MEM_READ", label=".text"),
                                FV("MEM_WRITE", label=".data"),
                            ],
                            "pe_section_count": [FV("5")],
                            "pe_section_hash": [
                                FV("1b0aedafa2c4fab127ed967459312e79", label=".pdata"),
                                FV("47ec8ce079a44ee7fa8b7087d9f877ee", label=".rdata"),
                                FV("5fef5be64159e9ee3ec44079be0da3f2", label=".text"),
                                FV("946813568fa81ba797db47741c92a470", label=".data"),
                                FV("b3b3c1427fe489ca14a0f262cdd395aa", label=".reloc"),
                            ],
                            "pe_section_line_nums_address": [
                                FV("0", label=".data"),
                                FV("0", label=".pdata"),
                                FV("0", label=".rdata"),
                                FV("0", label=".reloc"),
                                FV("0", label=".text"),
                            ],
                            "pe_section_line_nums_count": [
                                FV("0", label=".data"),
                                FV("0", label=".pdata"),
                                FV("0", label=".rdata"),
                                FV("0", label=".reloc"),
                                FV("0", label=".text"),
                            ],
                            "pe_section_raw_address": [
                                FV("1024", label=".text"),
                                FV("6144", label=".rdata"),
                                FV("7168", label=".data"),
                                FV("9216", label=".pdata"),
                                FV("9728", label=".reloc"),
                            ],
                            "pe_section_raw_hash": [
                                FV("395028ae78adf01dd4826f898dc5ce84", label=".rdata"),
                                FV("44a45cb57a4324804f6bc7e30ea58e98", label=".text"),
                                FV("60b175512012bac3b1fa2b455c9d35bc", label=".reloc"),
                                FV("685edc7f2aa7326386de487542bb9322", label=".data"),
                                FV("9f7a58664600557b09ceeab2bea1f301", label=".pdata"),
                            ],
                            "pe_section_raw_size": [
                                FV("1024", label=".rdata"),
                                FV("1024", label=".reloc"),
                                FV("2048", label=".data"),
                                FV("512", label=".pdata"),
                                FV("5120", label=".text"),
                            ],
                            "pe_section_relocs_address": [
                                FV("0", label=".data"),
                                FV("0", label=".pdata"),
                                FV("0", label=".rdata"),
                                FV("0", label=".reloc"),
                                FV("0", label=".text"),
                            ],
                            "pe_section_relocs_count": [
                                FV("0", label=".data"),
                                FV("0", label=".pdata"),
                                FV("0", label=".rdata"),
                                FV("0", label=".reloc"),
                                FV("0", label=".text"),
                            ],
                            "pe_section_virtual_address": [
                                FV("12288", label=".rdata"),
                                FV("16384", label=".data"),
                                FV("20480", label=".pdata"),
                                FV("24576", label=".reloc"),
                                FV("4096", label=".text"),
                            ],
                            "pe_section_virtual_size": [
                                FV("1624", label=".data"),
                                FV("440", label=".pdata"),
                                FV("4648", label=".text"),
                                FV("554", label=".reloc"),
                                FV("864", label=".rdata"),
                            ],
                            "pe_stack_commit_size": [FV("4096")],
                            "pe_stack_reserve_size": [FV("65536")],
                            "pe_subsystem": [FV("WINDOWS_CE_GUI")],
                            "pe_subsystem_version": [FV("4.20")],
                            "pe_uninit_data_size": [FV("0")],
                            "pe_win32_version": [FV("0")],
                            "signature_signer_issuer": [FV("CN=Smartphone Privileged Development Root for sd")],
                            "signature_signer_name": [FV("CN=Smartphone Privileged Development Code-Signing for sd")],
                            "signature_signer_serial": [FV("01")],
                            "signature_signer_valid_from": [FV("2005-08-25T07:25:49+00:00")],
                            "signature_signer_valid_to": [FV("2010-08-25T07:25:49+00:00")],
                            "signature_verification": [FV("BAD_SIGNATURE|CERT_EXPIRED")],
                            "tag": [FV("pe_has_overlay")],
                        },
                    ),
                    Event(
                        sha256="0e4523852d8e5e02f2e27dbb41cbdf0004b20f27b6c519c9e6816cfb14dd5f7d",
                        parent=EventParent(sha256="12d3544622b9005118bce74e5ca4ef71ce61a69e60d1c7327d4f472f72043d2e"),
                        relationship={"action": "extracted", "type": "overlay", "offset": "0x2a00"},
                        data=[
                            EventData(
                                hash="0e4523852d8e5e02f2e27dbb41cbdf0004b20f27b6c519c9e6816cfb14dd5f7d",
                                label="content",
                            )
                        ],
                        features={"tag": [FV("pe_overlay")]},
                    ),
                    Event(
                        sha256="662689c0f42ea653b63c97a3296317d6667da780344cb9eae82a708e8ef06f65",
                        parent=EventParent(sha256="12d3544622b9005118bce74e5ca4ef71ce61a69e60d1c7327d4f472f72043d2e"),
                        relationship={"action": "extracted", "type": "without overlay"},
                        data=[
                            EventData(
                                hash="662689c0f42ea653b63c97a3296317d6667da780344cb9eae82a708e8ef06f65",
                                label="content",
                            )
                        ],
                        features={"tag": [FV("pe_parent_has_overlay")]},
                    ),
                ],
                data={
                    "0e4523852d8e5e02f2e27dbb41cbdf0004b20f27b6c519c9e6816cfb14dd5f7d": b"",
                    "662689c0f42ea653b63c97a3296317d6667da780344cb9eae82a708e8ef06f65": b"",
                },
            ),
        )
