"""
LIEF ELF functional test suite.

Functionally test a file compiled with the Gold linker.

"""

from azul_runner import FV, DataLabel, Event, JobResult, State, test_template

from azul_plugin_lief.lief_elf import LiefELF


class TestExecute(test_template.TestPlugin):
    """Parent class of all Lief ELF tests."""

    PLUGIN_TO_TEST = LiefELF

    def test_lief_elf_gold_32(self):
        """Tests on a random gold linked binary for i386."""
        result = self.do_execution(
            data_in=[
                (
                    DataLabel.CONTENT,
                    self.load_test_file_bytes(
                        "cd47a7cfd3a75df39cd533e009439b01e14603dad1b6982a81bbbb3940c8d16a",
                        "Potentially malicious libdecodefilter ELF32",
                    ),
                )
            ]
        )

        self.assertJobResult(
            result,
            JobResult(
                state=State(State.Label.COMPLETED),
                events=[
                    Event(
                        entity_type="binary",
                        entity_id="cd47a7cfd3a75df39cd533e009439b01e14603dad1b6982a81bbbb3940c8d16a",
                        features={
                            "elf_abi_version": [FV(0)],
                            "elf_class": [FV("ELF32")],
                            "elf_data": [FV("2's complement, little endian")],
                            "elf_entrypoint": [FV(0)],
                            "elf_export": [
                                FV("JNI_OnLoad"),
                                FV("_Unwind_Backtrace"),
                                FV("_Unwind_Complete"),
                                FV("_Unwind_DeleteException"),
                                FV("_Unwind_ForcedUnwind"),
                                FV("_Unwind_GetCFA"),
                                FV("_Unwind_GetDataRelBase"),
                                FV("_Unwind_GetLanguageSpecificData"),
                                FV("_Unwind_GetRegionStart"),
                                FV("_Unwind_GetTextRelBase"),
                                FV("_Unwind_RaiseException"),
                                FV("_Unwind_Resume"),
                                FV("_Unwind_Resume_or_Rethrow"),
                                FV("_Unwind_VRS_Get"),
                                FV("_Unwind_VRS_Pop"),
                                FV("_Unwind_VRS_Set"),
                                FV("___Unwind_Backtrace"),
                                FV("___Unwind_ForcedUnwind"),
                                FV("___Unwind_RaiseException"),
                                FV("___Unwind_Resume"),
                                FV("___Unwind_Resume_or_Rethrow"),
                                FV("__addsf3"),
                                FV("__aeabi_fadd"),
                                FV("__aeabi_fdiv"),
                                FV("__aeabi_fmul"),
                                FV("__aeabi_frsub"),
                                FV("__aeabi_fsub"),
                                FV("__aeabi_i2f"),
                                FV("__aeabi_idiv0"),
                                FV("__aeabi_l2f"),
                                FV("__aeabi_ldiv0"),
                                FV("__aeabi_ui2f"),
                                FV("__aeabi_ul2f"),
                                FV("__aeabi_unwind_cpp_pr0"),
                                FV("__aeabi_unwind_cpp_pr1"),
                                FV("__aeabi_unwind_cpp_pr2"),
                                FV("__divsf3"),
                                FV("__floatdisf"),
                                FV("__floatsisf"),
                                FV("__floatundisf"),
                                FV("__floatunsisf"),
                                FV("__gnu_Unwind_Backtrace"),
                                FV("__gnu_Unwind_ForcedUnwind"),
                                FV("__gnu_Unwind_RaiseException"),
                                FV("__gnu_Unwind_Restore_VFP"),
                                FV("__gnu_Unwind_Restore_VFP_D"),
                                FV("__gnu_Unwind_Restore_VFP_D_16_to_31"),
                                FV("__gnu_Unwind_Restore_WMMXC"),
                                FV("__gnu_Unwind_Restore_WMMXD"),
                                FV("__gnu_Unwind_Resume"),
                                FV("__gnu_Unwind_Resume_or_Rethrow"),
                                FV("__gnu_Unwind_Save_VFP"),
                                FV("__gnu_Unwind_Save_VFP_D"),
                                FV("__gnu_Unwind_Save_VFP_D_16_to_31"),
                                FV("__gnu_Unwind_Save_WMMXC"),
                                FV("__gnu_Unwind_Save_WMMXD"),
                                FV("__gnu_unwind_execute"),
                                FV("__gnu_unwind_frame"),
                                FV("__modsi3"),
                                FV("__mulsf3"),
                                FV("__restore_core_regs"),
                                FV("__subsf3"),
                                FV("__umodsi3"),
                                FV("bep_load"),
                                FV("restore_core_regs"),
                                FV("rtld_db_dlactivity"),
                            ],
                            "elf_export_binding": [
                                FV("GLOBAL", label="JNI_OnLoad"),
                                FV("GLOBAL", label="_Unwind_Backtrace"),
                                FV("GLOBAL", label="_Unwind_Complete"),
                                FV("GLOBAL", label="_Unwind_DeleteException"),
                                FV("GLOBAL", label="_Unwind_ForcedUnwind"),
                                FV("GLOBAL", label="_Unwind_GetCFA"),
                                FV("GLOBAL", label="_Unwind_GetDataRelBase"),
                                FV("GLOBAL", label="_Unwind_GetLanguageSpecificData"),
                                FV("GLOBAL", label="_Unwind_GetRegionStart"),
                                FV("GLOBAL", label="_Unwind_GetTextRelBase"),
                                FV("GLOBAL", label="_Unwind_RaiseException"),
                                FV("GLOBAL", label="_Unwind_Resume"),
                                FV("GLOBAL", label="_Unwind_Resume_or_Rethrow"),
                                FV("GLOBAL", label="_Unwind_VRS_Get"),
                                FV("GLOBAL", label="_Unwind_VRS_Pop"),
                                FV("GLOBAL", label="_Unwind_VRS_Set"),
                                FV("GLOBAL", label="___Unwind_Backtrace"),
                                FV("GLOBAL", label="___Unwind_ForcedUnwind"),
                                FV("GLOBAL", label="___Unwind_RaiseException"),
                                FV("GLOBAL", label="___Unwind_Resume"),
                                FV("GLOBAL", label="___Unwind_Resume_or_Rethrow"),
                                FV("GLOBAL", label="__addsf3"),
                                FV("GLOBAL", label="__aeabi_fadd"),
                                FV("GLOBAL", label="__aeabi_fdiv"),
                                FV("GLOBAL", label="__aeabi_fmul"),
                                FV("GLOBAL", label="__aeabi_frsub"),
                                FV("GLOBAL", label="__aeabi_fsub"),
                                FV("GLOBAL", label="__aeabi_i2f"),
                                FV("GLOBAL", label="__aeabi_l2f"),
                                FV("GLOBAL", label="__aeabi_ui2f"),
                                FV("GLOBAL", label="__aeabi_ul2f"),
                                FV("GLOBAL", label="__aeabi_unwind_cpp_pr0"),
                                FV("GLOBAL", label="__divsf3"),
                                FV("GLOBAL", label="__floatdisf"),
                                FV("GLOBAL", label="__floatsisf"),
                                FV("GLOBAL", label="__floatundisf"),
                                FV("GLOBAL", label="__floatunsisf"),
                                FV("GLOBAL", label="__gnu_Unwind_Backtrace"),
                                FV("GLOBAL", label="__gnu_Unwind_ForcedUnwind"),
                                FV("GLOBAL", label="__gnu_Unwind_RaiseException"),
                                FV("GLOBAL", label="__gnu_Unwind_Restore_VFP"),
                                FV("GLOBAL", label="__gnu_Unwind_Restore_VFP_D"),
                                FV("GLOBAL", label="__gnu_Unwind_Restore_VFP_D_16_to_31"),
                                FV("GLOBAL", label="__gnu_Unwind_Restore_WMMXC"),
                                FV("GLOBAL", label="__gnu_Unwind_Restore_WMMXD"),
                                FV("GLOBAL", label="__gnu_Unwind_Resume"),
                                FV("GLOBAL", label="__gnu_Unwind_Resume_or_Rethrow"),
                                FV("GLOBAL", label="__gnu_Unwind_Save_VFP"),
                                FV("GLOBAL", label="__gnu_Unwind_Save_VFP_D"),
                                FV("GLOBAL", label="__gnu_Unwind_Save_VFP_D_16_to_31"),
                                FV("GLOBAL", label="__gnu_Unwind_Save_WMMXC"),
                                FV("GLOBAL", label="__gnu_Unwind_Save_WMMXD"),
                                FV("GLOBAL", label="__gnu_unwind_execute"),
                                FV("GLOBAL", label="__gnu_unwind_frame"),
                                FV("GLOBAL", label="__modsi3"),
                                FV("GLOBAL", label="__mulsf3"),
                                FV("GLOBAL", label="__restore_core_regs"),
                                FV("GLOBAL", label="__subsf3"),
                                FV("GLOBAL", label="__umodsi3"),
                                FV("GLOBAL", label="bep_load"),
                                FV("GLOBAL", label="restore_core_regs"),
                                FV("GLOBAL", label="rtld_db_dlactivity"),
                                FV("WEAK", label="__aeabi_idiv0"),
                                FV("WEAK", label="__aeabi_ldiv0"),
                                FV("WEAK", label="__aeabi_unwind_cpp_pr1"),
                                FV("WEAK", label="__aeabi_unwind_cpp_pr2"),
                            ],
                            "elf_export_size": [
                                FV(0, label="__gnu_Unwind_Restore_VFP"),
                                FV(0, label="__gnu_Unwind_Restore_VFP_D"),
                                FV(0, label="__gnu_Unwind_Restore_VFP_D_16_to_31"),
                                FV(0, label="__gnu_Unwind_Restore_WMMXC"),
                                FV(0, label="__gnu_Unwind_Restore_WMMXD"),
                                FV(0, label="__gnu_Unwind_Save_VFP"),
                                FV(0, label="__gnu_Unwind_Save_VFP_D"),
                                FV(0, label="__gnu_Unwind_Save_VFP_D_16_to_31"),
                                FV(0, label="__gnu_Unwind_Save_WMMXC"),
                                FV(0, label="__gnu_Unwind_Save_WMMXD"),
                                FV(2, label="rtld_db_dlactivity"),
                                FV(4, label="_Unwind_Complete"),
                                FV(8, label="_Unwind_GetCFA"),
                                FV(8, label="_Unwind_GetDataRelBase"),
                                FV(8, label="_Unwind_GetTextRelBase"),
                                FV(8, label="__aeabi_unwind_cpp_pr0"),
                                FV(8, label="__aeabi_unwind_cpp_pr1"),
                                FV(8, label="__aeabi_unwind_cpp_pr2"),
                                FV(16, label="_Unwind_GetRegionStart"),
                                FV(16, label="__aeabi_idiv0"),
                                FV(16, label="__aeabi_ldiv0"),
                                FV(20, label="__restore_core_regs"),
                                FV(20, label="restore_core_regs"),
                                FV(28, label="_Unwind_GetLanguageSpecificData"),
                                FV(28, label="__gnu_Unwind_ForcedUnwind"),
                                FV(32, label="_Unwind_DeleteException"),
                                FV(32, label="__aeabi_i2f"),
                                FV(32, label="__floatsisf"),
                                FV(32, label="__gnu_Unwind_Resume_or_Rethrow"),
                                FV(36, label="_Unwind_Backtrace"),
                                FV(36, label="_Unwind_ForcedUnwind"),
                                FV(36, label="_Unwind_RaiseException"),
                                FV(36, label="_Unwind_Resume"),
                                FV(36, label="_Unwind_Resume_or_Rethrow"),
                                FV(36, label="___Unwind_Backtrace"),
                                FV(36, label="___Unwind_ForcedUnwind"),
                                FV(36, label="___Unwind_RaiseException"),
                                FV(36, label="___Unwind_Resume"),
                                FV(36, label="___Unwind_Resume_or_Rethrow"),
                                FV(40, label="__aeabi_ui2f"),
                                FV(40, label="__floatunsisf"),
                                FV(64, label="__gnu_unwind_frame"),
                                FV(92, label="_Unwind_VRS_Get"),
                                FV(92, label="_Unwind_VRS_Set"),
                                FV(116, label="__gnu_Unwind_Resume"),
                                FV(124, label="__aeabi_l2f"),
                                FV(124, label="__floatdisf"),
                                FV(140, label="__aeabi_ul2f"),
                                FV(140, label="__floatundisf"),
                                FV(164, label="__gnu_Unwind_RaiseException"),
                                FV(172, label="__umodsi3"),
                                FV(196, label="__gnu_Unwind_Backtrace"),
                                FV(200, label="__modsi3"),
                                FV(352, label="__aeabi_fdiv"),
                                FV(352, label="__divsf3"),
                                FV(400, label="__addsf3"),
                                FV(400, label="__aeabi_fadd"),
                                FV(404, label="__aeabi_fsub"),
                                FV(404, label="__subsf3"),
                                FV(408, label="__aeabi_fmul"),
                                FV(408, label="__mulsf3"),
                                FV(412, label="__aeabi_frsub"),
                                FV(856, label="_Unwind_VRS_Pop"),
                                FV(892, label="__gnu_unwind_execute"),
                                FV(5128, label="JNI_OnLoad"),
                                FV(7928, label="bep_load"),
                            ],
                            "elf_export_type": [
                                FV("FUNC", label="JNI_OnLoad"),
                                FV("FUNC", label="_Unwind_Backtrace"),
                                FV("FUNC", label="_Unwind_Complete"),
                                FV("FUNC", label="_Unwind_DeleteException"),
                                FV("FUNC", label="_Unwind_ForcedUnwind"),
                                FV("FUNC", label="_Unwind_GetCFA"),
                                FV("FUNC", label="_Unwind_GetDataRelBase"),
                                FV("FUNC", label="_Unwind_GetLanguageSpecificData"),
                                FV("FUNC", label="_Unwind_GetRegionStart"),
                                FV("FUNC", label="_Unwind_GetTextRelBase"),
                                FV("FUNC", label="_Unwind_RaiseException"),
                                FV("FUNC", label="_Unwind_Resume"),
                                FV("FUNC", label="_Unwind_Resume_or_Rethrow"),
                                FV("FUNC", label="_Unwind_VRS_Get"),
                                FV("FUNC", label="_Unwind_VRS_Pop"),
                                FV("FUNC", label="_Unwind_VRS_Set"),
                                FV("FUNC", label="___Unwind_Backtrace"),
                                FV("FUNC", label="___Unwind_ForcedUnwind"),
                                FV("FUNC", label="___Unwind_RaiseException"),
                                FV("FUNC", label="___Unwind_Resume"),
                                FV("FUNC", label="___Unwind_Resume_or_Rethrow"),
                                FV("FUNC", label="__addsf3"),
                                FV("FUNC", label="__aeabi_fadd"),
                                FV("FUNC", label="__aeabi_fdiv"),
                                FV("FUNC", label="__aeabi_fmul"),
                                FV("FUNC", label="__aeabi_frsub"),
                                FV("FUNC", label="__aeabi_fsub"),
                                FV("FUNC", label="__aeabi_i2f"),
                                FV("FUNC", label="__aeabi_idiv0"),
                                FV("FUNC", label="__aeabi_l2f"),
                                FV("FUNC", label="__aeabi_ldiv0"),
                                FV("FUNC", label="__aeabi_ui2f"),
                                FV("FUNC", label="__aeabi_ul2f"),
                                FV("FUNC", label="__aeabi_unwind_cpp_pr0"),
                                FV("FUNC", label="__aeabi_unwind_cpp_pr1"),
                                FV("FUNC", label="__aeabi_unwind_cpp_pr2"),
                                FV("FUNC", label="__divsf3"),
                                FV("FUNC", label="__floatdisf"),
                                FV("FUNC", label="__floatsisf"),
                                FV("FUNC", label="__floatundisf"),
                                FV("FUNC", label="__floatunsisf"),
                                FV("FUNC", label="__gnu_Unwind_Backtrace"),
                                FV("FUNC", label="__gnu_Unwind_ForcedUnwind"),
                                FV("FUNC", label="__gnu_Unwind_RaiseException"),
                                FV("FUNC", label="__gnu_Unwind_Restore_VFP"),
                                FV("FUNC", label="__gnu_Unwind_Restore_VFP_D"),
                                FV("FUNC", label="__gnu_Unwind_Restore_VFP_D_16_to_31"),
                                FV("FUNC", label="__gnu_Unwind_Restore_WMMXC"),
                                FV("FUNC", label="__gnu_Unwind_Restore_WMMXD"),
                                FV("FUNC", label="__gnu_Unwind_Resume"),
                                FV("FUNC", label="__gnu_Unwind_Resume_or_Rethrow"),
                                FV("FUNC", label="__gnu_Unwind_Save_VFP"),
                                FV("FUNC", label="__gnu_Unwind_Save_VFP_D"),
                                FV("FUNC", label="__gnu_Unwind_Save_VFP_D_16_to_31"),
                                FV("FUNC", label="__gnu_Unwind_Save_WMMXC"),
                                FV("FUNC", label="__gnu_Unwind_Save_WMMXD"),
                                FV("FUNC", label="__gnu_unwind_execute"),
                                FV("FUNC", label="__gnu_unwind_frame"),
                                FV("FUNC", label="__modsi3"),
                                FV("FUNC", label="__mulsf3"),
                                FV("FUNC", label="__restore_core_regs"),
                                FV("FUNC", label="__subsf3"),
                                FV("FUNC", label="__umodsi3"),
                                FV("FUNC", label="bep_load"),
                                FV("FUNC", label="restore_core_regs"),
                                FV("FUNC", label="rtld_db_dlactivity"),
                            ],
                            "elf_export_value": [
                                FV(19545, label="bep_load"),
                                FV(35901, label="JNI_OnLoad"),
                                FV(51789, label="rtld_db_dlactivity"),
                                FV(76040, label="__umodsi3"),
                                FV(76212, label="__modsi3"),
                                FV(76412, label="__aeabi_frsub"),
                                FV(76420, label="__aeabi_fsub"),
                                FV(76420, label="__subsf3"),
                                FV(76424, label="__addsf3"),
                                FV(76424, label="__aeabi_fadd"),
                                FV(76824, label="__aeabi_ui2f"),
                                FV(76824, label="__floatunsisf"),
                                FV(76832, label="__aeabi_i2f"),
                                FV(76832, label="__floatsisf"),
                                FV(76864, label="__aeabi_ul2f"),
                                FV(76864, label="__floatundisf"),
                                FV(76880, label="__aeabi_l2f"),
                                FV(76880, label="__floatdisf"),
                                FV(77004, label="__aeabi_fmul"),
                                FV(77004, label="__mulsf3"),
                                FV(77412, label="__aeabi_fdiv"),
                                FV(77412, label="__divsf3"),
                                FV(77764, label="__aeabi_idiv0"),
                                FV(77764, label="__aeabi_ldiv0"),
                                FV(78860, label="_Unwind_GetCFA"),
                                FV(78868, label="__gnu_Unwind_RaiseException"),
                                FV(79032, label="__gnu_Unwind_ForcedUnwind"),
                                FV(79060, label="__gnu_Unwind_Resume"),
                                FV(79176, label="__gnu_Unwind_Resume_or_Rethrow"),
                                FV(79208, label="_Unwind_Complete"),
                                FV(79212, label="_Unwind_DeleteException"),
                                FV(79244, label="_Unwind_VRS_Get"),
                                FV(79376, label="_Unwind_VRS_Set"),
                                FV(79512, label="__gnu_Unwind_Backtrace"),
                                FV(80720, label="__aeabi_unwind_cpp_pr0"),
                                FV(80728, label="__aeabi_unwind_cpp_pr1"),
                                FV(80736, label="__aeabi_unwind_cpp_pr2"),
                                FV(80744, label="_Unwind_VRS_Pop"),
                                FV(81600, label="__restore_core_regs"),
                                FV(81600, label="restore_core_regs"),
                                FV(81620, label="__gnu_Unwind_Restore_VFP"),
                                FV(81628, label="__gnu_Unwind_Save_VFP"),
                                FV(81636, label="__gnu_Unwind_Restore_VFP_D"),
                                FV(81644, label="__gnu_Unwind_Save_VFP_D"),
                                FV(81652, label="__gnu_Unwind_Restore_VFP_D_16_to_31"),
                                FV(81660, label="__gnu_Unwind_Save_VFP_D_16_to_31"),
                                FV(81668, label="__gnu_Unwind_Restore_WMMXD"),
                                FV(81736, label="__gnu_Unwind_Save_WMMXD"),
                                FV(81804, label="__gnu_Unwind_Restore_WMMXC"),
                                FV(81824, label="__gnu_Unwind_Save_WMMXC"),
                                FV(81844, label="_Unwind_RaiseException"),
                                FV(81844, label="___Unwind_RaiseException"),
                                FV(81880, label="_Unwind_Resume"),
                                FV(81880, label="___Unwind_Resume"),
                                FV(81916, label="_Unwind_Resume_or_Rethrow"),
                                FV(81916, label="___Unwind_Resume_or_Rethrow"),
                                FV(81952, label="_Unwind_ForcedUnwind"),
                                FV(81952, label="___Unwind_ForcedUnwind"),
                                FV(81988, label="_Unwind_Backtrace"),
                                FV(81988, label="___Unwind_Backtrace"),
                                FV(82164, label="__gnu_unwind_execute"),
                                FV(83056, label="__gnu_unwind_frame"),
                                FV(83120, label="_Unwind_GetRegionStart"),
                                FV(83136, label="_Unwind_GetLanguageSpecificData"),
                                FV(83164, label="_Unwind_GetDataRelBase"),
                                FV(83172, label="_Unwind_GetTextRelBase"),
                            ],
                            "elf_export_version": [
                                FV("", label="JNI_OnLoad"),
                                FV("", label="_Unwind_Backtrace"),
                                FV("", label="_Unwind_Complete"),
                                FV("", label="_Unwind_DeleteException"),
                                FV("", label="_Unwind_ForcedUnwind"),
                                FV("", label="_Unwind_GetCFA"),
                                FV("", label="_Unwind_GetDataRelBase"),
                                FV("", label="_Unwind_GetLanguageSpecificData"),
                                FV("", label="_Unwind_GetRegionStart"),
                                FV("", label="_Unwind_GetTextRelBase"),
                                FV("", label="_Unwind_RaiseException"),
                                FV("", label="_Unwind_Resume"),
                                FV("", label="_Unwind_Resume_or_Rethrow"),
                                FV("", label="_Unwind_VRS_Get"),
                                FV("", label="_Unwind_VRS_Pop"),
                                FV("", label="_Unwind_VRS_Set"),
                                FV("", label="___Unwind_Backtrace"),
                                FV("", label="___Unwind_ForcedUnwind"),
                                FV("", label="___Unwind_RaiseException"),
                                FV("", label="___Unwind_Resume"),
                                FV("", label="___Unwind_Resume_or_Rethrow"),
                                FV("", label="__addsf3"),
                                FV("", label="__aeabi_fadd"),
                                FV("", label="__aeabi_fdiv"),
                                FV("", label="__aeabi_fmul"),
                                FV("", label="__aeabi_frsub"),
                                FV("", label="__aeabi_fsub"),
                                FV("", label="__aeabi_i2f"),
                                FV("", label="__aeabi_idiv0"),
                                FV("", label="__aeabi_l2f"),
                                FV("", label="__aeabi_ldiv0"),
                                FV("", label="__aeabi_ui2f"),
                                FV("", label="__aeabi_ul2f"),
                                FV("", label="__aeabi_unwind_cpp_pr0"),
                                FV("", label="__aeabi_unwind_cpp_pr1"),
                                FV("", label="__aeabi_unwind_cpp_pr2"),
                                FV("", label="__divsf3"),
                                FV("", label="__floatdisf"),
                                FV("", label="__floatsisf"),
                                FV("", label="__floatundisf"),
                                FV("", label="__floatunsisf"),
                                FV("", label="__gnu_Unwind_Backtrace"),
                                FV("", label="__gnu_Unwind_ForcedUnwind"),
                                FV("", label="__gnu_Unwind_RaiseException"),
                                FV("", label="__gnu_Unwind_Restore_VFP"),
                                FV("", label="__gnu_Unwind_Restore_VFP_D"),
                                FV("", label="__gnu_Unwind_Restore_VFP_D_16_to_31"),
                                FV("", label="__gnu_Unwind_Restore_WMMXC"),
                                FV("", label="__gnu_Unwind_Restore_WMMXD"),
                                FV("", label="__gnu_Unwind_Resume"),
                                FV("", label="__gnu_Unwind_Resume_or_Rethrow"),
                                FV("", label="__gnu_Unwind_Save_VFP"),
                                FV("", label="__gnu_Unwind_Save_VFP_D"),
                                FV("", label="__gnu_Unwind_Save_VFP_D_16_to_31"),
                                FV("", label="__gnu_Unwind_Save_WMMXC"),
                                FV("", label="__gnu_Unwind_Save_WMMXD"),
                                FV("", label="__gnu_unwind_execute"),
                                FV("", label="__gnu_unwind_frame"),
                                FV("", label="__modsi3"),
                                FV("", label="__mulsf3"),
                                FV("", label="__restore_core_regs"),
                                FV("", label="__subsf3"),
                                FV("", label="__umodsi3"),
                                FV("", label="bep_load"),
                                FV("", label="restore_core_regs"),
                                FV("", label="rtld_db_dlactivity"),
                            ],
                            "elf_export_visibility": [
                                FV("DEFAULT", label="JNI_OnLoad"),
                                FV("DEFAULT", label="_Unwind_Backtrace"),
                                FV("DEFAULT", label="_Unwind_Complete"),
                                FV("DEFAULT", label="_Unwind_DeleteException"),
                                FV("DEFAULT", label="_Unwind_ForcedUnwind"),
                                FV("DEFAULT", label="_Unwind_GetCFA"),
                                FV("DEFAULT", label="_Unwind_GetDataRelBase"),
                                FV("DEFAULT", label="_Unwind_GetLanguageSpecificData"),
                                FV("DEFAULT", label="_Unwind_GetRegionStart"),
                                FV("DEFAULT", label="_Unwind_GetTextRelBase"),
                                FV("DEFAULT", label="_Unwind_RaiseException"),
                                FV("DEFAULT", label="_Unwind_Resume"),
                                FV("DEFAULT", label="_Unwind_Resume_or_Rethrow"),
                                FV("DEFAULT", label="_Unwind_VRS_Get"),
                                FV("DEFAULT", label="_Unwind_VRS_Pop"),
                                FV("DEFAULT", label="_Unwind_VRS_Set"),
                                FV("DEFAULT", label="___Unwind_Backtrace"),
                                FV("DEFAULT", label="___Unwind_ForcedUnwind"),
                                FV("DEFAULT", label="___Unwind_RaiseException"),
                                FV("DEFAULT", label="___Unwind_Resume"),
                                FV("DEFAULT", label="___Unwind_Resume_or_Rethrow"),
                                FV("DEFAULT", label="__addsf3"),
                                FV("DEFAULT", label="__aeabi_fadd"),
                                FV("DEFAULT", label="__aeabi_fdiv"),
                                FV("DEFAULT", label="__aeabi_fmul"),
                                FV("DEFAULT", label="__aeabi_frsub"),
                                FV("DEFAULT", label="__aeabi_fsub"),
                                FV("DEFAULT", label="__aeabi_i2f"),
                                FV("DEFAULT", label="__aeabi_idiv0"),
                                FV("DEFAULT", label="__aeabi_l2f"),
                                FV("DEFAULT", label="__aeabi_ldiv0"),
                                FV("DEFAULT", label="__aeabi_ui2f"),
                                FV("DEFAULT", label="__aeabi_ul2f"),
                                FV("DEFAULT", label="__aeabi_unwind_cpp_pr0"),
                                FV("DEFAULT", label="__aeabi_unwind_cpp_pr1"),
                                FV("DEFAULT", label="__aeabi_unwind_cpp_pr2"),
                                FV("DEFAULT", label="__divsf3"),
                                FV("DEFAULT", label="__floatdisf"),
                                FV("DEFAULT", label="__floatsisf"),
                                FV("DEFAULT", label="__floatundisf"),
                                FV("DEFAULT", label="__floatunsisf"),
                                FV("DEFAULT", label="__gnu_Unwind_Backtrace"),
                                FV("DEFAULT", label="__gnu_Unwind_ForcedUnwind"),
                                FV("DEFAULT", label="__gnu_Unwind_RaiseException"),
                                FV("DEFAULT", label="__gnu_Unwind_Restore_VFP"),
                                FV("DEFAULT", label="__gnu_Unwind_Restore_VFP_D"),
                                FV("DEFAULT", label="__gnu_Unwind_Restore_VFP_D_16_to_31"),
                                FV("DEFAULT", label="__gnu_Unwind_Restore_WMMXC"),
                                FV("DEFAULT", label="__gnu_Unwind_Restore_WMMXD"),
                                FV("DEFAULT", label="__gnu_Unwind_Resume"),
                                FV("DEFAULT", label="__gnu_Unwind_Resume_or_Rethrow"),
                                FV("DEFAULT", label="__gnu_Unwind_Save_VFP"),
                                FV("DEFAULT", label="__gnu_Unwind_Save_VFP_D"),
                                FV("DEFAULT", label="__gnu_Unwind_Save_VFP_D_16_to_31"),
                                FV("DEFAULT", label="__gnu_Unwind_Save_WMMXC"),
                                FV("DEFAULT", label="__gnu_Unwind_Save_WMMXD"),
                                FV("DEFAULT", label="__gnu_unwind_execute"),
                                FV("DEFAULT", label="__gnu_unwind_frame"),
                                FV("DEFAULT", label="__modsi3"),
                                FV("DEFAULT", label="__mulsf3"),
                                FV("DEFAULT", label="__restore_core_regs"),
                                FV("DEFAULT", label="__subsf3"),
                                FV("DEFAULT", label="__umodsi3"),
                                FV("DEFAULT", label="bep_load"),
                                FV("DEFAULT", label="restore_core_regs"),
                                FV("DEFAULT", label="rtld_db_dlactivity"),
                            ],
                            "elf_hdr_version": [FV("1 (current)")],
                            "elf_header_size": [FV(52)],
                            "elf_import": [
                                FV("__aeabi_memcpy"),
                                FV("__aeabi_memset"),
                                FV("__cxa_atexit"),
                                FV("__cxa_finalize"),
                                FV("__errno"),
                                FV("__gnu_Unwind_Find_exidx"),
                                FV("__stack_chk_fail"),
                                FV("__stack_chk_guard"),
                                FV("__system_property_get"),
                                FV("abort"),
                                FV("access"),
                                FV("close"),
                                FV("dlopen"),
                                FV("dlsym"),
                                FV("fclose"),
                                FV("fopen"),
                                FV("fread"),
                                FV("free"),
                                FV("gettimeofday"),
                                FV("malloc"),
                                FV("memcpy"),
                                FV("memset"),
                                FV("mmap"),
                                FV("mprotect"),
                                FV("munmap"),
                                FV("open"),
                                FV("operator delete(void*)"),
                                FV("operator delete[](void*)"),
                                FV("operator new[](unsigned int)"),
                                FV("raise"),
                                FV("read"),
                                FV("snprintf"),
                                FV("sprintf"),
                                FV("sscanf"),
                                FV("strchr"),
                                FV("strcmp"),
                                FV("strcpy"),
                                FV("strdup"),
                                FV("strerror"),
                                FV("strlcpy"),
                                FV("strlen"),
                                FV("strncmp"),
                                FV("strncpy"),
                                FV("strrchr"),
                                FV("strstr"),
                                FV("uncompress"),
                            ],
                            "elf_import_binding": [
                                FV("GLOBAL", label="_ZdaPv"),
                                FV("GLOBAL", label="_ZdlPv"),
                                FV("GLOBAL", label="_Znaj"),
                                FV("GLOBAL", label="__aeabi_memcpy"),
                                FV("GLOBAL", label="__aeabi_memset"),
                                FV("GLOBAL", label="__cxa_atexit"),
                                FV("GLOBAL", label="__cxa_finalize"),
                                FV("GLOBAL", label="__errno"),
                                FV("GLOBAL", label="__stack_chk_fail"),
                                FV("GLOBAL", label="__stack_chk_guard"),
                                FV("GLOBAL", label="__system_property_get"),
                                FV("GLOBAL", label="abort"),
                                FV("GLOBAL", label="access"),
                                FV("GLOBAL", label="close"),
                                FV("GLOBAL", label="dlopen"),
                                FV("GLOBAL", label="dlsym"),
                                FV("GLOBAL", label="fclose"),
                                FV("GLOBAL", label="fopen"),
                                FV("GLOBAL", label="fread"),
                                FV("GLOBAL", label="free"),
                                FV("GLOBAL", label="gettimeofday"),
                                FV("GLOBAL", label="malloc"),
                                FV("GLOBAL", label="memcpy"),
                                FV("GLOBAL", label="memset"),
                                FV("GLOBAL", label="mmap"),
                                FV("GLOBAL", label="mprotect"),
                                FV("GLOBAL", label="munmap"),
                                FV("GLOBAL", label="open"),
                                FV("GLOBAL", label="raise"),
                                FV("GLOBAL", label="read"),
                                FV("GLOBAL", label="snprintf"),
                                FV("GLOBAL", label="sprintf"),
                                FV("GLOBAL", label="sscanf"),
                                FV("GLOBAL", label="strchr"),
                                FV("GLOBAL", label="strcmp"),
                                FV("GLOBAL", label="strcpy"),
                                FV("GLOBAL", label="strdup"),
                                FV("GLOBAL", label="strerror"),
                                FV("GLOBAL", label="strlcpy"),
                                FV("GLOBAL", label="strlen"),
                                FV("GLOBAL", label="strncmp"),
                                FV("GLOBAL", label="strncpy"),
                                FV("GLOBAL", label="strrchr"),
                                FV("GLOBAL", label="strstr"),
                                FV("GLOBAL", label="uncompress"),
                                FV("WEAK", label="__gnu_Unwind_Find_exidx"),
                            ],
                            "elf_import_size": [
                                FV(0, label="_ZdaPv"),
                                FV(0, label="_ZdlPv"),
                                FV(0, label="_Znaj"),
                                FV(0, label="__aeabi_memcpy"),
                                FV(0, label="__aeabi_memset"),
                                FV(0, label="__cxa_atexit"),
                                FV(0, label="__cxa_finalize"),
                                FV(0, label="__errno"),
                                FV(0, label="__gnu_Unwind_Find_exidx"),
                                FV(0, label="__stack_chk_fail"),
                                FV(0, label="__stack_chk_guard"),
                                FV(0, label="__system_property_get"),
                                FV(0, label="abort"),
                                FV(0, label="access"),
                                FV(0, label="close"),
                                FV(0, label="dlopen"),
                                FV(0, label="dlsym"),
                                FV(0, label="fclose"),
                                FV(0, label="fopen"),
                                FV(0, label="fread"),
                                FV(0, label="free"),
                                FV(0, label="gettimeofday"),
                                FV(0, label="malloc"),
                                FV(0, label="memcpy"),
                                FV(0, label="memset"),
                                FV(0, label="mmap"),
                                FV(0, label="mprotect"),
                                FV(0, label="munmap"),
                                FV(0, label="open"),
                                FV(0, label="raise"),
                                FV(0, label="read"),
                                FV(0, label="snprintf"),
                                FV(0, label="sprintf"),
                                FV(0, label="sscanf"),
                                FV(0, label="strchr"),
                                FV(0, label="strcmp"),
                                FV(0, label="strcpy"),
                                FV(0, label="strdup"),
                                FV(0, label="strerror"),
                                FV(0, label="strlcpy"),
                                FV(0, label="strlen"),
                                FV(0, label="strncmp"),
                                FV(0, label="strncpy"),
                                FV(0, label="strrchr"),
                                FV(0, label="strstr"),
                                FV(0, label="uncompress"),
                            ],
                            "elf_import_type": [
                                FV("FUNC", label="_ZdaPv"),
                                FV("FUNC", label="_ZdlPv"),
                                FV("FUNC", label="_Znaj"),
                                FV("FUNC", label="__aeabi_memcpy"),
                                FV("FUNC", label="__aeabi_memset"),
                                FV("FUNC", label="__cxa_atexit"),
                                FV("FUNC", label="__cxa_finalize"),
                                FV("FUNC", label="__errno"),
                                FV("FUNC", label="__gnu_Unwind_Find_exidx"),
                                FV("FUNC", label="__stack_chk_fail"),
                                FV("FUNC", label="__system_property_get"),
                                FV("FUNC", label="abort"),
                                FV("FUNC", label="access"),
                                FV("FUNC", label="close"),
                                FV("FUNC", label="dlopen"),
                                FV("FUNC", label="dlsym"),
                                FV("FUNC", label="fclose"),
                                FV("FUNC", label="fopen"),
                                FV("FUNC", label="fread"),
                                FV("FUNC", label="free"),
                                FV("FUNC", label="gettimeofday"),
                                FV("FUNC", label="malloc"),
                                FV("FUNC", label="memcpy"),
                                FV("FUNC", label="memset"),
                                FV("FUNC", label="mmap"),
                                FV("FUNC", label="mprotect"),
                                FV("FUNC", label="munmap"),
                                FV("FUNC", label="open"),
                                FV("FUNC", label="raise"),
                                FV("FUNC", label="read"),
                                FV("FUNC", label="snprintf"),
                                FV("FUNC", label="sprintf"),
                                FV("FUNC", label="sscanf"),
                                FV("FUNC", label="strchr"),
                                FV("FUNC", label="strcmp"),
                                FV("FUNC", label="strcpy"),
                                FV("FUNC", label="strdup"),
                                FV("FUNC", label="strerror"),
                                FV("FUNC", label="strlcpy"),
                                FV("FUNC", label="strlen"),
                                FV("FUNC", label="strncmp"),
                                FV("FUNC", label="strncpy"),
                                FV("FUNC", label="strrchr"),
                                FV("FUNC", label="strstr"),
                                FV("FUNC", label="uncompress"),
                                FV("OBJECT", label="__stack_chk_guard"),
                            ],
                            "elf_import_value": [
                                FV(0, label="_ZdaPv"),
                                FV(0, label="_ZdlPv"),
                                FV(0, label="_Znaj"),
                                FV(0, label="__aeabi_memcpy"),
                                FV(0, label="__aeabi_memset"),
                                FV(0, label="__cxa_atexit"),
                                FV(0, label="__cxa_finalize"),
                                FV(0, label="__errno"),
                                FV(0, label="__gnu_Unwind_Find_exidx"),
                                FV(0, label="__stack_chk_fail"),
                                FV(0, label="__stack_chk_guard"),
                                FV(0, label="__system_property_get"),
                                FV(0, label="abort"),
                                FV(0, label="access"),
                                FV(0, label="close"),
                                FV(0, label="dlopen"),
                                FV(0, label="dlsym"),
                                FV(0, label="fclose"),
                                FV(0, label="fopen"),
                                FV(0, label="fread"),
                                FV(0, label="free"),
                                FV(0, label="gettimeofday"),
                                FV(0, label="malloc"),
                                FV(0, label="memcpy"),
                                FV(0, label="memset"),
                                FV(0, label="mmap"),
                                FV(0, label="mprotect"),
                                FV(0, label="munmap"),
                                FV(0, label="open"),
                                FV(0, label="raise"),
                                FV(0, label="read"),
                                FV(0, label="snprintf"),
                                FV(0, label="sprintf"),
                                FV(0, label="sscanf"),
                                FV(0, label="strchr"),
                                FV(0, label="strcmp"),
                                FV(0, label="strcpy"),
                                FV(0, label="strdup"),
                                FV(0, label="strerror"),
                                FV(0, label="strlcpy"),
                                FV(0, label="strlen"),
                                FV(0, label="strncmp"),
                                FV(0, label="strncpy"),
                                FV(0, label="strrchr"),
                                FV(0, label="strstr"),
                                FV(0, label="uncompress"),
                            ],
                            "elf_import_version": [
                                FV("", label="_ZdaPv"),
                                FV("", label="_ZdlPv"),
                                FV("", label="_Znaj"),
                                FV("", label="__aeabi_memcpy"),
                                FV("", label="__aeabi_memset"),
                                FV("", label="__cxa_atexit"),
                                FV("", label="__cxa_finalize"),
                                FV("", label="__errno"),
                                FV("", label="__gnu_Unwind_Find_exidx"),
                                FV("", label="__stack_chk_fail"),
                                FV("", label="__stack_chk_guard"),
                                FV("", label="__system_property_get"),
                                FV("", label="abort"),
                                FV("", label="access"),
                                FV("", label="close"),
                                FV("", label="dlopen"),
                                FV("", label="dlsym"),
                                FV("", label="fclose"),
                                FV("", label="fopen"),
                                FV("", label="fread"),
                                FV("", label="free"),
                                FV("", label="gettimeofday"),
                                FV("", label="malloc"),
                                FV("", label="memcpy"),
                                FV("", label="memset"),
                                FV("", label="mmap"),
                                FV("", label="mprotect"),
                                FV("", label="munmap"),
                                FV("", label="open"),
                                FV("", label="raise"),
                                FV("", label="read"),
                                FV("", label="snprintf"),
                                FV("", label="sprintf"),
                                FV("", label="sscanf"),
                                FV("", label="strchr"),
                                FV("", label="strcmp"),
                                FV("", label="strcpy"),
                                FV("", label="strdup"),
                                FV("", label="strerror"),
                                FV("", label="strlcpy"),
                                FV("", label="strlen"),
                                FV("", label="strncmp"),
                                FV("", label="strncpy"),
                                FV("", label="strrchr"),
                                FV("", label="strstr"),
                                FV("", label="uncompress"),
                            ],
                            "elf_import_visibility": [
                                FV("DEFAULT", label="_ZdaPv"),
                                FV("DEFAULT", label="_ZdlPv"),
                                FV("DEFAULT", label="_Znaj"),
                                FV("DEFAULT", label="__aeabi_memcpy"),
                                FV("DEFAULT", label="__aeabi_memset"),
                                FV("DEFAULT", label="__cxa_atexit"),
                                FV("DEFAULT", label="__cxa_finalize"),
                                FV("DEFAULT", label="__errno"),
                                FV("DEFAULT", label="__gnu_Unwind_Find_exidx"),
                                FV("DEFAULT", label="__stack_chk_fail"),
                                FV("DEFAULT", label="__stack_chk_guard"),
                                FV("DEFAULT", label="__system_property_get"),
                                FV("DEFAULT", label="abort"),
                                FV("DEFAULT", label="access"),
                                FV("DEFAULT", label="close"),
                                FV("DEFAULT", label="dlopen"),
                                FV("DEFAULT", label="dlsym"),
                                FV("DEFAULT", label="fclose"),
                                FV("DEFAULT", label="fopen"),
                                FV("DEFAULT", label="fread"),
                                FV("DEFAULT", label="free"),
                                FV("DEFAULT", label="gettimeofday"),
                                FV("DEFAULT", label="malloc"),
                                FV("DEFAULT", label="memcpy"),
                                FV("DEFAULT", label="memset"),
                                FV("DEFAULT", label="mmap"),
                                FV("DEFAULT", label="mprotect"),
                                FV("DEFAULT", label="munmap"),
                                FV("DEFAULT", label="open"),
                                FV("DEFAULT", label="raise"),
                                FV("DEFAULT", label="read"),
                                FV("DEFAULT", label="snprintf"),
                                FV("DEFAULT", label="sprintf"),
                                FV("DEFAULT", label="sscanf"),
                                FV("DEFAULT", label="strchr"),
                                FV("DEFAULT", label="strcmp"),
                                FV("DEFAULT", label="strcpy"),
                                FV("DEFAULT", label="strdup"),
                                FV("DEFAULT", label="strerror"),
                                FV("DEFAULT", label="strlcpy"),
                                FV("DEFAULT", label="strlen"),
                                FV("DEFAULT", label="strncmp"),
                                FV("DEFAULT", label="strncpy"),
                                FV("DEFAULT", label="strrchr"),
                                FV("DEFAULT", label="strstr"),
                                FV("DEFAULT", label="uncompress"),
                            ],
                            "elf_machine": [FV("ARM")],
                            "elf_note": [FV(0)],
                            "elf_note_description": [FV("67 6f 6c 64 20 31 2e 31 31 00 00 00", label="0")],
                            "elf_note_gold_version": [FV("gold 1.11", label="0")],
                            "elf_note_name": [FV("GNU", label="0")],
                            "elf_note_type": [FV("GNU_GOLD_VERSION", label="0")],
                            "elf_num_prog_headers": [FV(8)],
                            "elf_num_section_headers": [FV(24)],
                            "elf_obj_version": [FV("0x1")],
                            "elf_os_abi": [FV("UNIX - System V")],
                            "elf_processor_flag": [FV(83886080)],
                            "elf_program_header_offset": [FV(52)],
                            "elf_program_header_size": [FV(32)],
                            "elf_section": [
                                FV("", offset=0, size=0),
                                FV(".ARM.attributes", offset=94048, size=47),
                                FV(".ARM.exidx", offset=83992, size=864),
                                FV(".ARM.extab", offset=83884, size=108),
                                FV(".bep", offset=90936, size=1024),
                                FV(".bss", offset=91960, size=1924),
                                FV(".comment", offset=93884, size=135),
                                FV(".data", offset=90112, size=824),
                                FV(".data.rel.ro.local", offset=89480, size=16),
                                FV(".dynamic", offset=89508, size=256),
                                FV(".dynstr", offset=2232, size=1821),
                                FV(".dynsym", offset=328, size=1904),
                                FV(".fini_array", offset=89496, size=8),
                                FV(".got", offset=89764, size=348),
                                FV(".hash", offset=4056, size=872),
                                FV(".init_array", offset=89504, size=4),
                                FV(".interp", offset=308, size=19),
                                FV(".note.gnu.gold-version", offset=94020, size=28),
                                FV(".plt", offset=5632, size=896),
                                FV(".rel.dyn", offset=4928, size=120),
                                FV(".rel.plt", offset=5048, size=584),
                                FV(".rodata", offset=84856, size=668),
                                FV(".shstrtab", offset=94095, size=216),
                                FV(".text", offset=6528, size=77356),
                            ],
                            "elf_section_alignment": [
                                FV(0, label=""),
                                FV(1, label=".ARM.attributes"),
                                FV(1, label=".bep"),
                                FV(1, label=".comment"),
                                FV(1, label=".dynstr"),
                                FV(1, label=".init_array"),
                                FV(1, label=".interp"),
                                FV(1, label=".rodata"),
                                FV(1, label=".shstrtab"),
                                FV(4, label=".ARM.exidx"),
                                FV(4, label=".ARM.extab"),
                                FV(4, label=".bss"),
                                FV(4, label=".data"),
                                FV(4, label=".data.rel.ro.local"),
                                FV(4, label=".dynamic"),
                                FV(4, label=".dynsym"),
                                FV(4, label=".fini_array"),
                                FV(4, label=".got"),
                                FV(4, label=".hash"),
                                FV(4, label=".note.gnu.gold-version"),
                                FV(4, label=".plt"),
                                FV(4, label=".rel.dyn"),
                                FV(4, label=".rel.plt"),
                                FV(4, label=".text"),
                            ],
                            "elf_section_entropy": [
                                FV(0.0, label=""),
                                FV(-0.0, label=".bss"),
                                FV(-0.0, label=".init_array"),
                                FV(1.0403777286587372, label=".got"),
                                FV(1.061278124459133, label=".fini_array"),
                                FV(1.5261535719540131, label=".hash"),
                                FV(1.6737949406953985, label=".data.rel.ro.local"),
                                FV(2.4017942559625167, label=".dynamic"),
                                FV(2.8176298883512287, label=".ARM.extab"),
                                FV(2.848047642129116, label=".note.gnu.gold-version"),
                                FV(2.8683356741065955, label=".dynsym"),
                                FV(3.2474086914964775, label=".rel.dyn"),
                                FV(3.5766176449086653, label=".interp"),
                                FV(3.8860102436377426, label=".rel.plt"),
                                FV(4.023448247086406, label=".plt"),
                                FV(4.27682436014924, label=".shstrtab"),
                                FV(4.370514714349908, label=".ARM.attributes"),
                                FV(4.673999864024546, label=".dynstr"),
                                FV(4.989115998450138, label=".ARM.exidx"),
                                FV(4.9919631236125035, label=".data"),
                                FV(5.178963075815777, label=".comment"),
                                FV(6.632037760795661, label=".text"),
                                FV(7.760183294191247, label=".rodata"),
                                FV(7.793446740752754, label=".bep"),
                            ],
                            "elf_section_entry_size": [
                                FV(0, label=""),
                                FV(0, label=".ARM.attributes"),
                                FV(0, label=".ARM.extab"),
                                FV(0, label=".bep"),
                                FV(0, label=".bss"),
                                FV(0, label=".data"),
                                FV(0, label=".data.rel.ro.local"),
                                FV(0, label=".dynstr"),
                                FV(0, label=".fini_array"),
                                FV(0, label=".got"),
                                FV(0, label=".init_array"),
                                FV(0, label=".interp"),
                                FV(0, label=".note.gnu.gold-version"),
                                FV(0, label=".plt"),
                                FV(0, label=".rodata"),
                                FV(0, label=".shstrtab"),
                                FV(0, label=".text"),
                                FV(1, label=".comment"),
                                FV(4, label=".hash"),
                                FV(8, label=".ARM.exidx"),
                                FV(8, label=".dynamic"),
                                FV(8, label=".rel.dyn"),
                                FV(8, label=".rel.plt"),
                                FV(16, label=".dynsym"),
                            ],
                            "elf_section_flags": [
                                FV("", label=""),
                                FV("", label=".ARM.attributes"),
                                FV("", label=".note.gnu.gold-version"),
                                FV("", label=".shstrtab"),
                                FV("A", label=".ARM.extab"),
                                FV("A", label=".dynstr"),
                                FV("A", label=".dynsym"),
                                FV("A", label=".hash"),
                                FV("A", label=".interp"),
                                FV("A", label=".rel.dyn"),
                                FV("A", label=".rel.plt"),
                                FV("A", label=".rodata"),
                                FV("AL", label=".ARM.exidx"),
                                FV("AX", label=".plt"),
                                FV("AX", label=".text"),
                                FV("MS", label=".comment"),
                                FV("WA", label=".bep"),
                                FV("WA", label=".bss"),
                                FV("WA", label=".data"),
                                FV("WA", label=".data.rel.ro.local"),
                                FV("WA", label=".dynamic"),
                                FV("WA", label=".fini_array"),
                                FV("WA", label=".got"),
                                FV("WA", label=".init_array"),
                            ],
                            "elf_section_hash": [
                                FV("06e6d5ad5ccdac356b425e98d01ff980ba78c9cacec0a40b0207fb128765b3ac", label=".hash"),
                                FV(
                                    "075815c5e93b47f9a59cbbeb4483aa15a00d9e74b5f09f72f77c0c5941f6ff72",
                                    label=".fini_array",
                                ),
                                FV("290d9aec403f3fa366983152a14885b28a8ab2b632dd175fc9293ffcbde0ceaf", label=".bep"),
                                FV(
                                    "2d0d2d46a21ab21d36606d3a79a591b91e92b14866359fe3ff69776df2db6146", label=".interp"
                                ),
                                FV(
                                    "305460f9ef575065ae90a90ff87527aa8d603a96943ec6f8509bcfcaed8253a0",
                                    label=".rel.plt",
                                ),
                                FV(
                                    "35dee454018b0c4ab7a6386658e966fe0ba45473efb3032f105592ebc162bbc9",
                                    label=".data.rel.ro.local",
                                ),
                                FV(
                                    "3f98c02de0943535e1fd04c6f9118e035fbb4ad056e4210c75aa7b7995bcccff",
                                    label=".comment",
                                ),
                                FV(
                                    "4aea4adc6b44343e10e1ac73abb39db773d29f69c1165a1ed1a53c267a9a14ea", label=".dynsym"
                                ),
                                FV("643ac85eca408b14cf81835e96f7f5871da5dd7556b6c006f22029f1aeaf5a20", label=".data"),
                                FV(
                                    "6f42a57de1c18324a0ede2cffb6a5b7f45d2912eb7187fb971f4cc3c64095cee",
                                    label=".shstrtab",
                                ),
                                FV("760f79fb448f8206ea1ebbd1c86711d3ac66f3e6b1106b90e37aa5de3e06f3ab", label=".plt"),
                                FV(
                                    "8359ec26d8fd72c94fb86f4f39ce5a1ca6801ee3ff10b5fbea2430668901e1fe", label=".rodata"
                                ),
                                FV(
                                    "9a1f6acec555945b9b21a257a03a5da2c34753e1cde3e67a275c46cc905c162c",
                                    label=".ARM.attributes",
                                ),
                                FV("a38e5de5dae743f0f5b761348fd8819abd95bafe4538d1eefec0b7bace68d07b", label=".text"),
                                FV(
                                    "a8f25c3e53c7dd865c86ebede4133efcb096513f838e0f13fc47bf4ab41aae5c", label=".dynstr"
                                ),
                                FV(
                                    "b6c8db6fc1edb0738840be30b74e9217577dcd216f3ffa63421f2e211761f9aa",
                                    label=".note.gnu.gold-version",
                                ),
                                FV(
                                    "bf3a184b5eb59eceb70c81f531f8b983fcc04f85989e76338c7a5f668fb3ed92",
                                    label=".dynamic",
                                ),
                                FV(
                                    "c0a05db1782f933ee03fde27e3231659d9d8bc6d634b243f4baa2a4c7b92a73a",
                                    label=".ARM.exidx",
                                ),
                                FV(
                                    "df3f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81119",
                                    label=".init_array",
                                ),
                                FV("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", label=""),
                                FV(
                                    "f7f53be69d2e8a3b24147e8da2142d9c86ed2a46773ec209bf7d2b3d355d1d20",
                                    label=".rel.dyn",
                                ),
                                FV("faffbecf32613ffd4585b8fb0374dc40f32a5c6364c3254f1ad2cdd7ac494d53", label=".bss"),
                                FV(
                                    "fc1fe515aa0083d0f5c3c90784adb456ca74ee4a01c46d6bf2fe37e05adbfd42",
                                    label=".ARM.extab",
                                ),
                                FV("fff24ec661beb4ffde2d576b364a565c1f96729ab13428f3131d04e6d170ddf3", label=".got"),
                            ],
                            "elf_section_header_offset": [FV(94312)],
                            "elf_section_header_size": [FV(40)],
                            "elf_section_information": [
                                FV(0, label=""),
                                FV(0, label=".ARM.attributes"),
                                FV(0, label=".ARM.exidx"),
                                FV(0, label=".ARM.extab"),
                                FV(0, label=".bep"),
                                FV(0, label=".bss"),
                                FV(0, label=".comment"),
                                FV(0, label=".data"),
                                FV(0, label=".data.rel.ro.local"),
                                FV(0, label=".dynamic"),
                                FV(0, label=".dynstr"),
                                FV(0, label=".fini_array"),
                                FV(0, label=".got"),
                                FV(0, label=".hash"),
                                FV(0, label=".init_array"),
                                FV(0, label=".interp"),
                                FV(0, label=".note.gnu.gold-version"),
                                FV(0, label=".plt"),
                                FV(0, label=".rel.dyn"),
                                FV(0, label=".rodata"),
                                FV(0, label=".shstrtab"),
                                FV(0, label=".text"),
                                FV(1, label=".dynsym"),
                                FV(7, label=".rel.plt"),
                            ],
                            "elf_section_link": [
                                FV(0, label=""),
                                FV(0, label=".ARM.attributes"),
                                FV(0, label=".ARM.extab"),
                                FV(0, label=".bep"),
                                FV(0, label=".bss"),
                                FV(0, label=".comment"),
                                FV(0, label=".data"),
                                FV(0, label=".data.rel.ro.local"),
                                FV(0, label=".dynstr"),
                                FV(0, label=".fini_array"),
                                FV(0, label=".got"),
                                FV(0, label=".init_array"),
                                FV(0, label=".interp"),
                                FV(0, label=".note.gnu.gold-version"),
                                FV(0, label=".plt"),
                                FV(0, label=".rodata"),
                                FV(0, label=".shstrtab"),
                                FV(0, label=".text"),
                                FV(2, label=".hash"),
                                FV(2, label=".rel.dyn"),
                                FV(2, label=".rel.plt"),
                                FV(3, label=".dynamic"),
                                FV(3, label=".dynsym"),
                                FV(8, label=".ARM.exidx"),
                            ],
                            "elf_section_name_table_idx": [FV(23)],
                            "elf_section_num_flags": [
                                FV(0, label=""),
                                FV(0, label=".ARM.attributes"),
                                FV(0, label=".note.gnu.gold-version"),
                                FV(0, label=".shstrtab"),
                                FV(2, label=".ARM.extab"),
                                FV(2, label=".dynstr"),
                                FV(2, label=".dynsym"),
                                FV(2, label=".hash"),
                                FV(2, label=".interp"),
                                FV(2, label=".rel.dyn"),
                                FV(2, label=".rel.plt"),
                                FV(2, label=".rodata"),
                                FV(3, label=".bep"),
                                FV(3, label=".bss"),
                                FV(3, label=".data"),
                                FV(3, label=".data.rel.ro.local"),
                                FV(3, label=".dynamic"),
                                FV(3, label=".fini_array"),
                                FV(3, label=".got"),
                                FV(3, label=".init_array"),
                                FV(6, label=".plt"),
                                FV(6, label=".text"),
                                FV(48, label=".comment"),
                                FV(130, label=".ARM.exidx"),
                            ],
                            "elf_section_segments": [
                                FV("", label=""),
                                FV("INTERP - LOAD", label=".interp"),
                                FV("LOAD", label=".ARM.attributes"),
                                FV("LOAD", label=".ARM.extab"),
                                FV("LOAD", label=".bep"),
                                FV("LOAD", label=".bss"),
                                FV("LOAD", label=".comment"),
                                FV("LOAD", label=".data"),
                                FV("LOAD", label=".dynstr"),
                                FV("LOAD", label=".dynsym"),
                                FV("LOAD", label=".hash"),
                                FV("LOAD", label=".note.gnu.gold-version"),
                                FV("LOAD", label=".plt"),
                                FV("LOAD", label=".rel.dyn"),
                                FV("LOAD", label=".rel.plt"),
                                FV("LOAD", label=".rodata"),
                                FV("LOAD", label=".shstrtab"),
                                FV("LOAD", label=".text"),
                                FV("LOAD - ARM_EXIDX", label=".ARM.exidx"),
                                FV("LOAD - DYNAMIC - GNU_RELRO", label=".dynamic"),
                                FV("LOAD - GNU_RELRO", label=".data.rel.ro.local"),
                                FV("LOAD - GNU_RELRO", label=".fini_array"),
                                FV("LOAD - GNU_RELRO", label=".got"),
                                FV("LOAD - GNU_RELRO", label=".init_array"),
                            ],
                            "elf_section_type": [
                                FV("<unknown>", label=".ARM.attributes"),
                                FV("<unknown>", label=".ARM.exidx"),
                                FV("DYNAMIC", label=".dynamic"),
                                FV("DYNSYM", label=".dynsym"),
                                FV("FINI_ARRAY", label=".fini_array"),
                                FV("HASH", label=".hash"),
                                FV("INIT_ARRAY", label=".init_array"),
                                FV("NOBITS", label=".bss"),
                                FV("NOTE", label=".note.gnu.gold-version"),
                                FV("NULL", label=""),
                                FV("PROGBITS", label=".ARM.extab"),
                                FV("PROGBITS", label=".bep"),
                                FV("PROGBITS", label=".comment"),
                                FV("PROGBITS", label=".data"),
                                FV("PROGBITS", label=".data.rel.ro.local"),
                                FV("PROGBITS", label=".got"),
                                FV("PROGBITS", label=".interp"),
                                FV("PROGBITS", label=".plt"),
                                FV("PROGBITS", label=".rodata"),
                                FV("PROGBITS", label=".text"),
                                FV("REL", label=".rel.dyn"),
                                FV("REL", label=".rel.plt"),
                                FV("STRTAB", label=".dynstr"),
                                FV("STRTAB", label=".shstrtab"),
                            ],
                            "elf_section_virtual_address": [
                                FV(0, label=""),
                                FV(308, label=".interp"),
                                FV(328, label=".dynsym"),
                                FV(1924, label=".ARM.attributes"),
                                FV(1924, label=".comment"),
                                FV(1924, label=".note.gnu.gold-version"),
                                FV(1924, label=".shstrtab"),
                                FV(2232, label=".dynstr"),
                                FV(4056, label=".hash"),
                                FV(4928, label=".rel.dyn"),
                                FV(5048, label=".rel.plt"),
                                FV(5632, label=".plt"),
                                FV(6528, label=".text"),
                                FV(83884, label=".ARM.extab"),
                                FV(83992, label=".ARM.exidx"),
                                FV(84856, label=".rodata"),
                                FV(93576, label=".data.rel.ro.local"),
                                FV(93592, label=".fini_array"),
                                FV(93600, label=".init_array"),
                                FV(93604, label=".dynamic"),
                                FV(93860, label=".got"),
                                FV(94208, label=".data"),
                                FV(95032, label=".bep"),
                                FV(96056, label=".bss"),
                            ],
                            "elf_segment": [
                                FV(0, offset=52, size=256),
                                FV(1, offset=308, size=19),
                                FV(2, offset=0, size=85524),
                                FV(3, offset=89480, size=16113),
                                FV(4, offset=89508, size=256),
                                FV(5, offset=0, size=0),
                                FV(6, offset=83992, size=864),
                                FV(7, offset=89480, size=632),
                            ],
                            "elf_segment_alignment": [
                                FV(0, label="5"),
                                FV(1, label="1"),
                                FV(4, label="0"),
                                FV(4, label="4"),
                                FV(4, label="6"),
                                FV(4, label="7"),
                                FV(4096, label="2"),
                                FV(4096, label="3"),
                            ],
                            "elf_segment_flags": [
                                FV("R--", label="0"),
                                FV("R--", label="1"),
                                FV("R--", label="6"),
                                FV("R-X", label="2"),
                                FV("RW-", label="3"),
                                FV("RW-", label="4"),
                                FV("RW-", label="5"),
                                FV("RW-", label="7"),
                            ],
                            "elf_segment_physical_address": [
                                FV(0, label="2"),
                                FV(0, label="5"),
                                FV(52, label="0"),
                                FV(308, label="1"),
                                FV(83992, label="6"),
                                FV(93576, label="3"),
                                FV(93576, label="7"),
                                FV(93604, label="4"),
                            ],
                            "elf_segment_sections": [
                                FV("", label="0"),
                                FV("", label="5"),
                                FV(".ARM.exidx", label="6"),
                                FV(".data.rel.ro.local, .fini_array, .init_array, .dynamic, .got", label="7"),
                                FV(
                                    ".data.rel.ro.local, .fini_array, .init_array, .dynamic, .got, .data, .bep, .bss",
                                    label="3",
                                ),
                                FV(".dynamic", label="4"),
                                FV(".interp", label="1"),
                                FV(
                                    ".interp, .dynsym, .dynstr, .hash, .rel.dyn, .rel.plt, .plt, .text, .ARM.extab, .ARM.exidx, .rodata, .comment, .note.gnu.gold-version, .ARM.attributes, .shstrtab",
                                    label="2",
                                ),
                            ],
                            "elf_segment_type": [
                                FV("<unknown>", label="6"),
                                FV("DYNAMIC", label="4"),
                                FV("GNU_RELRO", label="7"),
                                FV("GNU_STACK", label="5"),
                                FV("INTERP", label="1"),
                                FV("LOAD", label="2"),
                                FV("LOAD", label="3"),
                                FV("PHDR", label="0"),
                            ],
                            "elf_segment_virtual_address": [
                                FV(0, label="2"),
                                FV(0, label="5"),
                                FV(52, label="0"),
                                FV(308, label="1"),
                                FV(83992, label="6"),
                                FV(93576, label="3"),
                                FV(93576, label="7"),
                                FV(93604, label="4"),
                            ],
                            "elf_segment_virtual_size": [
                                FV(0, label="5"),
                                FV(19, label="1"),
                                FV(256, label="0"),
                                FV(256, label="4"),
                                FV(632, label="7"),
                                FV(864, label="6"),
                                FV(18037, label="3"),
                                FV(85524, label="2"),
                            ],
                            "elf_type": [FV("DYN (Shared object file)")],
                        },
                    )
                ],
            ),
        )
