"""
LIEF ELF functional test suite.

Functionally test a full ELF x64 ls file.

"""

from azul_runner import FV, DataLabel, Event, JobResult, State, test_template

from azul_plugin_lief.lief_elf import LiefELF


class TestExecute(test_template.TestPlugin):
    """Parent class of all Lief ELF tests."""

    PLUGIN_TO_TEST = LiefELF

    def test_lief_elf_ls_32(self):
        """Tests on CentOS 6 'ls' i386."""
        result = self.do_execution(
            data_in=[
                (
                    DataLabel.CONTENT,
                    self.load_test_file_bytes(
                        "3607d78cbca461f876771813bda33dc4f5c44eeea4805172b7eb3b1b29d9f2d7",
                        "Benign ELF32 with i386 architecture from centos6.",
                    ),
                )
            ]
        )

        self.assertJobResult(
            result,
            JobResult(
                state=State(State.Label.COMPLETED),
                events=[
                    Event(
                        entity_type="binary",
                        entity_id="3607d78cbca461f876771813bda33dc4f5c44eeea4805172b7eb3b1b29d9f2d7",
                        features={
                            "elf_abi_version": [FV(0)],
                            "elf_class": [FV("ELF32")],
                            "elf_data": [FV("2's complement, little endian")],
                            "elf_entrypoint": [FV(134519904)],
                            "elf_export": [
                                FV("Version"),
                                FV("_IO_stdin_used"),
                                FV("_fini"),
                                FV("_init"),
                                FV("argmatch_die"),
                                FV("close_stdout"),
                                FV("exit_failure"),
                                FV("ls_mode"),
                                FV("program_name"),
                                FV("quoting_style_args"),
                                FV("quoting_style_vals"),
                                FV("version_etc_copyright"),
                            ],
                            "elf_export_binding": [
                                FV("GLOBAL", label="Version"),
                                FV("GLOBAL", label="_IO_stdin_used"),
                                FV("GLOBAL", label="_fini"),
                                FV("GLOBAL", label="_init"),
                                FV("GLOBAL", label="argmatch_die"),
                                FV("GLOBAL", label="close_stdout"),
                                FV("GLOBAL", label="exit_failure"),
                                FV("GLOBAL", label="ls_mode"),
                                FV("GLOBAL", label="program_name"),
                                FV("GLOBAL", label="quoting_style_args"),
                                FV("GLOBAL", label="quoting_style_vals"),
                                FV("GLOBAL", label="version_etc_copyright"),
                            ],
                            "elf_export_size": [
                                FV(0, label="_fini"),
                                FV(0, label="_init"),
                                FV(4, label="Version"),
                                FV(4, label="_IO_stdin_used"),
                                FV(4, label="argmatch_die"),
                                FV(4, label="exit_failure"),
                                FV(4, label="ls_mode"),
                                FV(4, label="program_name"),
                                FV(32, label="quoting_style_vals"),
                                FV(36, label="quoting_style_args"),
                                FV(47, label="version_etc_copyright"),
                                FV(244, label="close_stdout"),
                            ],
                            "elf_export_type": [
                                FV("FUNC", label="_fini"),
                                FV("FUNC", label="_init"),
                                FV("FUNC", label="close_stdout"),
                                FV("OBJECT", label="Version"),
                                FV("OBJECT", label="_IO_stdin_used"),
                                FV("OBJECT", label="argmatch_die"),
                                FV("OBJECT", label="exit_failure"),
                                FV("OBJECT", label="ls_mode"),
                                FV("OBJECT", label="program_name"),
                                FV("OBJECT", label="quoting_style_args"),
                                FV("OBJECT", label="quoting_style_vals"),
                                FV("OBJECT", label="version_etc_copyright"),
                            ],
                            "elf_export_value": [
                                FV(134518180, label="_init"),
                                FV(134563808, label="close_stdout"),
                                FV(134593852, label="_fini"),
                                FV(134593892, label="_IO_stdin_used"),
                                FV(134606848, label="version_etc_copyright"),
                                FV(134608064, label="quoting_style_vals"),
                                FV(134624576, label="quoting_style_args"),
                                FV(134625600, label="ls_mode"),
                                FV(134625604, label="Version"),
                                FV(134625608, label="argmatch_die"),
                                FV(134625612, label="exit_failure"),
                                FV(134628380, label="program_name"),
                            ],
                            "elf_export_version": [
                                FV("* Global *", label="Version"),
                                FV("* Global *", label="_IO_stdin_used"),
                                FV("* Global *", label="_fini"),
                                FV("* Global *", label="_init"),
                                FV("* Global *", label="argmatch_die"),
                                FV("* Global *", label="close_stdout"),
                                FV("* Global *", label="exit_failure"),
                                FV("* Global *", label="ls_mode"),
                                FV("* Global *", label="program_name"),
                                FV("* Global *", label="quoting_style_args"),
                                FV("* Global *", label="quoting_style_vals"),
                                FV("* Global *", label="version_etc_copyright"),
                            ],
                            "elf_export_visibility": [
                                FV("DEFAULT", label="Version"),
                                FV("DEFAULT", label="_IO_stdin_used"),
                                FV("DEFAULT", label="_fini"),
                                FV("DEFAULT", label="_init"),
                                FV("DEFAULT", label="argmatch_die"),
                                FV("DEFAULT", label="close_stdout"),
                                FV("DEFAULT", label="exit_failure"),
                                FV("DEFAULT", label="ls_mode"),
                                FV("DEFAULT", label="program_name"),
                                FV("DEFAULT", label="quoting_style_args"),
                                FV("DEFAULT", label="quoting_style_vals"),
                                FV("DEFAULT", label="version_etc_copyright"),
                            ],
                            "elf_hdr_version": [FV("1 (current)")],
                            "elf_header_size": [FV(52)],
                            "elf_import": [
                                FV("__assert_fail"),
                                FV("__ctype_b_loc"),
                                FV("__ctype_get_mb_cur_max"),
                                FV("__ctype_tolower_loc"),
                                FV("__ctype_toupper_loc"),
                                FV("__cxa_atexit"),
                                FV("__errno_location"),
                                FV("__fpending"),
                                FV("__fprintf_chk"),
                                FV("__fxstat64"),
                                FV("__libc_start_main"),
                                FV("__lxstat64"),
                                FV("__memcpy_chk"),
                                FV("__mempcpy_chk"),
                                FV("__overflow"),
                                FV("__printf_chk"),
                                FV("__progname"),
                                FV("__progname_full"),
                                FV("__sprintf_chk"),
                                FV("__stack_chk_fail"),
                                FV("__strtoull_internal"),
                                FV("__xstat64"),
                                FV("_exit"),
                                FV("_obstack_begin"),
                                FV("_obstack_newchunk"),
                                FV("_setjmp"),
                                FV("abort"),
                                FV("acl_extended_file"),
                                FV("acl_extended_file_nofollow"),
                                FV("acl_get_entry"),
                                FV("acl_get_tag_type"),
                                FV("bindtextdomain"),
                                FV("calloc"),
                                FV("cap_free"),
                                FV("cap_get_file"),
                                FV("cap_to_text"),
                                FV("clock_gettime"),
                                FV("closedir"),
                                FV("dcgettext"),
                                FV("dirfd"),
                                FV("error"),
                                FV("exit"),
                                FV("fclose"),
                                FV("fflush_unlocked"),
                                FV("fgetfilecon"),
                                FV("fnmatch"),
                                FV("fputs_unlocked"),
                                FV("free"),
                                FV("freecon"),
                                FV("fwrite"),
                                FV("fwrite_unlocked"),
                                FV("getenv"),
                                FV("getfilecon"),
                                FV("getgrgid"),
                                FV("getgrnam"),
                                FV("getopt_long"),
                                FV("getpwnam"),
                                FV("getpwuid"),
                                FV("gettimeofday"),
                                FV("ioctl"),
                                FV("isatty"),
                                FV("iswcntrl"),
                                FV("iswprint"),
                                FV("lgetfilecon"),
                                FV("localeconv"),
                                FV("localtime"),
                                FV("malloc"),
                                FV("mbrtowc"),
                                FV("mbsinit"),
                                FV("mbstowcs"),
                                FV("memcpy"),
                                FV("memmove"),
                                FV("mempcpy"),
                                FV("memset"),
                                FV("mktime"),
                                FV("nl_langinfo"),
                                FV("opendir"),
                                FV("optarg"),
                                FV("optind"),
                                FV("program_invocation_name"),
                                FV("program_invocation_short_name"),
                                FV("raise"),
                                FV("readdir64"),
                                FV("readlink"),
                                FV("realloc"),
                                FV("setlocale"),
                                FV("sigaction"),
                                FV("sigaddset"),
                                FV("sigemptyset"),
                                FV("sigismember"),
                                FV("signal"),
                                FV("sigprocmask"),
                                FV("stderr"),
                                FV("stdout"),
                                FV("stpcpy"),
                                FV("strchr"),
                                FV("strcmp"),
                                FV("strcoll"),
                                FV("strcpy"),
                                FV("strftime"),
                                FV("strlen"),
                                FV("strncmp"),
                                FV("strncpy"),
                                FV("strrchr"),
                                FV("strstr"),
                                FV("strtoul"),
                                FV("tcgetpgrp"),
                                FV("textdomain"),
                                FV("wcstombs"),
                                FV("wcwidth"),
                            ],
                            "elf_import_binding": [
                                FV("GLOBAL", label="__assert_fail"),
                                FV("GLOBAL", label="__ctype_b_loc"),
                                FV("GLOBAL", label="__ctype_get_mb_cur_max"),
                                FV("GLOBAL", label="__ctype_tolower_loc"),
                                FV("GLOBAL", label="__ctype_toupper_loc"),
                                FV("GLOBAL", label="__cxa_atexit"),
                                FV("GLOBAL", label="__errno_location"),
                                FV("GLOBAL", label="__fpending"),
                                FV("GLOBAL", label="__fprintf_chk"),
                                FV("GLOBAL", label="__fxstat64"),
                                FV("GLOBAL", label="__libc_start_main"),
                                FV("GLOBAL", label="__lxstat64"),
                                FV("GLOBAL", label="__memcpy_chk"),
                                FV("GLOBAL", label="__mempcpy_chk"),
                                FV("GLOBAL", label="__overflow"),
                                FV("GLOBAL", label="__printf_chk"),
                                FV("GLOBAL", label="__progname"),
                                FV("GLOBAL", label="__progname_full"),
                                FV("GLOBAL", label="__sprintf_chk"),
                                FV("GLOBAL", label="__stack_chk_fail"),
                                FV("GLOBAL", label="__strtoull_internal"),
                                FV("GLOBAL", label="__xstat64"),
                                FV("GLOBAL", label="_exit"),
                                FV("GLOBAL", label="_obstack_begin"),
                                FV("GLOBAL", label="_obstack_newchunk"),
                                FV("GLOBAL", label="_setjmp"),
                                FV("GLOBAL", label="abort"),
                                FV("GLOBAL", label="acl_extended_file"),
                                FV("GLOBAL", label="acl_extended_file_nofollow"),
                                FV("GLOBAL", label="acl_get_entry"),
                                FV("GLOBAL", label="acl_get_tag_type"),
                                FV("GLOBAL", label="bindtextdomain"),
                                FV("GLOBAL", label="calloc"),
                                FV("GLOBAL", label="cap_free"),
                                FV("GLOBAL", label="cap_get_file"),
                                FV("GLOBAL", label="cap_to_text"),
                                FV("GLOBAL", label="clock_gettime"),
                                FV("GLOBAL", label="closedir"),
                                FV("GLOBAL", label="dcgettext"),
                                FV("GLOBAL", label="dirfd"),
                                FV("GLOBAL", label="error"),
                                FV("GLOBAL", label="exit"),
                                FV("GLOBAL", label="fclose"),
                                FV("GLOBAL", label="fflush_unlocked"),
                                FV("GLOBAL", label="fgetfilecon"),
                                FV("GLOBAL", label="fnmatch"),
                                FV("GLOBAL", label="fputs_unlocked"),
                                FV("GLOBAL", label="free"),
                                FV("GLOBAL", label="freecon"),
                                FV("GLOBAL", label="fwrite"),
                                FV("GLOBAL", label="fwrite_unlocked"),
                                FV("GLOBAL", label="getenv"),
                                FV("GLOBAL", label="getfilecon"),
                                FV("GLOBAL", label="getgrgid"),
                                FV("GLOBAL", label="getgrnam"),
                                FV("GLOBAL", label="getopt_long"),
                                FV("GLOBAL", label="getpwnam"),
                                FV("GLOBAL", label="getpwuid"),
                                FV("GLOBAL", label="gettimeofday"),
                                FV("GLOBAL", label="ioctl"),
                                FV("GLOBAL", label="isatty"),
                                FV("GLOBAL", label="iswcntrl"),
                                FV("GLOBAL", label="iswprint"),
                                FV("GLOBAL", label="lgetfilecon"),
                                FV("GLOBAL", label="localeconv"),
                                FV("GLOBAL", label="localtime"),
                                FV("GLOBAL", label="malloc"),
                                FV("GLOBAL", label="mbrtowc"),
                                FV("GLOBAL", label="mbsinit"),
                                FV("GLOBAL", label="mbstowcs"),
                                FV("GLOBAL", label="memcpy"),
                                FV("GLOBAL", label="memmove"),
                                FV("GLOBAL", label="mempcpy"),
                                FV("GLOBAL", label="memset"),
                                FV("GLOBAL", label="mktime"),
                                FV("GLOBAL", label="nl_langinfo"),
                                FV("GLOBAL", label="opendir"),
                                FV("GLOBAL", label="optarg"),
                                FV("GLOBAL", label="optind"),
                                FV("GLOBAL", label="program_invocation_name"),
                                FV("GLOBAL", label="program_invocation_short_name"),
                                FV("GLOBAL", label="raise"),
                                FV("GLOBAL", label="readdir64"),
                                FV("GLOBAL", label="readlink"),
                                FV("GLOBAL", label="realloc"),
                                FV("GLOBAL", label="setlocale"),
                                FV("GLOBAL", label="sigaction"),
                                FV("GLOBAL", label="sigaddset"),
                                FV("GLOBAL", label="sigemptyset"),
                                FV("GLOBAL", label="sigismember"),
                                FV("GLOBAL", label="signal"),
                                FV("GLOBAL", label="sigprocmask"),
                                FV("GLOBAL", label="stderr"),
                                FV("GLOBAL", label="stdout"),
                                FV("GLOBAL", label="stpcpy"),
                                FV("GLOBAL", label="strchr"),
                                FV("GLOBAL", label="strcmp"),
                                FV("GLOBAL", label="strcoll"),
                                FV("GLOBAL", label="strcpy"),
                                FV("GLOBAL", label="strftime"),
                                FV("GLOBAL", label="strlen"),
                                FV("GLOBAL", label="strncmp"),
                                FV("GLOBAL", label="strncpy"),
                                FV("GLOBAL", label="strrchr"),
                                FV("GLOBAL", label="strstr"),
                                FV("GLOBAL", label="strtoul"),
                                FV("GLOBAL", label="tcgetpgrp"),
                                FV("GLOBAL", label="textdomain"),
                                FV("GLOBAL", label="wcstombs"),
                                FV("GLOBAL", label="wcwidth"),
                            ],
                            "elf_import_size": [
                                FV(0, label="__assert_fail"),
                                FV(0, label="__ctype_b_loc"),
                                FV(0, label="__ctype_get_mb_cur_max"),
                                FV(0, label="__ctype_tolower_loc"),
                                FV(0, label="__ctype_toupper_loc"),
                                FV(0, label="__cxa_atexit"),
                                FV(0, label="__errno_location"),
                                FV(0, label="__fpending"),
                                FV(0, label="__fprintf_chk"),
                                FV(0, label="__fxstat64"),
                                FV(0, label="__libc_start_main"),
                                FV(0, label="__lxstat64"),
                                FV(0, label="__memcpy_chk"),
                                FV(0, label="__mempcpy_chk"),
                                FV(0, label="__overflow"),
                                FV(0, label="__printf_chk"),
                                FV(0, label="__progname"),
                                FV(0, label="__progname_full"),
                                FV(0, label="__sprintf_chk"),
                                FV(0, label="__stack_chk_fail"),
                                FV(0, label="__strtoull_internal"),
                                FV(0, label="__xstat64"),
                                FV(0, label="_exit"),
                                FV(0, label="_obstack_begin"),
                                FV(0, label="_obstack_newchunk"),
                                FV(0, label="_setjmp"),
                                FV(0, label="abort"),
                                FV(0, label="acl_extended_file"),
                                FV(0, label="acl_extended_file_nofollow"),
                                FV(0, label="acl_get_entry"),
                                FV(0, label="acl_get_tag_type"),
                                FV(0, label="bindtextdomain"),
                                FV(0, label="calloc"),
                                FV(0, label="cap_free"),
                                FV(0, label="cap_get_file"),
                                FV(0, label="cap_to_text"),
                                FV(0, label="clock_gettime"),
                                FV(0, label="closedir"),
                                FV(0, label="dcgettext"),
                                FV(0, label="dirfd"),
                                FV(0, label="error"),
                                FV(0, label="exit"),
                                FV(0, label="fclose"),
                                FV(0, label="fflush_unlocked"),
                                FV(0, label="fgetfilecon"),
                                FV(0, label="fnmatch"),
                                FV(0, label="fputs_unlocked"),
                                FV(0, label="free"),
                                FV(0, label="freecon"),
                                FV(0, label="fwrite"),
                                FV(0, label="fwrite_unlocked"),
                                FV(0, label="getenv"),
                                FV(0, label="getfilecon"),
                                FV(0, label="getgrgid"),
                                FV(0, label="getgrnam"),
                                FV(0, label="getopt_long"),
                                FV(0, label="getpwnam"),
                                FV(0, label="getpwuid"),
                                FV(0, label="gettimeofday"),
                                FV(0, label="ioctl"),
                                FV(0, label="isatty"),
                                FV(0, label="iswcntrl"),
                                FV(0, label="iswprint"),
                                FV(0, label="lgetfilecon"),
                                FV(0, label="localeconv"),
                                FV(0, label="localtime"),
                                FV(0, label="malloc"),
                                FV(0, label="mbrtowc"),
                                FV(0, label="mbsinit"),
                                FV(0, label="mbstowcs"),
                                FV(0, label="memcpy"),
                                FV(0, label="memmove"),
                                FV(0, label="mempcpy"),
                                FV(0, label="memset"),
                                FV(0, label="mktime"),
                                FV(0, label="nl_langinfo"),
                                FV(0, label="opendir"),
                                FV(0, label="optarg"),
                                FV(0, label="optind"),
                                FV(0, label="program_invocation_name"),
                                FV(0, label="program_invocation_short_name"),
                                FV(0, label="raise"),
                                FV(0, label="readdir64"),
                                FV(0, label="readlink"),
                                FV(0, label="realloc"),
                                FV(0, label="setlocale"),
                                FV(0, label="sigaction"),
                                FV(0, label="sigaddset"),
                                FV(0, label="sigemptyset"),
                                FV(0, label="sigismember"),
                                FV(0, label="signal"),
                                FV(0, label="sigprocmask"),
                                FV(0, label="stderr"),
                                FV(0, label="stdout"),
                                FV(0, label="stpcpy"),
                                FV(0, label="strchr"),
                                FV(0, label="strcmp"),
                                FV(0, label="strcoll"),
                                FV(0, label="strcpy"),
                                FV(0, label="strftime"),
                                FV(0, label="strlen"),
                                FV(0, label="strncmp"),
                                FV(0, label="strncpy"),
                                FV(0, label="strrchr"),
                                FV(0, label="strstr"),
                                FV(0, label="strtoul"),
                                FV(0, label="tcgetpgrp"),
                                FV(0, label="textdomain"),
                                FV(0, label="wcstombs"),
                                FV(0, label="wcwidth"),
                            ],
                            "elf_import_type": [
                                FV("FUNC", label="__assert_fail"),
                                FV("FUNC", label="__ctype_b_loc"),
                                FV("FUNC", label="__ctype_get_mb_cur_max"),
                                FV("FUNC", label="__ctype_tolower_loc"),
                                FV("FUNC", label="__ctype_toupper_loc"),
                                FV("FUNC", label="__cxa_atexit"),
                                FV("FUNC", label="__errno_location"),
                                FV("FUNC", label="__fpending"),
                                FV("FUNC", label="__fprintf_chk"),
                                FV("FUNC", label="__fxstat64"),
                                FV("FUNC", label="__libc_start_main"),
                                FV("FUNC", label="__lxstat64"),
                                FV("FUNC", label="__memcpy_chk"),
                                FV("FUNC", label="__mempcpy_chk"),
                                FV("FUNC", label="__overflow"),
                                FV("FUNC", label="__printf_chk"),
                                FV("FUNC", label="__sprintf_chk"),
                                FV("FUNC", label="__stack_chk_fail"),
                                FV("FUNC", label="__strtoull_internal"),
                                FV("FUNC", label="__xstat64"),
                                FV("FUNC", label="_exit"),
                                FV("FUNC", label="_obstack_begin"),
                                FV("FUNC", label="_obstack_newchunk"),
                                FV("FUNC", label="_setjmp"),
                                FV("FUNC", label="abort"),
                                FV("FUNC", label="acl_extended_file"),
                                FV("FUNC", label="acl_extended_file_nofollow"),
                                FV("FUNC", label="acl_get_entry"),
                                FV("FUNC", label="acl_get_tag_type"),
                                FV("FUNC", label="bindtextdomain"),
                                FV("FUNC", label="calloc"),
                                FV("FUNC", label="cap_free"),
                                FV("FUNC", label="cap_get_file"),
                                FV("FUNC", label="cap_to_text"),
                                FV("FUNC", label="clock_gettime"),
                                FV("FUNC", label="closedir"),
                                FV("FUNC", label="dcgettext"),
                                FV("FUNC", label="dirfd"),
                                FV("FUNC", label="error"),
                                FV("FUNC", label="exit"),
                                FV("FUNC", label="fclose"),
                                FV("FUNC", label="fflush_unlocked"),
                                FV("FUNC", label="fgetfilecon"),
                                FV("FUNC", label="fnmatch"),
                                FV("FUNC", label="fputs_unlocked"),
                                FV("FUNC", label="free"),
                                FV("FUNC", label="freecon"),
                                FV("FUNC", label="fwrite"),
                                FV("FUNC", label="fwrite_unlocked"),
                                FV("FUNC", label="getenv"),
                                FV("FUNC", label="getfilecon"),
                                FV("FUNC", label="getgrgid"),
                                FV("FUNC", label="getgrnam"),
                                FV("FUNC", label="getopt_long"),
                                FV("FUNC", label="getpwnam"),
                                FV("FUNC", label="getpwuid"),
                                FV("FUNC", label="gettimeofday"),
                                FV("FUNC", label="ioctl"),
                                FV("FUNC", label="isatty"),
                                FV("FUNC", label="iswcntrl"),
                                FV("FUNC", label="iswprint"),
                                FV("FUNC", label="lgetfilecon"),
                                FV("FUNC", label="localeconv"),
                                FV("FUNC", label="localtime"),
                                FV("FUNC", label="malloc"),
                                FV("FUNC", label="mbrtowc"),
                                FV("FUNC", label="mbsinit"),
                                FV("FUNC", label="mbstowcs"),
                                FV("FUNC", label="memcpy"),
                                FV("FUNC", label="memmove"),
                                FV("FUNC", label="mempcpy"),
                                FV("FUNC", label="memset"),
                                FV("FUNC", label="mktime"),
                                FV("FUNC", label="nl_langinfo"),
                                FV("FUNC", label="opendir"),
                                FV("FUNC", label="raise"),
                                FV("FUNC", label="readdir64"),
                                FV("FUNC", label="readlink"),
                                FV("FUNC", label="realloc"),
                                FV("FUNC", label="setlocale"),
                                FV("FUNC", label="sigaction"),
                                FV("FUNC", label="sigaddset"),
                                FV("FUNC", label="sigemptyset"),
                                FV("FUNC", label="sigismember"),
                                FV("FUNC", label="signal"),
                                FV("FUNC", label="sigprocmask"),
                                FV("FUNC", label="stpcpy"),
                                FV("FUNC", label="strchr"),
                                FV("FUNC", label="strcmp"),
                                FV("FUNC", label="strcoll"),
                                FV("FUNC", label="strcpy"),
                                FV("FUNC", label="strftime"),
                                FV("FUNC", label="strlen"),
                                FV("FUNC", label="strncmp"),
                                FV("FUNC", label="strncpy"),
                                FV("FUNC", label="strrchr"),
                                FV("FUNC", label="strstr"),
                                FV("FUNC", label="strtoul"),
                                FV("FUNC", label="tcgetpgrp"),
                                FV("FUNC", label="textdomain"),
                                FV("FUNC", label="wcstombs"),
                                FV("FUNC", label="wcwidth"),
                                FV("OBJECT", label="__progname"),
                                FV("OBJECT", label="__progname_full"),
                                FV("OBJECT", label="optarg"),
                                FV("OBJECT", label="optind"),
                                FV("OBJECT", label="program_invocation_name"),
                                FV("OBJECT", label="program_invocation_short_name"),
                                FV("OBJECT", label="stderr"),
                                FV("OBJECT", label="stdout"),
                            ],
                            "elf_import_value": [
                                FV(0, label="__assert_fail"),
                                FV(0, label="__ctype_b_loc"),
                                FV(0, label="__ctype_get_mb_cur_max"),
                                FV(0, label="__ctype_tolower_loc"),
                                FV(0, label="__ctype_toupper_loc"),
                                FV(0, label="__cxa_atexit"),
                                FV(0, label="__errno_location"),
                                FV(0, label="__fpending"),
                                FV(0, label="__fprintf_chk"),
                                FV(0, label="__fxstat64"),
                                FV(0, label="__libc_start_main"),
                                FV(0, label="__lxstat64"),
                                FV(0, label="__memcpy_chk"),
                                FV(0, label="__mempcpy_chk"),
                                FV(0, label="__overflow"),
                                FV(0, label="__printf_chk"),
                                FV(0, label="__progname"),
                                FV(0, label="__progname_full"),
                                FV(0, label="__sprintf_chk"),
                                FV(0, label="__stack_chk_fail"),
                                FV(0, label="__strtoull_internal"),
                                FV(0, label="__xstat64"),
                                FV(0, label="_exit"),
                                FV(0, label="_obstack_begin"),
                                FV(0, label="_obstack_newchunk"),
                                FV(0, label="_setjmp"),
                                FV(0, label="abort"),
                                FV(0, label="acl_extended_file"),
                                FV(0, label="acl_extended_file_nofollow"),
                                FV(0, label="acl_get_entry"),
                                FV(0, label="acl_get_tag_type"),
                                FV(0, label="bindtextdomain"),
                                FV(0, label="calloc"),
                                FV(0, label="cap_free"),
                                FV(0, label="cap_get_file"),
                                FV(0, label="cap_to_text"),
                                FV(0, label="clock_gettime"),
                                FV(0, label="closedir"),
                                FV(0, label="dcgettext"),
                                FV(0, label="dirfd"),
                                FV(0, label="error"),
                                FV(0, label="exit"),
                                FV(0, label="fclose"),
                                FV(0, label="fflush_unlocked"),
                                FV(0, label="fgetfilecon"),
                                FV(0, label="fnmatch"),
                                FV(0, label="fputs_unlocked"),
                                FV(0, label="free"),
                                FV(0, label="freecon"),
                                FV(0, label="fwrite"),
                                FV(0, label="fwrite_unlocked"),
                                FV(0, label="getenv"),
                                FV(0, label="getfilecon"),
                                FV(0, label="getgrgid"),
                                FV(0, label="getgrnam"),
                                FV(0, label="getopt_long"),
                                FV(0, label="getpwnam"),
                                FV(0, label="getpwuid"),
                                FV(0, label="gettimeofday"),
                                FV(0, label="ioctl"),
                                FV(0, label="isatty"),
                                FV(0, label="iswcntrl"),
                                FV(0, label="iswprint"),
                                FV(0, label="lgetfilecon"),
                                FV(0, label="localeconv"),
                                FV(0, label="localtime"),
                                FV(0, label="malloc"),
                                FV(0, label="mbrtowc"),
                                FV(0, label="mbsinit"),
                                FV(0, label="mbstowcs"),
                                FV(0, label="memcpy"),
                                FV(0, label="memmove"),
                                FV(0, label="mempcpy"),
                                FV(0, label="memset"),
                                FV(0, label="mktime"),
                                FV(0, label="nl_langinfo"),
                                FV(0, label="opendir"),
                                FV(0, label="optarg"),
                                FV(0, label="optind"),
                                FV(0, label="program_invocation_name"),
                                FV(0, label="program_invocation_short_name"),
                                FV(0, label="raise"),
                                FV(0, label="readdir64"),
                                FV(0, label="readlink"),
                                FV(0, label="realloc"),
                                FV(0, label="setlocale"),
                                FV(0, label="sigaction"),
                                FV(0, label="sigaddset"),
                                FV(0, label="sigemptyset"),
                                FV(0, label="sigismember"),
                                FV(0, label="signal"),
                                FV(0, label="sigprocmask"),
                                FV(0, label="stderr"),
                                FV(0, label="stdout"),
                                FV(0, label="stpcpy"),
                                FV(0, label="strchr"),
                                FV(0, label="strcmp"),
                                FV(0, label="strcoll"),
                                FV(0, label="strcpy"),
                                FV(0, label="strftime"),
                                FV(0, label="strlen"),
                                FV(0, label="strncmp"),
                                FV(0, label="strncpy"),
                                FV(0, label="strrchr"),
                                FV(0, label="strstr"),
                                FV(0, label="strtoul"),
                                FV(0, label="tcgetpgrp"),
                                FV(0, label="textdomain"),
                                FV(0, label="wcstombs"),
                                FV(0, label="wcwidth"),
                            ],
                            "elf_import_version": [
                                FV("* Local *", label="cap_free"),
                                FV("* Local *", label="cap_get_file"),
                                FV("* Local *", label="cap_to_text"),
                                FV("* Local *", label="fgetfilecon"),
                                FV("* Local *", label="freecon"),
                                FV("* Local *", label="getfilecon"),
                                FV("* Local *", label="lgetfilecon"),
                                FV("ACL_1.0(9)", label="acl_extended_file"),
                                FV("ACL_1.0(9)", label="acl_get_entry"),
                                FV("ACL_1.0(9)", label="acl_get_tag_type"),
                                FV("ACL_1.2(7)", label="acl_extended_file_nofollow"),
                                FV("GLIBC_2.0(2)", label="__assert_fail"),
                                FV("GLIBC_2.0(2)", label="__ctype_get_mb_cur_max"),
                                FV("GLIBC_2.0(2)", label="__errno_location"),
                                FV("GLIBC_2.0(2)", label="__libc_start_main"),
                                FV("GLIBC_2.0(2)", label="__overflow"),
                                FV("GLIBC_2.0(2)", label="__progname"),
                                FV("GLIBC_2.0(2)", label="__progname_full"),
                                FV("GLIBC_2.0(2)", label="__strtoull_internal"),
                                FV("GLIBC_2.0(2)", label="_exit"),
                                FV("GLIBC_2.0(2)", label="_obstack_begin"),
                                FV("GLIBC_2.0(2)", label="_obstack_newchunk"),
                                FV("GLIBC_2.0(2)", label="_setjmp"),
                                FV("GLIBC_2.0(2)", label="abort"),
                                FV("GLIBC_2.0(2)", label="bindtextdomain"),
                                FV("GLIBC_2.0(2)", label="calloc"),
                                FV("GLIBC_2.0(2)", label="closedir"),
                                FV("GLIBC_2.0(2)", label="dcgettext"),
                                FV("GLIBC_2.0(2)", label="dirfd"),
                                FV("GLIBC_2.0(2)", label="error"),
                                FV("GLIBC_2.0(2)", label="exit"),
                                FV("GLIBC_2.0(2)", label="fflush_unlocked"),
                                FV("GLIBC_2.0(2)", label="free"),
                                FV("GLIBC_2.0(2)", label="fwrite"),
                                FV("GLIBC_2.0(2)", label="getenv"),
                                FV("GLIBC_2.0(2)", label="getgrgid"),
                                FV("GLIBC_2.0(2)", label="getgrnam"),
                                FV("GLIBC_2.0(2)", label="getopt_long"),
                                FV("GLIBC_2.0(2)", label="getpwnam"),
                                FV("GLIBC_2.0(2)", label="getpwuid"),
                                FV("GLIBC_2.0(2)", label="gettimeofday"),
                                FV("GLIBC_2.0(2)", label="ioctl"),
                                FV("GLIBC_2.0(2)", label="isatty"),
                                FV("GLIBC_2.0(2)", label="iswcntrl"),
                                FV("GLIBC_2.0(2)", label="iswprint"),
                                FV("GLIBC_2.0(2)", label="localtime"),
                                FV("GLIBC_2.0(2)", label="malloc"),
                                FV("GLIBC_2.0(2)", label="mbrtowc"),
                                FV("GLIBC_2.0(2)", label="mbsinit"),
                                FV("GLIBC_2.0(2)", label="mbstowcs"),
                                FV("GLIBC_2.0(2)", label="memcpy"),
                                FV("GLIBC_2.0(2)", label="memmove"),
                                FV("GLIBC_2.0(2)", label="memset"),
                                FV("GLIBC_2.0(2)", label="mktime"),
                                FV("GLIBC_2.0(2)", label="nl_langinfo"),
                                FV("GLIBC_2.0(2)", label="opendir"),
                                FV("GLIBC_2.0(2)", label="optarg"),
                                FV("GLIBC_2.0(2)", label="optind"),
                                FV("GLIBC_2.0(2)", label="program_invocation_name"),
                                FV("GLIBC_2.0(2)", label="program_invocation_short_name"),
                                FV("GLIBC_2.0(2)", label="raise"),
                                FV("GLIBC_2.0(2)", label="readlink"),
                                FV("GLIBC_2.0(2)", label="realloc"),
                                FV("GLIBC_2.0(2)", label="setlocale"),
                                FV("GLIBC_2.0(2)", label="sigaction"),
                                FV("GLIBC_2.0(2)", label="sigaddset"),
                                FV("GLIBC_2.0(2)", label="sigemptyset"),
                                FV("GLIBC_2.0(2)", label="sigismember"),
                                FV("GLIBC_2.0(2)", label="signal"),
                                FV("GLIBC_2.0(2)", label="sigprocmask"),
                                FV("GLIBC_2.0(2)", label="stderr"),
                                FV("GLIBC_2.0(2)", label="stdout"),
                                FV("GLIBC_2.0(2)", label="stpcpy"),
                                FV("GLIBC_2.0(2)", label="strchr"),
                                FV("GLIBC_2.0(2)", label="strcmp"),
                                FV("GLIBC_2.0(2)", label="strcoll"),
                                FV("GLIBC_2.0(2)", label="strcpy"),
                                FV("GLIBC_2.0(2)", label="strftime"),
                                FV("GLIBC_2.0(2)", label="strlen"),
                                FV("GLIBC_2.0(2)", label="strncmp"),
                                FV("GLIBC_2.0(2)", label="strncpy"),
                                FV("GLIBC_2.0(2)", label="strrchr"),
                                FV("GLIBC_2.0(2)", label="strstr"),
                                FV("GLIBC_2.0(2)", label="strtoul"),
                                FV("GLIBC_2.0(2)", label="tcgetpgrp"),
                                FV("GLIBC_2.0(2)", label="textdomain"),
                                FV("GLIBC_2.0(2)", label="wcstombs"),
                                FV("GLIBC_2.0(2)", label="wcwidth"),
                                FV("GLIBC_2.1(5)", label="fclose"),
                                FV("GLIBC_2.1(5)", label="fputs_unlocked"),
                                FV("GLIBC_2.1(5)", label="fwrite_unlocked"),
                                FV("GLIBC_2.1(5)", label="mempcpy"),
                                FV("GLIBC_2.1.3(4)", label="__cxa_atexit"),
                                FV("GLIBC_2.2(10)", label="clock_gettime"),
                                FV("GLIBC_2.2(3)", label="__fpending"),
                                FV("GLIBC_2.2(3)", label="__fxstat64"),
                                FV("GLIBC_2.2(3)", label="__lxstat64"),
                                FV("GLIBC_2.2(3)", label="__xstat64"),
                                FV("GLIBC_2.2(3)", label="localeconv"),
                                FV("GLIBC_2.2(3)", label="readdir64"),
                                FV("GLIBC_2.2.3(12)", label="fnmatch"),
                                FV("GLIBC_2.3(8)", label="__ctype_b_loc"),
                                FV("GLIBC_2.3(8)", label="__ctype_tolower_loc"),
                                FV("GLIBC_2.3(8)", label="__ctype_toupper_loc"),
                                FV("GLIBC_2.3.4(6)", label="__fprintf_chk"),
                                FV("GLIBC_2.3.4(6)", label="__memcpy_chk"),
                                FV("GLIBC_2.3.4(6)", label="__mempcpy_chk"),
                                FV("GLIBC_2.3.4(6)", label="__printf_chk"),
                                FV("GLIBC_2.3.4(6)", label="__sprintf_chk"),
                                FV("GLIBC_2.4(11)", label="__stack_chk_fail"),
                            ],
                            "elf_import_visibility": [
                                FV("DEFAULT", label="__assert_fail"),
                                FV("DEFAULT", label="__ctype_b_loc"),
                                FV("DEFAULT", label="__ctype_get_mb_cur_max"),
                                FV("DEFAULT", label="__ctype_tolower_loc"),
                                FV("DEFAULT", label="__ctype_toupper_loc"),
                                FV("DEFAULT", label="__cxa_atexit"),
                                FV("DEFAULT", label="__errno_location"),
                                FV("DEFAULT", label="__fpending"),
                                FV("DEFAULT", label="__fprintf_chk"),
                                FV("DEFAULT", label="__fxstat64"),
                                FV("DEFAULT", label="__libc_start_main"),
                                FV("DEFAULT", label="__lxstat64"),
                                FV("DEFAULT", label="__memcpy_chk"),
                                FV("DEFAULT", label="__mempcpy_chk"),
                                FV("DEFAULT", label="__overflow"),
                                FV("DEFAULT", label="__printf_chk"),
                                FV("DEFAULT", label="__progname"),
                                FV("DEFAULT", label="__progname_full"),
                                FV("DEFAULT", label="__sprintf_chk"),
                                FV("DEFAULT", label="__stack_chk_fail"),
                                FV("DEFAULT", label="__strtoull_internal"),
                                FV("DEFAULT", label="__xstat64"),
                                FV("DEFAULT", label="_exit"),
                                FV("DEFAULT", label="_obstack_begin"),
                                FV("DEFAULT", label="_obstack_newchunk"),
                                FV("DEFAULT", label="_setjmp"),
                                FV("DEFAULT", label="abort"),
                                FV("DEFAULT", label="acl_extended_file"),
                                FV("DEFAULT", label="acl_extended_file_nofollow"),
                                FV("DEFAULT", label="acl_get_entry"),
                                FV("DEFAULT", label="acl_get_tag_type"),
                                FV("DEFAULT", label="bindtextdomain"),
                                FV("DEFAULT", label="calloc"),
                                FV("DEFAULT", label="cap_free"),
                                FV("DEFAULT", label="cap_get_file"),
                                FV("DEFAULT", label="cap_to_text"),
                                FV("DEFAULT", label="clock_gettime"),
                                FV("DEFAULT", label="closedir"),
                                FV("DEFAULT", label="dcgettext"),
                                FV("DEFAULT", label="dirfd"),
                                FV("DEFAULT", label="error"),
                                FV("DEFAULT", label="exit"),
                                FV("DEFAULT", label="fclose"),
                                FV("DEFAULT", label="fflush_unlocked"),
                                FV("DEFAULT", label="fgetfilecon"),
                                FV("DEFAULT", label="fnmatch"),
                                FV("DEFAULT", label="fputs_unlocked"),
                                FV("DEFAULT", label="free"),
                                FV("DEFAULT", label="freecon"),
                                FV("DEFAULT", label="fwrite"),
                                FV("DEFAULT", label="fwrite_unlocked"),
                                FV("DEFAULT", label="getenv"),
                                FV("DEFAULT", label="getfilecon"),
                                FV("DEFAULT", label="getgrgid"),
                                FV("DEFAULT", label="getgrnam"),
                                FV("DEFAULT", label="getopt_long"),
                                FV("DEFAULT", label="getpwnam"),
                                FV("DEFAULT", label="getpwuid"),
                                FV("DEFAULT", label="gettimeofday"),
                                FV("DEFAULT", label="ioctl"),
                                FV("DEFAULT", label="isatty"),
                                FV("DEFAULT", label="iswcntrl"),
                                FV("DEFAULT", label="iswprint"),
                                FV("DEFAULT", label="lgetfilecon"),
                                FV("DEFAULT", label="localeconv"),
                                FV("DEFAULT", label="localtime"),
                                FV("DEFAULT", label="malloc"),
                                FV("DEFAULT", label="mbrtowc"),
                                FV("DEFAULT", label="mbsinit"),
                                FV("DEFAULT", label="mbstowcs"),
                                FV("DEFAULT", label="memcpy"),
                                FV("DEFAULT", label="memmove"),
                                FV("DEFAULT", label="mempcpy"),
                                FV("DEFAULT", label="memset"),
                                FV("DEFAULT", label="mktime"),
                                FV("DEFAULT", label="nl_langinfo"),
                                FV("DEFAULT", label="opendir"),
                                FV("DEFAULT", label="optarg"),
                                FV("DEFAULT", label="optind"),
                                FV("DEFAULT", label="program_invocation_name"),
                                FV("DEFAULT", label="program_invocation_short_name"),
                                FV("DEFAULT", label="raise"),
                                FV("DEFAULT", label="readdir64"),
                                FV("DEFAULT", label="readlink"),
                                FV("DEFAULT", label="realloc"),
                                FV("DEFAULT", label="setlocale"),
                                FV("DEFAULT", label="sigaction"),
                                FV("DEFAULT", label="sigaddset"),
                                FV("DEFAULT", label="sigemptyset"),
                                FV("DEFAULT", label="sigismember"),
                                FV("DEFAULT", label="signal"),
                                FV("DEFAULT", label="sigprocmask"),
                                FV("DEFAULT", label="stderr"),
                                FV("DEFAULT", label="stdout"),
                                FV("DEFAULT", label="stpcpy"),
                                FV("DEFAULT", label="strchr"),
                                FV("DEFAULT", label="strcmp"),
                                FV("DEFAULT", label="strcoll"),
                                FV("DEFAULT", label="strcpy"),
                                FV("DEFAULT", label="strftime"),
                                FV("DEFAULT", label="strlen"),
                                FV("DEFAULT", label="strncmp"),
                                FV("DEFAULT", label="strncpy"),
                                FV("DEFAULT", label="strrchr"),
                                FV("DEFAULT", label="strstr"),
                                FV("DEFAULT", label="strtoul"),
                                FV("DEFAULT", label="tcgetpgrp"),
                                FV("DEFAULT", label="textdomain"),
                                FV("DEFAULT", label="wcstombs"),
                                FV("DEFAULT", label="wcwidth"),
                            ],
                            "elf_machine": [FV("Intel 80386")],
                            "elf_note": [FV(0), FV(1)],
                            "elf_note_abi": [FV("LINUX", label="0")],
                            "elf_note_description": [
                                FV("00 00 00 00 02 00 00 00 06 00 00 00 12 00 00 00", label="0"),
                                FV("28 46 15 4a a6 79 b3 08 2b 4d c3 03 49 ec 5a 5b 27 62 ca 2b", label="1"),
                            ],
                            "elf_note_name": [FV("GNU", label="0"), FV("GNU", label="1")],
                            "elf_note_type": [FV("GNU_ABI_TAG", label="0"), FV("GNU_BUILD_ID", label="1")],
                            "elf_note_version": [FV("2.6.18", label="0")],
                            "elf_num_prog_headers": [FV(8)],
                            "elf_num_section_headers": [FV(29)],
                            "elf_obj_version": [FV("0x1")],
                            "elf_os_abi": [FV("UNIX - System V")],
                            "elf_processor_flag": [FV(0)],
                            "elf_program_header_offset": [FV(52)],
                            "elf_program_header_size": [FV(32)],
                            "elf_section": [
                                FV("", offset=0, size=0),
                                FV(".bss", offset=112992, size=3104),
                                FV(".ctors", offset=110592, size=8),
                                FV(".data", offset=112704, size=288),
                                FV(".data.rel.ro", offset=110624, size=1348),
                                FV(".dtors", offset=110600, size=8),
                                FV(".dynamic", offset=111972, size=232),
                                FV(".dynstr", offset=2548, size=1542),
                                FV(".dynsym", offset=500, size=2048),
                                FV(".eh_frame", offset=98372, size=10908),
                                FV(".eh_frame_hdr", offset=96584, size=1788),
                                FV(".fini", offset=81212, size=28),
                                FV(".gnu.hash", offset=396, size=104),
                                FV(".gnu.version", offset=4090, size=256),
                                FV(".gnu.version_r", offset=4348, size=224),
                                FV(".gnu_debuglink", offset=112992, size=16),
                                FV(".got", offset=112204, size=76),
                                FV(".got.plt", offset=112280, size=424),
                                FV(".init", offset=5540, size=48),
                                FV(".interp", offset=308, size=19),
                                FV(".jcr", offset=110608, size=4),
                                FV(".note.ABI-tag", offset=328, size=32),
                                FV(".note.gnu.build-id", offset=360, size=36),
                                FV(".plt", offset=5588, size=1664),
                                FV(".rel.dyn", offset=4572, size=144),
                                FV(".rel.plt", offset=4716, size=824),
                                FV(".rodata", offset=81248, size=15336),
                                FV(".shstrtab", offset=113008, size=255),
                                FV(".text", offset=7264, size=73948),
                            ],
                            "elf_section_alignment": [
                                FV(0, label=""),
                                FV(1, label=".dynstr"),
                                FV(1, label=".interp"),
                                FV(1, label=".shstrtab"),
                                FV(2, label=".gnu.version"),
                                FV(4, label=".ctors"),
                                FV(4, label=".dtors"),
                                FV(4, label=".dynamic"),
                                FV(4, label=".dynsym"),
                                FV(4, label=".eh_frame"),
                                FV(4, label=".eh_frame_hdr"),
                                FV(4, label=".fini"),
                                FV(4, label=".gnu.hash"),
                                FV(4, label=".gnu.version_r"),
                                FV(4, label=".gnu_debuglink"),
                                FV(4, label=".got"),
                                FV(4, label=".got.plt"),
                                FV(4, label=".init"),
                                FV(4, label=".jcr"),
                                FV(4, label=".note.ABI-tag"),
                                FV(4, label=".note.gnu.build-id"),
                                FV(4, label=".plt"),
                                FV(4, label=".rel.dyn"),
                                FV(4, label=".rel.plt"),
                                FV(16, label=".text"),
                                FV(32, label=".bss"),
                                FV(32, label=".data"),
                                FV(32, label=".data.rel.ro"),
                                FV(32, label=".rodata"),
                            ],
                            "elf_section_entropy": [
                                FV(0.0, label=""),
                                FV(0.0, label=".bss"),
                                FV(-0.0, label=".jcr"),
                                FV(0.4027354068140264, label=".got"),
                                FV(1.0, label=".ctors"),
                                FV(1.0, label=".dtors"),
                                FV(1.748689844084022, label=".note.ABI-tag"),
                                FV(1.8798769996636207, label=".gnu.version"),
                                FV(1.91737028396309, label=".dynsym"),
                                FV(2.6402452367306295, label=".data"),
                                FV(2.8463028206284693, label=".dynamic"),
                                FV(3.0253964915277973, label=".gnu.version_r"),
                                FV(3.5, label=".gnu_debuglink"),
                                FV(3.5147034725827977, label=".rel.dyn"),
                                FV(3.6373380259281896, label=".data.rel.ro"),
                                FV(3.681880802803402, label=".interp"),
                                FV(3.768224670868764, label=".got.plt"),
                                FV(4.03914867190307, label=".fini"),
                                FV(4.136056086195821, label=".note.gnu.build-id"),
                                FV(4.295504807239659, label=".shstrtab"),
                                FV(4.320232600513377, label=".rel.plt"),
                                FV(4.326248421937603, label=".init"),
                                FV(4.464984882198269, label=".plt"),
                                FV(4.640776173133139, label=".dynstr"),
                                FV(5.131131709037912, label=".eh_frame_hdr"),
                                FV(5.167466049154478, label=".rodata"),
                                FV(5.227974299651544, label=".eh_frame"),
                                FV(5.3513650784891915, label=".gnu.hash"),
                                FV(6.167756787409701, label=".text"),
                            ],
                            "elf_section_entry_size": [
                                FV(0, label=""),
                                FV(0, label=".bss"),
                                FV(0, label=".ctors"),
                                FV(0, label=".data"),
                                FV(0, label=".data.rel.ro"),
                                FV(0, label=".dtors"),
                                FV(0, label=".dynstr"),
                                FV(0, label=".eh_frame"),
                                FV(0, label=".eh_frame_hdr"),
                                FV(0, label=".fini"),
                                FV(0, label=".gnu.version_r"),
                                FV(0, label=".gnu_debuglink"),
                                FV(0, label=".init"),
                                FV(0, label=".interp"),
                                FV(0, label=".jcr"),
                                FV(0, label=".note.ABI-tag"),
                                FV(0, label=".note.gnu.build-id"),
                                FV(0, label=".rodata"),
                                FV(0, label=".shstrtab"),
                                FV(0, label=".text"),
                                FV(2, label=".gnu.version"),
                                FV(4, label=".gnu.hash"),
                                FV(4, label=".got"),
                                FV(4, label=".got.plt"),
                                FV(4, label=".plt"),
                                FV(8, label=".dynamic"),
                                FV(8, label=".rel.dyn"),
                                FV(8, label=".rel.plt"),
                                FV(16, label=".dynsym"),
                            ],
                            "elf_section_flags": [
                                FV("", label=""),
                                FV("", label=".gnu_debuglink"),
                                FV("", label=".shstrtab"),
                                FV("A", label=".dynstr"),
                                FV("A", label=".dynsym"),
                                FV("A", label=".eh_frame"),
                                FV("A", label=".eh_frame_hdr"),
                                FV("A", label=".gnu.hash"),
                                FV("A", label=".gnu.version"),
                                FV("A", label=".gnu.version_r"),
                                FV("A", label=".interp"),
                                FV("A", label=".note.ABI-tag"),
                                FV("A", label=".note.gnu.build-id"),
                                FV("A", label=".rel.dyn"),
                                FV("A", label=".rel.plt"),
                                FV("A", label=".rodata"),
                                FV("AX", label=".fini"),
                                FV("AX", label=".init"),
                                FV("AX", label=".plt"),
                                FV("AX", label=".text"),
                                FV("WA", label=".bss"),
                                FV("WA", label=".ctors"),
                                FV("WA", label=".data"),
                                FV("WA", label=".data.rel.ro"),
                                FV("WA", label=".dtors"),
                                FV("WA", label=".dynamic"),
                                FV("WA", label=".got"),
                                FV("WA", label=".got.plt"),
                                FV("WA", label=".jcr"),
                            ],
                            "elf_section_hash": [
                                FV(
                                    "0145182123463d1ffa04b35e298230c68b40cb216503d8dc9920a34324aae874",
                                    label=".gnu.version",
                                ),
                                FV(
                                    "0266989ad8d1fed08aafa5d8654682895da66883eeb0518463ea60a0f3889644",
                                    label=".rel.plt",
                                ),
                                FV(
                                    "1acf55d34fb5b8bdebe3554069e83cb0cbf5bd4aad94f13dcbc34301879fa6d0", label=".dynstr"
                                ),
                                FV("22d0b2d9190feec5e0621883ca6f44e082090dc6e806b3cb51dd17fdf4e0deb9", label=".got"),
                                FV(
                                    "29593214e289d2c6d56a404dcc0d2b869237fb2e43235fd29d2d948780d470b0",
                                    label=".data.rel.ro",
                                ),
                                FV(
                                    "2ca8c6fdfd014fccc014ee733d08e9ea30a65877536ba357dc24d5debac54ae3",
                                    label=".eh_frame",
                                ),
                                FV(
                                    "51951c009f64cb253420f93dd57aa9d2c34a1b53681c05f5a130a32c25272e04",
                                    label=".eh_frame_hdr",
                                ),
                                FV(
                                    "59251fadffc2bac51d6da5f55aef30e8f33f664c08f0a7af2d384feb3b005481",
                                    label=".shstrtab",
                                ),
                                FV(
                                    "5ea1c0596366c45f9a181372025ee3e74b796207a8539d1ebecad566b962f134",
                                    label=".gnu.hash",
                                ),
                                FV(
                                    "605b396258aa390909e4178dd6a06bf53da56ee6600b194da00d0b44e3d603e6", label=".rodata"
                                ),
                                FV(
                                    "72333ceb2db233f8834233aade4d6dc38d597dbc5243a81d675ca36b77daaf18",
                                    label=".gnu.version_r",
                                ),
                                FV("72a4fa3544e43a836ffcb268ce06ccdbc55d44d5e6b1b1c19216a53ea98301fd", label=".ctors"),
                                FV("72a4fa3544e43a836ffcb268ce06ccdbc55d44d5e6b1b1c19216a53ea98301fd", label=".dtors"),
                                FV("840b357102cba6e6bb6014aeffca9a528bfd614821098d1f358e98b32573753f", label=".data"),
                                FV(
                                    "849ddc2981b0026010be36fa7076ebce979b6416ac2550c6738d90613be35af3", label=".dynsym"
                                ),
                                FV("8b8a7fe39cf08c5cd7aaca4a6e0298a1ef561c077b392d0018c90a0267af517b", label=".plt"),
                                FV(
                                    "a04de509db9a5591162e6fc6783a076e75e3b587af1dbe7cefb1df1257e7c9f6",
                                    label=".rel.dyn",
                                ),
                                FV(
                                    "ac61c1275db96c3c870370367bc1d06baff58e56af5e0441c68de99e60269d7b",
                                    label=".gnu_debuglink",
                                ),
                                FV(
                                    "aeb1f9d10ae73cb49b36bbd846e5f51dac4bb2fabfee3c7f2c4cc0b339722d94",
                                    label=".note.ABI-tag",
                                ),
                                FV(
                                    "b5d7e70511f933da65799141f15a82f23e58a444b3d5f0407620f0f0c01baa91",
                                    label=".note.gnu.build-id",
                                ),
                                FV(
                                    "b9c8c60f94debc16dfcec5f43255ba10bd432857630052eaeb071b88a35421ef", label=".interp"
                                ),
                                FV("d820c3019f077eb850ed9000d0fea2e69ade06ae02bb23ea12f22b4e43e3a23d", label=".fini"),
                                FV("df3f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81119", label=".jcr"),
                                FV("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", label=""),
                                FV("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", label=".bss"),
                                FV("e43e51653b414c5bdf8221493ccef1692817ac6de597f6f5384eeb8eccc2fbe9", label=".text"),
                                FV(
                                    "ea7156fbacb3f16aa60f501e1bb8af797296f4b22411422c13f4897904a2981d",
                                    label=".dynamic",
                                ),
                                FV(
                                    "fa5a9cb9406cb6d668a8c0698ed56c1a0c0e7665b0bc30f773782c5f53495f2f",
                                    label=".got.plt",
                                ),
                                FV("fa6873817a57e6e768df8a5c2011cd6a1a705b889a408234801a5872d23de48b", label=".init"),
                            ],
                            "elf_section_header_offset": [FV(113264)],
                            "elf_section_header_size": [FV(40)],
                            "elf_section_information": [
                                FV(0, label=""),
                                FV(0, label=".bss"),
                                FV(0, label=".ctors"),
                                FV(0, label=".data"),
                                FV(0, label=".data.rel.ro"),
                                FV(0, label=".dtors"),
                                FV(0, label=".dynamic"),
                                FV(0, label=".dynstr"),
                                FV(0, label=".eh_frame"),
                                FV(0, label=".eh_frame_hdr"),
                                FV(0, label=".fini"),
                                FV(0, label=".gnu.hash"),
                                FV(0, label=".gnu.version"),
                                FV(0, label=".gnu_debuglink"),
                                FV(0, label=".got"),
                                FV(0, label=".got.plt"),
                                FV(0, label=".init"),
                                FV(0, label=".interp"),
                                FV(0, label=".jcr"),
                                FV(0, label=".note.ABI-tag"),
                                FV(0, label=".note.gnu.build-id"),
                                FV(0, label=".plt"),
                                FV(0, label=".rel.dyn"),
                                FV(0, label=".rodata"),
                                FV(0, label=".shstrtab"),
                                FV(0, label=".text"),
                                FV(1, label=".dynsym"),
                                FV(3, label=".gnu.version_r"),
                                FV(12, label=".rel.plt"),
                            ],
                            "elf_section_link": [
                                FV(0, label=""),
                                FV(0, label=".bss"),
                                FV(0, label=".ctors"),
                                FV(0, label=".data"),
                                FV(0, label=".data.rel.ro"),
                                FV(0, label=".dtors"),
                                FV(0, label=".dynstr"),
                                FV(0, label=".eh_frame"),
                                FV(0, label=".eh_frame_hdr"),
                                FV(0, label=".fini"),
                                FV(0, label=".gnu_debuglink"),
                                FV(0, label=".got"),
                                FV(0, label=".got.plt"),
                                FV(0, label=".init"),
                                FV(0, label=".interp"),
                                FV(0, label=".jcr"),
                                FV(0, label=".note.ABI-tag"),
                                FV(0, label=".note.gnu.build-id"),
                                FV(0, label=".plt"),
                                FV(0, label=".rodata"),
                                FV(0, label=".shstrtab"),
                                FV(0, label=".text"),
                                FV(5, label=".gnu.hash"),
                                FV(5, label=".gnu.version"),
                                FV(5, label=".rel.dyn"),
                                FV(5, label=".rel.plt"),
                                FV(6, label=".dynamic"),
                                FV(6, label=".dynsym"),
                                FV(6, label=".gnu.version_r"),
                            ],
                            "elf_section_name_table_idx": [FV(28)],
                            "elf_section_num_flags": [
                                FV(0, label=""),
                                FV(0, label=".gnu_debuglink"),
                                FV(0, label=".shstrtab"),
                                FV(2, label=".dynstr"),
                                FV(2, label=".dynsym"),
                                FV(2, label=".eh_frame"),
                                FV(2, label=".eh_frame_hdr"),
                                FV(2, label=".gnu.hash"),
                                FV(2, label=".gnu.version"),
                                FV(2, label=".gnu.version_r"),
                                FV(2, label=".interp"),
                                FV(2, label=".note.ABI-tag"),
                                FV(2, label=".note.gnu.build-id"),
                                FV(2, label=".rel.dyn"),
                                FV(2, label=".rel.plt"),
                                FV(2, label=".rodata"),
                                FV(3, label=".bss"),
                                FV(3, label=".ctors"),
                                FV(3, label=".data"),
                                FV(3, label=".data.rel.ro"),
                                FV(3, label=".dtors"),
                                FV(3, label=".dynamic"),
                                FV(3, label=".got"),
                                FV(3, label=".got.plt"),
                                FV(3, label=".jcr"),
                                FV(6, label=".fini"),
                                FV(6, label=".init"),
                                FV(6, label=".plt"),
                                FV(6, label=".text"),
                            ],
                            "elf_section_segments": [
                                FV("", label=""),
                                FV("", label=".gnu_debuglink"),
                                FV("", label=".shstrtab"),
                                FV("INTERP - LOAD", label=".interp"),
                                FV("LOAD", label=".bss"),
                                FV("LOAD", label=".ctors"),
                                FV("LOAD", label=".data"),
                                FV("LOAD", label=".data.rel.ro"),
                                FV("LOAD", label=".dtors"),
                                FV("LOAD", label=".dynstr"),
                                FV("LOAD", label=".dynsym"),
                                FV("LOAD", label=".eh_frame"),
                                FV("LOAD", label=".fini"),
                                FV("LOAD", label=".gnu.hash"),
                                FV("LOAD", label=".gnu.version"),
                                FV("LOAD", label=".gnu.version_r"),
                                FV("LOAD", label=".got"),
                                FV("LOAD", label=".got.plt"),
                                FV("LOAD", label=".init"),
                                FV("LOAD", label=".jcr"),
                                FV("LOAD", label=".plt"),
                                FV("LOAD", label=".rel.dyn"),
                                FV("LOAD", label=".rel.plt"),
                                FV("LOAD", label=".rodata"),
                                FV("LOAD", label=".text"),
                                FV("LOAD - DYNAMIC", label=".dynamic"),
                                FV("LOAD - GNU_EH_FRAME", label=".eh_frame_hdr"),
                                FV("LOAD - NOTE", label=".note.ABI-tag"),
                                FV("LOAD - NOTE", label=".note.gnu.build-id"),
                            ],
                            "elf_section_type": [
                                FV("DYNAMIC", label=".dynamic"),
                                FV("DYNSYM", label=".dynsym"),
                                FV("GNU_HASH", label=".gnu.hash"),
                                FV("NOBITS", label=".bss"),
                                FV("NOTE", label=".note.ABI-tag"),
                                FV("NOTE", label=".note.gnu.build-id"),
                                FV("NULL", label=""),
                                FV("PROGBITS", label=".ctors"),
                                FV("PROGBITS", label=".data"),
                                FV("PROGBITS", label=".data.rel.ro"),
                                FV("PROGBITS", label=".dtors"),
                                FV("PROGBITS", label=".eh_frame"),
                                FV("PROGBITS", label=".eh_frame_hdr"),
                                FV("PROGBITS", label=".fini"),
                                FV("PROGBITS", label=".gnu_debuglink"),
                                FV("PROGBITS", label=".got"),
                                FV("PROGBITS", label=".got.plt"),
                                FV("PROGBITS", label=".init"),
                                FV("PROGBITS", label=".interp"),
                                FV("PROGBITS", label=".jcr"),
                                FV("PROGBITS", label=".plt"),
                                FV("PROGBITS", label=".rodata"),
                                FV("PROGBITS", label=".text"),
                                FV("REL", label=".rel.dyn"),
                                FV("REL", label=".rel.plt"),
                                FV("STRTAB", label=".dynstr"),
                                FV("STRTAB", label=".shstrtab"),
                                FV("VERNEED", label=".gnu.version_r"),
                                FV("VERSYM", label=".gnu.version"),
                            ],
                            "elf_section_virtual_address": [
                                FV(0, label=""),
                                FV(0, label=".gnu_debuglink"),
                                FV(0, label=".shstrtab"),
                                FV(134512948, label=".interp"),
                                FV(134512968, label=".note.ABI-tag"),
                                FV(134513000, label=".note.gnu.build-id"),
                                FV(134513036, label=".gnu.hash"),
                                FV(134513140, label=".dynsym"),
                                FV(134515188, label=".dynstr"),
                                FV(134516730, label=".gnu.version"),
                                FV(134516988, label=".gnu.version_r"),
                                FV(134517212, label=".rel.dyn"),
                                FV(134517356, label=".rel.plt"),
                                FV(134518180, label=".init"),
                                FV(134518228, label=".plt"),
                                FV(134519904, label=".text"),
                                FV(134593852, label=".fini"),
                                FV(134593888, label=".rodata"),
                                FV(134609224, label=".eh_frame_hdr"),
                                FV(134611012, label=".eh_frame"),
                                FV(134623232, label=".ctors"),
                                FV(134623240, label=".dtors"),
                                FV(134623248, label=".jcr"),
                                FV(134623264, label=".data.rel.ro"),
                                FV(134624612, label=".dynamic"),
                                FV(134624844, label=".got"),
                                FV(134624920, label=".got.plt"),
                                FV(134625344, label=".data"),
                                FV(134625632, label=".bss"),
                            ],
                            "elf_segment": [
                                FV(0, offset=52, size=256),
                                FV(1, offset=308, size=19),
                                FV(2, offset=0, size=109280),
                                FV(3, offset=110592, size=2400),
                                FV(4, offset=111972, size=232),
                                FV(5, offset=328, size=68),
                                FV(6, offset=96584, size=1788),
                                FV(7, offset=0, size=0),
                            ],
                            "elf_segment_alignment": [
                                FV(1, label="1"),
                                FV(4, label="0"),
                                FV(4, label="4"),
                                FV(4, label="5"),
                                FV(4, label="6"),
                                FV(4, label="7"),
                                FV(4096, label="2"),
                                FV(4096, label="3"),
                            ],
                            "elf_segment_flags": [
                                FV("R--", label="1"),
                                FV("R--", label="5"),
                                FV("R--", label="6"),
                                FV("R-X", label="0"),
                                FV("R-X", label="2"),
                                FV("RW-", label="3"),
                                FV("RW-", label="4"),
                                FV("RW-", label="7"),
                            ],
                            "elf_segment_physical_address": [
                                FV(0, label="7"),
                                FV(134512640, label="2"),
                                FV(134512692, label="0"),
                                FV(134512948, label="1"),
                                FV(134512968, label="5"),
                                FV(134609224, label="6"),
                                FV(134623232, label="3"),
                                FV(134624612, label="4"),
                            ],
                            "elf_segment_sections": [
                                FV("", label="0"),
                                FV("", label="7"),
                                FV(
                                    ".ctors, .dtors, .jcr, .data.rel.ro, .dynamic, .got, .got.plt, .data, .bss",
                                    label="3",
                                ),
                                FV(".dynamic", label="4"),
                                FV(".eh_frame_hdr", label="6"),
                                FV(".interp", label="1"),
                                FV(
                                    ".interp, .note.ABI-tag, .note.gnu.build-id, .gnu.hash, .dynsym, .dynstr, .gnu.version, .gnu.version_r, .rel.dyn, .rel.plt, .init, .plt, .text, .fini, .rodata, .eh_frame_hdr, .eh_frame",
                                    label="2",
                                ),
                                FV(".note.ABI-tag, .note.gnu.build-id", label="5"),
                            ],
                            "elf_segment_type": [
                                FV("DYNAMIC", label="4"),
                                FV("GNU_EH_FRAME", label="6"),
                                FV("GNU_STACK", label="7"),
                                FV("INTERP", label="1"),
                                FV("LOAD", label="2"),
                                FV("LOAD", label="3"),
                                FV("NOTE", label="5"),
                                FV("PHDR", label="0"),
                            ],
                            "elf_segment_virtual_address": [
                                FV(0, label="7"),
                                FV(134512640, label="2"),
                                FV(134512692, label="0"),
                                FV(134512948, label="1"),
                                FV(134512968, label="5"),
                                FV(134609224, label="6"),
                                FV(134623232, label="3"),
                                FV(134624612, label="4"),
                            ],
                            "elf_segment_virtual_size": [
                                FV(0, label="7"),
                                FV(19, label="1"),
                                FV(68, label="5"),
                                FV(232, label="4"),
                                FV(256, label="0"),
                                FV(1788, label="6"),
                                FV(5504, label="3"),
                                FV(109280, label="2"),
                            ],
                            "elf_type": [FV("EXEC (Executable file)")],
                        },
                    )
                ],
            ),
        )
